cga.lgo: logo.asm
    masm -D?CGA -D?EGA -z-t-b63 logo;
    link logo;
    exe2bin logo.exe cga.lgo
    erase logo.obj
    erase logo.exe

egahires.lgo: cga.lgo
    copy cga.lgo egahires.lgo

egahibw.lgo: cga.lgo
    copy cga.lgo egahibw.lgo

hercules.lgo: logo.asm
    masm -D?HERCULES logo;
    link logo;
    exe2bin logo.exe hercules.lgo
    erase logo.obj
    erase logo.exe
