#   Windows Color Printer Library Makefile.
#

drawmode.obj:   drawmode.asm
        masm -z-t-b63 drawmode;

hidither.obj:   hidither.asm
        masm -z-t-b63 hidither;

chkstk.obj:   chkstk.asm
        masm -z-t-b63 chkstk;

robject.obj:   robject.asm
        masm -z-t-b63 robject;

enum.obj:   enum.asm
        masm -z-t-b63 enum;

colorinf.obj:   colorinf.asm
        masm -z-t-b63 colorinf;

pixel.obj:   pixel.asm
        masm -z-t-b63 pixel;

bitblt.obj:   bitblt.asm bitblteq.inc
        masm -z-t-b63 bitblt;

strblt.obj:   strblt.asm
        masm -z-t-b63 strblt;

output.obj:   output.asm
        masm -z-t-b63 output;

scanlr.obj:   scanlr.asm
        masm -z-t-b63 scanlr;

color.obj:   color.asm
        masm -z-t-b63 color;

dmcolor.lib:	drawmode.obj hidither.obj chkstk.obj robject.obj enum.obj \
		colorinf.obj pixel.obj bitblt.obj strblt.obj output.obj \
		scanlr.obj color.obj
                erase dmcolor.lib
                lib @dmcolor.scr
