//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by dptest.rc
//
#define IDD_DPTEST_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDD_CHOOSEPROVIDER              129
#define IDD_SELSESSION                  130
#define IDD_PLAYERS                     131
#define IDC_CREATE                      1000
#define IDC_CONNECT                     1001
#define IDC_CREATEPLAYER                1002
#define IDC_GETMESSAGE                  1003
#define IDC_SENDMESSAGE                 1004
#define IDC_RESULTS                     1006
#define IDC_EDIT                        1007
#define IDC_EDIT_TO                     1008
#define IDC_EDIT_FROM                   1009
#define IDC_SAVESESSION                 1010
#define IDC_OPENSESSION                 1011
#define IDC_BANDWIDTH                   1012
#define IDC_CLOSE                       1013
#define IDC_DESTROYPLAYER               1014
#define IDC_ENUMPLAYERS                 1015
#define IDC_GETCAPS                     1016
#define IDC_GETPLAYERCAPS               1017
#define IDC_GETPLAYERNAME               1018
#define IDC_SETPLAYERNAME               1019
#define IDC_ENABLENEWPLAYERS            1020
#define IDC_ADDPLAYERTOGRP              1021
#define IDC_LIST1                       1021
#define IDC_DELPLAYERFROMGRP            1022
#define IDC_CREATEGROUP                 1023
#define IDC_DESTROYGROUP                1024
#define IDC_LB_SESSION                  1024
#define IDC_ENUMGRP                     1025
#define IDC_FUTURE2                     1026
#define IDC_GETPLAYERS                  1026
#define IDC_FUTURE3                     1027
#define IDC_CLEAR                       1028
#define IDC_PLAYERLIST                  1028
#define IDC_STATIC1                     -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1029
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
