# Windows Sample Epson Raster Printer Driver
#
# NOTE: This sample code does not build the Epson raster printer drivers
#       included in Windows/286 Version 2.10.  It is intended as an example
#       dumb raster printer driver.  Use Microsoft C v5.10 to compile the
#       .C files.  GDI.LIB and USER.LIB can be found in the \PRINTERS\LIB 
#       directory on this diskette.
#                
# First, create .FNT stub files for use by the Resource Compiler:
#

ctofnt.obj: ctofnt.c
        cl -c -Zep -DLINT_ARGS ctofnt.c

pica5.fnt: pica5.c
        cl -c -Zep pica5.c
        link4 ctofnt pica5;
        ctofnt
        del pica5.obj
        del ctofnt.exe

pica8.fnt: pica8.c
        cl -c -Zep pica8.c
        link4 ctofnt pica8;
        ctofnt
        del pica8.obj
        del ctofnt.exe

pica10.fnt: pica10.c
        cl -c -Zep pica10.c
        link4 ctofnt pica10;
        ctofnt
        del pica10.obj
        del ctofnt.exe

pica17.fnt: pica17.c
        cl -c -Zep pica17.c
        link4 ctofnt pica17;
        ctofnt
        del pica17.obj
        del ctofnt.exe

elite6.fnt: elite6.c
        cl -c -Zep elite6.c
        link4 ctofnt elite6;
        ctofnt
        del elite6.obj
        del ctofnt.exe

elite12.fnt: elite12.c
        cl -c -Zep elite12.c
        link4 ctofnt elite12;
        ctofnt
        del elite12.obj
        del ctofnt.exe

ps6.fnt: ps6.c
        cl -c -Zep ps6.c
        link4 ctofnt ps6;
        ctofnt
        del ps6.obj
        del ctofnt.exe

ps12.fnt: ps12.c
        cl -c -Zep ps12.c
        link4 ctofnt ps12;
        ctofnt
        del ps12.obj
        del ctofnt.exe

ps6it.fnt: ps6it.c
        cl -c -Zep ps6it.c
        link4 ctofnt ps6it;
        ctofnt
        del ps6it.obj
        del ctofnt.exe

ps12it.fnt: ps12it.c
        cl -c -Zep ps12it.c
        link4 ctofnt ps12it;
        ctofnt
        del ps12it.obj
        del ctofnt.exe                                           

#
# Now compile the .FNT files along with other resources into EPSON.RES:
#

epson.res:	epson.rc pica5.fnt  pica8.fnt  pica10.fnt  pica17.fnt \
		elite6.fnt elite12.fnt ps6.fnt ps12.fnt ps6it.fnt ps12it.fnt
    rc -r -e epson.rc

#
# Now, compile the sources to the driver:
#

epson.obj:   epson.asm  epson.inc
    masm -DR120x72 -DWIDE_PG_SUPPORT -I. epson.asm;

reset.obj:   reset.c
    cl -u -d -c -Asnw -PLM -Gsw -Oas -Zpe -NT _TEXT reset.c

physical.obj:     physical.c
    cl -u -d -c -Asnw -PLM -Gsw -Oas -Zpe -NT _TEXT physical.c

stubs.obj:     stubs.c
    cl -u -d -c -Asnw -PLM -Gsw -Oas -Zpe -NT _TEXT stubs.c

devmode.obj:    devmode.c
    cl -u -d -c -Asnw -PLM -Gsw -Oas -Zpe -NT _CHAR devmode.c

control.obj:    control.c
    cl -u -d -c -Asnw -PLM -Gsw -Oas -Zpe -NT _TEXT control.c

realize.obj:  realize.c
    cl -u -d -c -Alnw -PLM -Gsw -Oas -Zpe -NT _CHAR realize.c

chphys.obj:     chphys.c
    cl -u -d -c -Alnw -PLM -Gsw -Oas -Zpe -NT _CHAR chphys.c

data.obj: data.c trans.dat  control.dat
    cl -u -d -c -Asnw -PLM -Gsw -Oas -Zpe -NT _CHAR data.c

epson.drv:  epson.lnk epson.def epson.obj devmode.obj \
                physical.obj stubs.obj control.obj reset.obj realize.obj \
                chphys.obj data.obj
    link4 @epson.lnk
    mapsym epson
    rc -e epson.res
    erase epson.drv
    ren epson.exe epson.drv
