### CGA System 10 Pt.
.\cgasys.fon:  cgasys.fnt cgasys.lnk cgasys.rc makefile cgasys.def \
               cgasys.rc cgasys.rcv
        ..\..\link4 @cgasys.lnk
        rc -k cgasys.rc cgasys.fon
        del cgasys.res
