all:  vgafix.fon vgaoem.fon vga850.fon vga860.fon vga861.fon vga863.fon \
      vga865.fon

### VGA System Only
vgafix.fon:  vgafix.FNT vgafix.DEF vgafix.RC vgafix.LNK makefile \
             vgafix.rc vgafix.rcv
        ..\..\link4 @vgafix.lnk
        rc -k vgafix.rc vgafix.fon
        del vgafix.res

### VGA US Oem Only
VGAOEM.fon:  VGAOEM.FNT VGAOEM.RC VGAOEM.DEF VGAOEM.LNK MAKEFILE \
             vgaoem.rc vgaoem.rcv
        ..\..\link4 @VGAOEM.lnk
        rc -k VGAOEM.rc VGAOEM.fon
        del VGAOEM.res

### VGA 850 Oem Only
VGA850.fon:  VGA850.FNT VGA850.RC VGA850.DEF VGA850.LNK MAKEFILE \
             vga850.rc vga850.rcv
        ..\..\link4 @VGA850.lnk
        rc -k VGA850.rc VGA850.fon
        del VGA850.res

### VGA 860 Oem Only
VGA860.fon:  VGA860.FNT VGA860.RC VGA860.DEF VGA860.LNK MAKEFILE \
             vga860.rc vga860.rcv
        ..\..\link4 @VGA860.lnk
        rc -k VGA860.rc VGA860.fon
        del VGA860.res

### VGA 861 Oem Only
VGA861.fon:  VGA861.FNT VGA861.RC VGA861.DEF VGA861.LNK MAKEFILE \
             vga861.rc vga861.rcv
        ..\..\link4 @VGA861.lnk
        rc -k VGA861.rc VGA861.fon
        del VGA861.res

### VGA 863 Oem Only
VGA863.fon:  VGA863.FNT VGA863.RC VGA863.DEF VGA863.LNK MAKEFILE \
             vga863.rc vga863.rcv
        ..\..\link4 @VGA863.lnk
        rc -k VGA863.rc VGA863.fon
        del VGA863.res

### VGA 865 Oem Only
VGA865.fon:  VGA865.FNT VGA865.RC VGA865.DEF VGA865.LNK MAKEFILE \
             vga865.rc vga865.rcv
        ..\..\link4 @VGA865.lnk
        rc -k VGA865.rc VGA865.fon
        del VGA865.res
