#   Windows VGA resource build file
#

color.obj:      color.asm
    masm -z-t-Ml-b63 color;

blkwhite.obj:   blkwhite.asm
    masm -z-t-Ml-b63 blkwhite;

config.obj:	config.asm
    masm -z-t-b63 config;

cconfig.bin:    config.obj color.obj
    link config color.obj,cconfig;
    exe2bin cconfig
    erase cconfig.exe

bconfig.bin:    config.obj blkwhite.obj
    link config blkwhite.obj,bconfig;
    exe2bin bconfig
    erase bconfig.exe

fonts.obj:	fonts.asm
    masm -z-t-b63 fonts;

fonts.bin:	fonts.obj
    link fonts;
    exe2bin fonts
    erase fonts.exe

# The VGA color resource is intended for use by the sample VGA color driver.  
# The monochrome resource is not used by any of the supplied sample 
# drivers but may be of use for medium resolution monochrome device drivers.

vgamono.res:    vga.rc       bconfig.bin                          \
		normal.cur   ibeam.cur	  wait.cur    cross.cur   \
		up.cur	     size.cur	  icon.cur    sample.ico  \
		hand.ico     ques.ico	  bang.ico    note.ico	  \
		right.bmp    left.bmp	  up.bmp      down.bmp	  \
		check.bmp    btsize.bmp   size.bmp    close.bmp   \
		button.bmp   btncorn.bmp  fonts.bin   hizoom.bmp  \
		sizenwse.cur sizenesw.cur sizewe.cur  sizens.cur  \
		hired.bmp
    copy bconfig.bin config.bin
    rc -r vga.rc
    erase config.bin
    copy vga.res vgamono.res
    erase vga.res


vga.res:        vga.rc       cconfig.bin                          \
		normal.cur   ibeam.cur	  wait.cur    cross.cur   \
		up.cur	     size.cur	  icon.cur    sample.ico  \
		hand.ico     ques.ico	  bang.ico    note.ico	  \
		right.bmp    left.bmp	  up.bmp      down.bmp	  \
		check.bmp    btsize.bmp   size.bmp    close.bmp   \
		button.bmp   btncorn.bmp  fonts.bin   hizoom.bmp  \
		sizenwse.cur sizenesw.cur sizewe.cur  sizens.cur  \
		hired.bmp
    copy cconfig.bin config.bin
    rc -r vga.rc
    erase config.bin

