//-----------------------------------------------------------------------------
// Microsoft Local Test Manager (LTM)
// Copyright (C) 1997 - 1999 By Microsoft Corporation.
//	  
// @doc
//												  
// @module DTMCommon.idl
//
//-----------------------------------------------------------------------------------

////////////////////////////////////////////////////////////////////////
// Imports
//
////////////////////////////////////////////////////////////////////////
import "unknwn.idl";
import "ModuleCore.idl";


////////////////////////////////////////////////////////////////////////
// ILTMSink
//
////////////////////////////////////////////////////////////////////////
[ object, uuid(1D9D6DF4-5DCC-11d0-82B1-00C04FC2CABA) ]
interface ILTMSink : IUnknown
{
	HRESULT		NotifyText([in, string] BSTR);
}

