/******************************************************************************\
*       This is a part of the Microsoft Source Code Samples. 
*       Copyright (C) 1993-1995 Microsoft Corporation.
*       All rights reserved. 
*       This source code is only intended as a supplement to 
*       Microsoft Development Tools and/or WinHelp documentation.
*       See these sources for detailed information regarding the 
*       Microsoft samples programs.
*
*		stdwin.h : include file for standard system include files,
*		or project specific include files that are used frequently, but
*		are changed infrequently
\******************************************************************************/

#include <windows.h>
#include <windowsx.h>
#include <commdlg.h>
#include <string.h>
