# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (C) 1992 Microsoft Corporation
# All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and Microsoft
# QuickHelp and/or WinHelp documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=STDREG
OBJS= dialog.obj typeinfo.obj columdlg.obj coursset.obj \
   dsectset.obj enrolset.obj instrset.obj sectset.obj stdreg.obj stdset.obj
USES_DB=1
EXTRA_LIBS=odbccp32.lib
UNICODE=0

!include ..\sample_.mak
