#
# TxtOut makefile
#
#############################################################################
#
#   THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
#   KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
#   PURPOSE.
#
#   Copyright (c) 1992, 1993  Microsoft Corporation.  All Rights Reserved.
#
#############################################################################

NAME	= TxtOut
EXT     = drv
OBJ     = drvproc.obj TxtOut.obj
DEFFILE = $(NAME).DEF

!if "$(DEBUG)" == "NO"
DEF  =
RC   = rc
CC   = cl -c -nologo -Asnw -G2s -Zp -W3 -Oxwt $(DEF)
ASM  = masm -Mx -t $(DEF)
LINK = link /NOD/NOE/MAP/NOPACKC/AL:16/ONERROR:NOEXE
LIBS = mdllcew libw mmsystem
!else
DEF  = -DDEBUG 
CC   = cl -c -nologo -Asnw -G2s -Zip -W3 -Oxwt $(DEF)
RC   = rc
ASM  = masm -Mx -Zi -t
LINK = link /CO/NOD/NOE/LI/NOPACKC/MAP/AL:16/ONERROR:NOEXE
LIBS = mdllcew libw mmsystem
!endif

.c.obj:
    $(CC) $*.c

.asm.obj:
    $(ASM) $*;

.rc.res:
    $(RC) $(DEF) -r $*.rc

goal:  $(NAME).$(EXT)
	@echo ***** finished making $(NAME) *****

$(NAME).$(EXT): $(OBJ) $(DEFFILE) $(NAME).res $(NAME).def libinit.obj
    $(LINK) @<<
    libinit.obj +
    $(OBJ),
    $(NAME).$(EXT),
    $(NAME).map,
    $(LIBS),
    $(DEFFILE)
<<
    $(RC) -t -31 $(NAME).res $(NAME).$(EXT)
    @mapsym /n $*.map

clean:
    -del $(NAME).$(EXT)
    -del $(NAME).res
    -del *.obj
    -del *.map
    -del *.sym
    -del *.cod

copy:
    copy $(NAME).$(EXT) ..\..\bin
    copy $(NAME).sym ..\..\bin
