BOOL	FAR PASCAL GetExtTable(LPDV, LPEXTTEXTDATA, LPSHORT);
short	FAR PASCAL GetEtm(LPDV, LPEXTTEXTDATA, LPSTR);
short	FAR PASCAL GetPairKern(LPDV, LPEXTTEXTDATA, LPSTR);
short	FAR PASCAL GetPSName(LPDV, LPEXTTEXTDATA, LPSTR);

