# -----------------------------------------------------------------------------
# $(MAPITEST)\samples\misc\makefile
#
# Copyright (C) 1995 Microsoft Corporation
# -----------------------------------------------------------------------------

!INCLUDE    "..\makestuf\xmake1.mak"

H           = $(MAPI)\$(SRCROOT)\misc

OBJS        = misctool.obj strtbl.obj pvalloc.obj mapiguid.obj

misctool.obj: \
  $H\misctool.c

strtbl.obj: \
  $H\strtbl.c

pvalloc.obj: \
  $H\pvalloc.c

mapiguid.obj: \
  $H\mapiguid.c

!INCLUDE    "..\makestuf\xmake2.mak"

