/* This header file machine-generated by mktyplib.exe */
/* Interface to type library: Lines */

#ifndef _Lines_H_
#define _Lines_H_

DEFINE_GUID(LIBID_Lines,0x3C591B20L,0x1F13,0x101B,0xB8,0x26,0x00,0xDD,0x01,0x10,0x3D,0xE1);

DEFINE_GUID(IID_IPoint,0x3C591B25L,0x1F13,0x101B,0xB8,0x26,0x00,0xDD,0x01,0x10,0x3D,0xE1);

/* Definition of interface: IPoint */
#undef INTERFACE
#define INTERFACE IPoint

DECLARE_INTERFACE_(IPoint, IDispatch)
{
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;

    /* IDispatch methods */
    STDMETHOD(GetTypeInfoCount)(THIS_ UINT FAR* pctinfo) PURE;

    STDMETHOD(GetTypeInfo)(
      THIS_
      UINT itinfo,
      LCID lcid,
      ITypeInfo FAR* FAR* pptinfo) PURE;

    STDMETHOD(GetIDsOfNames)(
      THIS_
      REFIID riid,
      OLECHAR FAR* FAR* rgszNames,
      UINT cNames,
      LCID lcid,
      DISPID FAR* rgdispid) PURE;

    STDMETHOD(Invoke)(
      THIS_
      DISPID dispidMember,
      REFIID riid,
      LCID lcid,
      WORD wFlags,
      DISPPARAMS FAR* pdispparams,
      VARIANT FAR* pvarResult,
      EXCEPINFO FAR* pexcepinfo,
      UINT FAR* puArgErr) PURE;
#endif

    /* IPoint methods */
    STDMETHOD(get_x)(THIS_ int FAR* retval) PURE;
    STDMETHOD(put_x)(THIS_ int Value) PURE;
    STDMETHOD(get_y)(THIS_ int FAR* retval) PURE;
    STDMETHOD(put_y)(THIS_ int Value) PURE;
};

DEFINE_GUID(IID_ILine,0x3C591B24L,0x1F13,0x101B,0xB8,0x26,0x00,0xDD,0x01,0x10,0x3D,0xE1);

/* Definition of interface: ILine */
#undef INTERFACE
#define INTERFACE ILine

DECLARE_INTERFACE_(ILine, IDispatch)
{
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;

    /* IDispatch methods */
    STDMETHOD(GetTypeInfoCount)(THIS_ UINT FAR* pctinfo) PURE;

    STDMETHOD(GetTypeInfo)(
      THIS_
      UINT itinfo,
      LCID lcid,
      ITypeInfo FAR* FAR* pptinfo) PURE;

    STDMETHOD(GetIDsOfNames)(
      THIS_
      REFIID riid,
      OLECHAR FAR* FAR* rgszNames,
      UINT cNames,
      LCID lcid,
      DISPID FAR* rgdispid) PURE;

    STDMETHOD(Invoke)(
      THIS_
      DISPID dispidMember,
      REFIID riid,
      LCID lcid,
      WORD wFlags,
      DISPPARAMS FAR* pdispparams,
      VARIANT FAR* pvarResult,
      EXCEPINFO FAR* pexcepinfo,
      UINT FAR* puArgErr) PURE;
#endif

    /* ILine methods */
    STDMETHOD(get_Color)(THIS_ long FAR* retval) PURE;
    STDMETHOD(put_Color)(THIS_ long rgb) PURE;
    STDMETHOD(get_EndPoint)(THIS_ IPoint FAR* FAR* retval) PURE;
    STDMETHOD(putref_EndPoint)(THIS_ IPoint FAR* Point) PURE;
    STDMETHOD(get_StartPoint)(THIS_ IPoint FAR* FAR* retval) PURE;
    STDMETHOD(putref_StartPoint)(THIS_ IPoint FAR* Point) PURE;
    STDMETHOD(get_Thickness)(THIS_ int FAR* retval) PURE;
    STDMETHOD(put_Thickness)(THIS_ int Value) PURE;
};

DEFINE_GUID(IID_ILines,0x3C591B26L,0x1F13,0x101B,0xB8,0x26,0x00,0xDD,0x01,0x10,0x3D,0xE1);

/* Definition of interface: ILines */
#undef INTERFACE
#define INTERFACE ILines

DECLARE_INTERFACE_(ILines, IDispatch)
{
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;

    /* IDispatch methods */
    STDMETHOD(GetTypeInfoCount)(THIS_ UINT FAR* pctinfo) PURE;

    STDMETHOD(GetTypeInfo)(
      THIS_
      UINT itinfo,
      LCID lcid,
      ITypeInfo FAR* FAR* pptinfo) PURE;

    STDMETHOD(GetIDsOfNames)(
      THIS_
      REFIID riid,
      OLECHAR FAR* FAR* rgszNames,
      UINT cNames,
      LCID lcid,
      DISPID FAR* rgdispid) PURE;

    STDMETHOD(Invoke)(
      THIS_
      DISPID dispidMember,
      REFIID riid,
      LCID lcid,
      WORD wFlags,
      DISPPARAMS FAR* pdispparams,
      VARIANT FAR* pvarResult,
      EXCEPINFO FAR* pexcepinfo,
      UINT FAR* puArgErr) PURE;
#endif

    /* ILines methods */
    STDMETHOD(Add)(THIS_ ILine FAR* NewLine) PURE;
    STDMETHOD(get_Count)(THIS_ long FAR* retval) PURE;
    STDMETHOD(get_Item)(THIS_ long Index, ILine FAR* FAR* retval) PURE;
    STDMETHOD(get__NewEnum)(THIS_ IUnknown * FAR* retval) PURE;
    STDMETHOD(Remove)(THIS_ long Index) PURE;
};

DEFINE_GUID(IID_IPoints,0x3C591B27L,0x1F13,0x101B,0xB8,0x26,0x00,0xDD,0x01,0x10,0x3D,0xE1);

/* Definition of interface: IPoints */
#undef INTERFACE
#define INTERFACE IPoints

DECLARE_INTERFACE_(IPoints, IDispatch)
{
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;

    /* IDispatch methods */
    STDMETHOD(GetTypeInfoCount)(THIS_ UINT FAR* pctinfo) PURE;

    STDMETHOD(GetTypeInfo)(
      THIS_
      UINT itinfo,
      LCID lcid,
      ITypeInfo FAR* FAR* pptinfo) PURE;

    STDMETHOD(GetIDsOfNames)(
      THIS_
      REFIID riid,
      OLECHAR FAR* FAR* rgszNames,
      UINT cNames,
      LCID lcid,
      DISPID FAR* rgdispid) PURE;

    STDMETHOD(Invoke)(
      THIS_
      DISPID dispidMember,
      REFIID riid,
      LCID lcid,
      WORD wFlags,
      DISPPARAMS FAR* pdispparams,
      VARIANT FAR* pvarResult,
      EXCEPINFO FAR* pexcepinfo,
      UINT FAR* puArgErr) PURE;
#endif

    /* IPoints methods */
    STDMETHOD(get_Count)(THIS_ long FAR* retval) PURE;
    STDMETHOD(get_Item)(THIS_ long Index, IPoint FAR* FAR* retval) PURE;
    STDMETHOD(get__NewEnum)(THIS_ IUnknown * FAR* retval) PURE;
};

DEFINE_GUID(IID_IPane,0x3C591B23L,0x1F13,0x101B,0xB8,0x26,0x00,0xDD,0x01,0x10,0x3D,0xE1);

/* Definition of interface: IPane */
#undef INTERFACE
#define INTERFACE IPane

DECLARE_INTERFACE_(IPane, IDispatch)
{
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;

    /* IDispatch methods */
    STDMETHOD(GetTypeInfoCount)(THIS_ UINT FAR* pctinfo) PURE;

    STDMETHOD(GetTypeInfo)(
      THIS_
      UINT itinfo,
      LCID lcid,
      ITypeInfo FAR* FAR* pptinfo) PURE;

    STDMETHOD(GetIDsOfNames)(
      THIS_
      REFIID riid,
      OLECHAR FAR* FAR* rgszNames,
      UINT cNames,
      LCID lcid,
      DISPID FAR* rgdispid) PURE;

    STDMETHOD(Invoke)(
      THIS_
      DISPID dispidMember,
      REFIID riid,
      LCID lcid,
      WORD wFlags,
      DISPPARAMS FAR* pdispparams,
      VARIANT FAR* pvarResult,
      EXCEPINFO FAR* pexcepinfo,
      UINT FAR* puArgErr) PURE;
#endif

    /* IPane methods */
    STDMETHOD(get_Lines)(THIS_ ILines FAR* FAR* retval) PURE;
    STDMETHOD(get_Points)(THIS_ IPoints FAR* FAR* retval) PURE;
    STDMETHOD(get_MaxX)(THIS_ int FAR* retval) PURE;
    STDMETHOD(get_MaxY)(THIS_ int FAR* retval) PURE;
    STDMETHOD(Clear)(THIS) PURE;
    STDMETHOD(Refresh)(THIS) PURE;
};

DEFINE_GUID(IID_IApplication,0x3C591B22L,0x1F13,0x101B,0xB8,0x26,0x00,0xDD,0x01,0x10,0x3D,0xE1);

/* Definition of interface: IApplication */
#undef INTERFACE
#define INTERFACE IApplication

DECLARE_INTERFACE_(IApplication, IDispatch)
{
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;

    /* IDispatch methods */
    STDMETHOD(GetTypeInfoCount)(THIS_ UINT FAR* pctinfo) PURE;

    STDMETHOD(GetTypeInfo)(
      THIS_
      UINT itinfo,
      LCID lcid,
      ITypeInfo FAR* FAR* pptinfo) PURE;

    STDMETHOD(GetIDsOfNames)(
      THIS_
      REFIID riid,
      OLECHAR FAR* FAR* rgszNames,
      UINT cNames,
      LCID lcid,
      DISPID FAR* rgdispid) PURE;

    STDMETHOD(Invoke)(
      THIS_
      DISPID dispidMember,
      REFIID riid,
      LCID lcid,
      WORD wFlags,
      DISPPARAMS FAR* pdispparams,
      VARIANT FAR* pvarResult,
      EXCEPINFO FAR* pexcepinfo,
      UINT FAR* puArgErr) PURE;
#endif

    /* IApplication methods */
    STDMETHOD(get_Application)(THIS_ IApplication FAR* FAR* retval) PURE;
    STDMETHOD(get_FullName)(THIS_ BSTR FAR* retval) PURE;
    STDMETHOD(get_Name)(THIS_ BSTR FAR* retval) PURE;
    STDMETHOD(get_Parent)(THIS_ IApplication FAR* FAR* retval) PURE;
    STDMETHOD(put_Visible)(THIS_ VARIANT_BOOL VisibleFlag) PURE;
    STDMETHOD(get_Visible)(THIS_ VARIANT_BOOL FAR* retval) PURE;
    STDMETHOD(Quit)(THIS) PURE;
    STDMETHOD(get_Pane)(THIS_ IPane FAR* FAR* retval) PURE;
    STDMETHOD(CreateLine)(THIS_ ILine FAR* FAR* retval) PURE;
    STDMETHOD(CreatePoint)(THIS_ IPoint FAR* FAR* retval) PURE;
};

DEFINE_GUID(CLSID_Lines,0x3C591B21L,0x1F13,0x101B,0xB8,0x26,0x00,0xDD,0x01,0x10,0x3D,0xE1);

#ifdef __cplusplus
class Lines;
#endif

#endif
