FILES = vmm01z.asm vmm02z.asm vmm03z.asm vmm04z.asm \
        vmm05z.asm vmm06z.asm vmm07z.asm vmm08z.asm \
        vmm09z.asm vmm0az.asm vmm0bz.asm vmm0cz.asm \
        vmm0dz.asm vmm0ez.asm vmm0fz.asm vmm10z.asm \
        vmm11z.asm vmm12z.asm vmm13z.asm vmm14z.asm \
        vmm15z.asm vmm16z.asm vmm17z.asm vmm18z.asm \
        vmm19z.asm vmm1az.asm vmm1bz.asm vmm1cz.asm \
        vmm1dz.asm vmm1ez.asm vmm1fz.asm vmm20z.asm \
        vmm21z.asm vmm22z.asm vmm23z.asm vmm24z.asm \
        vmm25z.asm vmm26z.asm vmm27z.asm vmm28z.asm \
        vmm29z.asm vmm2az.asm vmm2bz.asm vmm2cz.asm \
        vmm2dz.asm vmm2ez.asm vmm2fz.asm vmm30z.asm \
        vmm31z.asm vmm32z.asm vmm33z.asm vmm34z.asm \
        vmm35z.asm vmm36z.asm vmm37z.asm vmm38z.asm \
        vmm39z.asm vmm3az.asm vmm3bz.asm vmm3cz.asm \
        vmm3dz.asm vmm3ez.asm vmm3fz.asm vmm40z.asm \
        vmm41z.asm vmm42z.asm vmm43z.asm vmm44z.asm \
        vmm45z.asm vmm46z.asm vmm47z.asm

!include ..\local.mk
