DIRLIST =   cosmo       \
            patron

all: $(DIRLIST)

$(DIRLIST):
        cd $@
        @echo *** ole\inole2\chap14\$@ *** >>$(MSTOOLS)\samples\chap14.tmp
        @nmake -a -i -nologo >>$(MSTOOLS)\samples\chap14.tmp
        cd ..

