#
# app16.mak
#

proj1 = utsamp16

all : $(proj1).dll $(proj1).sym

#update the object files if necessary

$(proj1).obj : $*.c
   cl /c /ASw -G2sw -Ow /Od /Oi /Zi /Zd -W3 -Zp $*.c

# update the import library if necessary

$(proj1).lib : $*.def
   implib $@ $*.def

# update the executable files if necessary

$(proj1).map $(proj1).dll : $(proj1).obj $(proj1).def
   link $(proj1),$(proj1).dll,,/NOE /NOD:slibce /cod /li /map sdllcew libw.lib w32sut16.lib,$(proj1).def
   rc -t $(proj1).dll

$(proj1).sym: $*.map
   mapsym $*
