//--------------------------------------------------------------------------
//
// Module Name:  TABLES.H
//
// Brief Description:  This module contains tables used for the PSCRIPT
// driver's Printer Descriptor and Font Metric compilers.
//
// Author:  Kent Settle (kentse)
// Created: 16-Apr-1991
//
// Copyright (c) 1991 Microsoft Corporation
//
//--------------------------------------------------------------------------

//!!! put into resource - kentse.

TABLE_ENTRY KeywordTable[] =
{
    "*Product",                     PRODUCT,
    "*NickName",                    NICKNAME,
    "*ColorDevice",                 COLORDEVICE,
    "*FileSystem",                  FILESYSTEM,
    "*DefaultResolution",           DEFAULTRESOLUTION,
    "*DefaultTransfer",             DEFAULTTRANSFER,
    "*Transfer",                    TRANSFER,
    "*Protocols",                   PROTOCOLS,
    "*DefaultPageSize",             DEFAULTPAGESIZE,
    "*PageSize",                    PAGESIZE,
    "*PageRegion",                  PAGEREGION,
    "*DefaultImageableArea",        DEFAULTIMAGEABLEAREA,
    "*ImageableArea",               IMAGEABLEAREA,
    "*DefaultManualFeed",           DEFAULTMANUALFEED,
    "*ManualFeed",                  MANUALFEED,
    "*DefaultFont",                 DEFAULTFONT,
    "*Font",                        DEVICE_FONT,
    "*InputSlot",                   INPUTSLOT,
    "*DefaultOutputBin",            DEFAULTOUTPUTBIN,
    "*OutputBin",                   OUTPUTBIN,
    "*PaperDimension",              PAPERDIMENSION,
    "*DefaultInputSlot",            DEFAULTINPUTSLOT,
    "*ScreenFreq",                  SCREENFREQ,
    "*ScreenAngle",                 SCREENANGLE,
    "*FreeVM",                      PRTVM,
    "*SetResolution",               SETRESOLUTION,
    "*Resolution",                  RESOLUTION,
    "*VariablePaperSize",           VARIABLEPAPER,
    "*Duplex",                      DUPLEX,
    "*Collate",                     COLLATE,
    "*LanguageLevel",               LANGUAGELEVEL,
    "*EndOfFile",                   ENDOFFILE,  // extended PPD stuff
    NULL,                           0
};

TABLE_ENTRY SecondKeyTable[] =
{
    "Normalized",                   NORMALIZED,
    "Normalized.Inverse",           NORM_INVERSE,
    "True",                         OPTION_TRUE,
    "False",                        OPTION_FALSE,
    "DuplexTumble",                 DUPLEX_TUMBLE,
    "DuplexNoTumble",               DUPLEX_NO_TUMBLE,
    "None",                         OPTION_NONE,
    NULL,                           0
};

TABLE_ENTRY FontTable[] =
{
    "Arial",                        ARIAL,
    "Arial-Bold",                   ARIAL_BOLD,
    "Arial-BoldOblique",            ARIAL_BOLDOBLIQUE,
    "Arial-Oblique",                ARIAL_OBLIQUE,
    "Arial-Narrow",                 ARIAL_NARROW,
    "Arial-Narrow-Bold",            ARIAL_NARROW_BOLD,
    "Arial-Narrow-BoldOblique",     ARIAL_NARROW_BOLDOBLIQUE,
    "Arial-Narrow-Oblique",         ARIAL_NARROW_OBLIQUE,
    "AvantGarde-Book",              AVANTGARDE_BOOK,
    "AvantGarde-BookOblique",       AVANTGARDE_BOOKOBLIQUE,
    "AvantGarde-Demi",              AVANTGARDE_DEMI,
    "AvantGarde-DemiOblique",       AVANTGARDE_DEMIOBLIQUE,
    "Bookman-Demi",                 BOOKMAN_DEMI,
    "Bookman-DemiItalic",           BOOKMAN_DEMIITALIC,
    "Bookman-Light",                BOOKMAN_LIGHT,
    "Bookman-LightItalic",          BOOKMAN_LIGHTITALIC,
    "Courier",                      COURIER,
    "Courier-Bold",                 COURIER_BOLD,
    "Courier-BoldOblique",          COURIER_BOLDOBLIQUE,
    "Courier-Oblique",              COURIER_OBLIQUE,
    "Garamond-Bold",                GARAMOND_BOLD,
    "Garamond-BoldItalic",          GARAMOND_BOLDITALIC,
    "Garamond-Light",               GARAMOND_LIGHT,
    "Garamond-LightItalic",         GARAMOND_LIGHTITALIC,
    "Helvetica",                    HELVETICA,
    "Helvetica-Black",              HELVETICA_BLACK,
    "Helvetica-BlackOblique",       HELVETICA_BLACKOBLIQUE,
    "Helvetica-Bold",               HELVETICA_BOLD,
    "Helvetica-BoldOblique",        HELVETICA_BOLDOBLIQUE,
    "Helvetica-Condensed",          HELVETICA_CONDENSED,
    "Helvetica-Condensed-Bold",     HELVETICA_CONDENSED_BOLD,
    "Helvetica-Condensed-BoldObl",  HELVETICA_CONDENSED_BOLDOBL,
    "Helvetica-Condensed-Oblique",  HELVETICA_CONDENSED_OBLIQUE,
    "Helvetica-Light",              HELVETICA_LIGHT,
    "Helvetica-LightOblique",       HELVETICA_LIGHTOBLIQUE,
    "Helvetica-Narrow",             HELVETICA_NARROW,
    "Helvetica-Narrow-Bold",        HELVETICA_NARROW_BOLD,
    "Helvetica-Narrow-BoldOblique", HELVETICA_NARROW_BOLDOBLIQUE,
    "Helvetica-Narrow-Oblique",     HELVETICA_NARROW_OBLIQUE,
    "Helvetica-Oblique",            HELVETICA_OBLIQUE,
    "Korinna-Bold",                 KORINNA_BOLD,
    "Korinna-KursivBold",           KORINNA_KURSIVBOLD,
    "Korinna-KursivRegular",        KORINNA_KURSIVREGULAR,
    "Korinna-Regular",              KORINNA_REGULAR,
    "LubalinGraph-Book",            LUBALINGRAPH_BOOK,
    "LubalinGraph-BookOblique",     LUBALINGRAPH_BOOKOBLIQUE,
    "LubalinGraph-Demi",            LUBALINGRAPH_DEMI,
    "LubalinGraph-DemiOblique",     LUBALINGRAPH_DEMIOBLIQUE,
    "NewCenturySchlbk-Bold",        NEWCENTURYSCHLBK_BOLD,
    "NewCenturySchlbk-BoldItalic",  NEWCENTURYSCHLBK_BOLDITALIC,
    "NewCenturySchlbk-Italic",      NEWCENTURYSCHLBK_ITALIC,
    "NewCenturySchlbk-Roman",       NEWCENTURYSCHLBK_ROMAN,
    "Palatino-Bold",                PALATINO_BOLD,
    "Palatino-BoldItalic",          PALATINO_BOLDITALIC,
    "Palatino-Italic",              PALATINO_ITALIC,
    "Palatino-Roman",               PALATINO_ROMAN,
    "Souvenir-Demi",                SOUVENIR_DEMI,
    "Souvenir-DemiItalic",          SOUVENIR_DEMIITALIC,
    "Souvenir-Light",               SOUVENIR_LIGHT,
    "Souvenir-LightItalic",         SOUVENIR_LIGHTITALIC,
    "Symbol",                       SYMBOL,
    "Times-Bold",                   TIMES_BOLD,
    "Times-BoldItalic",             TIMES_BOLDITALIC,
    "Times-Italic",                 TIMES_ITALIC,
    "Times-Roman",                  TIMES_ROMAN,
    "Times-New-Roman",              TIMES_NEW_ROMAN,
    "Times-New-Roman-Bold",         TIMES_NEW_ROMAN_BOLD,
    "Times-New-Roman-BoldItalic",   TIMES_NEW_ROMAN_BOLDITALIC,
    "Times-New-Roman-Italic",       TIMES_NEW_ROMAN_ITALIC,
    "Varitimes#Bold",               VARITIMES_BOLD,
    "Varitimes#BoldItalic",         VARITIMES_BOLDITALIC,
    "Varitimes#Italic",             VARITIMES_ITALIC,
    "Varitimes#Roman",              VARITIMES_ROMAN,
    "ZapfCalligraphic-Bold",        ZAPFCALLIGRAPHIC_BOLD,
    "ZapfCalligraphic-BoldItalic",  ZAPFCALLIGRAPHIC_BOLDITALIC,
    "ZapfCalligraphic-Italic",      ZAPFCALLIGRAPHIC_ITALIC,
    "ZapfCalligraphic-Roman",       ZAPFCALLIGRAPHIC_ROMAN,
    "ZapfChancery-MediumItalic",    ZAPFCHANCERY_MEDIUMITALIC,
    "ZapfDingbats",                 ZAPFDINGBATS,
    NULL,                           NUM_INTERNAL_FONTS
}    ;

TABLE_ENTRY WeightTable[] =
{
    "Light",            PAN_WEIGHT_LIGHT,
    "LightCondensed",   PAN_WEIGHT_LIGHT,
    "Book",             PAN_WEIGHT_BOOK,
    "Medium",           PAN_WEIGHT_MEDIUM,
    "Roman",            PAN_WEIGHT_MEDIUM,
    "Regular",          PAN_WEIGHT_MEDIUM,
    "Italic",           PAN_WEIGHT_MEDIUM,
    "MediumCondensed",  PAN_WEIGHT_MEDIUM,
    "Bold",             PAN_WEIGHT_BOLD,
    "BoldItalic",       PAN_WEIGHT_BOLD,
    "Demi",             PAN_WEIGHT_DEMI,
    "Poster",           PAN_WEIGHT_BOLD,
    "Heavy",            PAN_WEIGHT_HEAVY,
    "Black",            PAN_WEIGHT_BLACK,
    "BlackCondensed",   PAN_WEIGHT_BLACK,
    "BoldCondensed",    PAN_WEIGHT_BOLD,
    NULL,               0
};

TABLE_ENTRY AFMKeywordTable[] =
{
    "FontBBox",             TK_FONTBBOX,
    "StartFontMetrics",     TK_STARTFONTMETRICS,
    "FontName",             TK_FONTNAME,
    "FullName",             TK_FULLNAME,
    "FamilyName",           TK_FAMILYNAME,
    "Weight",               TK_WEIGHT,
    "ItalicAngle",          TK_ITALICANGLE,
    "IsFixedPitch",         TK_ISFIXEDPITCH,
    "UnderlinePosition",    TK_UNDERLINEPOSITION,
    "UnderlineThickness",   TK_UNDERLINETHICKNESS,
    "CapHeight",            TK_CAPHEIGHT,
    "XHeight",              TK_XHEIGHT,
    "Descender",            TK_DESCENDER,
    "Ascender",             TK_ASCENDER,
    "StartCharMetrics",     TK_STARTCHARMETRICS,
    "EndCharMetrics",       TK_ENDCHARMETRICS,
    "StartKernData",        TK_STARTKERNDATA,
    "StartKernPairs",       TK_STARTKERNPAIRS,
    "KPX",                  TK_KPX,
    "EndKernPairs",         TK_ENDKERNPAIRS,
    "EndKernData",          TK_ENDKERNDATA,
    "EndFontMetrics",       TK_ENDFONTMETRICS,
    "EncodingScheme",       TK_ENCODINGSCHEME,
    "MSFamily",             TK_MSFAMILY,
    NULL,                   0
};

TABLE_ENTRY MSFamilyTable[] =
{
    "Roman",                FF_ROMAN,
    "Swiss",                FF_SWISS,
    "Decorative",           FF_DECORATIVE,
    "Modern",               FF_MODERN,
    "Script",               FF_SCRIPT,
    NULL,                   0
};

TT_FONT_MAPPING TTFamilyTable[] =
{
    L"Arial",                               L"Helvetica",
    L"Arial Narrow",                        L"Helvetica Narrow",
    L"Book Antiqua",                        L"Palatino",
    L"Bookman Old Style",                   L"Bookman",
    L"Century Gothic",                      L"ITC Avante Garde Gothic",
    L"Century Schoolbook",                  L"New Century Schoolbook",
    L"Courier New",                         L"Courier",
    L"Monotype Corsiva",                    L"ITC Zapf Chancery",
    L"Monotype Sorts",                      L"ITC Zapf Dingbats",
    L"Symbol",                              L"Symbol",
    L"Times New Roman",                     L"Times",
    NULL,                                   NULL
};

TT_FONT_MAPPING TTFontTable[] =
{
    L"Arial",                            L"Helvetica",
    L"Arial Bold",                       L"Helvetica-Bold",
    L"Arial Bold Italic",                L"Helvetica-BoldOblique",
    L"Arial Italic",                     L"Helvetica-Oblique",
    L"Arial Narrow",                     L"Helvetica-Narrow",
    L"Arial Narrow Bold",                L"Helvetica-Narrow-Bold",
    L"Arial Narrow Bold Italic",         L"Helvetica-Narrow-Bold-Oblique",
    L"Arial Narrow Italic",              L"Helvetica-Narrow-Italic",
    L"Book Antiqua",                     L"Palatino-Roman",
    L"Book Antiqua Bold",                L"Palatino-Bold",
    L"Book Antiqua Bold Italic",         L"Palatino-BoldItalic",
    L"Book Antiqua Italic",              L"Palatino-Italic",
    L"Bookman Old Style",                L"Bookman-Light",
    L"Bookman Old Style Bold",           L"Bookman-Demi",
    L"Bookman Old Style Bold Italic",    L"Bookman-DemiItalic",
    L"Bookman Old Style Italic",         L"Bookman-LightItalic",
    L"Century Gothic",                   L"AvanteGarde-Book",
    L"Century Gothic Bold",              L"AvanteGarde-Demi",
    L"Century Gothic Bold Italic",       L"AvanteGarde-DemiOblique",
    L"Century Gothic Italic",            L"AvanteGarde-Oblique",
    L"Century Schoolbook",               L"NewCenturySchlbk-Roman",
    L"Century Schoolbook Bold",          L"NewCenturySchlbk-Bold",
    L"Century Schoolbook Bold Italic",   L"NewCenturySchlbk-BoldItalic",
    L"Century Schoolbook Italic",        L"NewCenturySchlbk-Italic",
    L"Courier New",                      L"Courier",
    L"Courier New Bold",                 L"Courier-Bold",
    L"Courier New Bold Italic",          L"Courier-BoldOblique",
    L"Courier New Italic",               L"Courier-Oblique",
    L"Monotype Corsiva",                 L"ZapfChancery-MediumItalic",
    L"Monotype Sorts",                   L"ZapfDingbats",
    L"Times New Roman",                  L"Times-Roman",
    L"Times New Roman Bold",             L"Times-Bold",
    L"Times New Roman Bold Italic",      L"Times-BoldItalic",
    L"Times New Roman Italic",           L"Times-Italic",
    L"Symbol",                           L"Symbol",
    NULL,                               NULL
};


WINFONTPAIR WinFontTable[] =
{
    "Aachen-Bold",                              "Aachen",
    "AmericanTypewriter-Bold",                  "AmericanTypewriter",
    "AmericanTypewriter-Medium",                "AmericanTypewriter",
    "AvantGarde-Book",                          "AvantGarde",
    "AvantGarde-BookOblique",                   "AvantGarde",
    "AvantGarde-Demi",                          "AvantGarde",
    "AvantGarde-DemiOblique",                   "AvantGarde",
    "Benguiat-Bold",                            "Benguiat",
    "Benguiat-Book",                            "Benguiat",
    "Bodoni",                                   "Bodoni",
    "Bodoni-Bold",                              "Bodoni",
    "Bodoni-BoldItalic",                        "Bodoni",
    "Bodoni-Italic",                            "Bodoni",
    "Bodoni-Poster",                            "Bodoni",
    "Bookman-Demi",                             "Bookman",
    "Bookman-DemiItalic",                       "Bookman",
    "Bookman-Light",                            "Bookman",
    "Bookman-LightItalic",                      "Bookman",
    "BrushScript",                              "BrushScript",
    "Carta",                                    "Carta",
    "CenturyOldStyle-Bold",                     "CenturyOldStyle",
    "CenturyOldStyle-Italic",                   "CenturyOldStyle",
    "CenturyOldStyle-Regular",                  "CenturyOldStyle",
    "Cheltenham-Bold",                          "Cheltenham",
    "Cheltenham-BoldItalic",                    "Cheltenham",
    "Cheltenham-Book",                          "Cheltenham",
    "Cheltenham-BookItalic",                    "Cheltenham",
    "CooperBlack",                              "CooperBlack",
    "CooperBlack-Italic",                       "CooperBlack",
    "Courier",                                  "Courier",
    "Courier-Bold",                             "Courier",
    "Courier-BoldOblique",                      "Courier",
    "Courier-Oblique",                          "Courier",
    "FranklinGothic-Book",                      "FranklinGothic",
    "FranklinGothic-BookOblique",               "FranklinGothic",
    "FranklinGothic-Demi",                      "FranklinGothic",
    "FranklinGothic-DemiOblique",               "FranklinGothic",
    "FranklinGothic-Heavy",                     "FrGothHeavy",
    "FranklinGothic-HeavyOblique",              "FrGothHeavy",
    "FreestyleScript",                          "FreestyleScript",
    "FrizQuadrata",                             "FrizQuadrata",
    "FrizQuadrata-Bold",                        "FrizQuadrata",
    "Galliard-Bold",                            "Galliard",
    "Galliard-BoldItalic",                      "Galliard",
    "Galliard-Italic",                          "Galliard",
    "Galliard-Roman",                           "Galliard",
    "Garamond-Bold",                            "Garamond",
    "Garamond-BoldItalic",                      "Garamond",
    "Garamond-Light",                           "Garamond",
    "Garamond-LightItalic",                     "Garamond",
    "Glypha",                                   "Glypha",
    "Glypha-Bold",                              "Glypha",
    "Glypha-BoldOblique",                       "Glypha",
    "Glypha-Oblique",                           "Glypha",
    "Goudy",                                    "Goudy",
    "Goudy-Bold",                               "Goudy",
    "Goudy-BoldItalic",                         "Goudy",
    "Goudy-Italic",                             "Goudy",
    "Helvetica",                                "Helvetica",
    "Helvetica-Black",                          "Helvetica-Black",
    "Helvetica-BlackOblique",                   "Helvetica-Black",
    "Helvetica-Bold",                           "Helvetica",
    "Helvetica-BoldOblique",                    "Helvetica",
    "Helvetica-Condensed",                      "Helvetica-Condensed",
    "Helvetica-Condensed-Black",                "Helvetica-Condensed-Black",
    "Helvetica-Condensed-BlackObl",             "Helvetica-Condensed-Black",
    "Helvetica-Condensed-Bold",                 "Helvetica-Condensed",
    "Helvetica-Condensed-BoldObl",              "Helvetica-Condensed",
    "Helvetica-Condensed-Light",                "Helvetica-Condensed-Light",
    "Helvetica-Condensed-LightObl",             "Helvetica-Condensed-Light",
    "Helvetica-Condensed-Oblique",              "Helvetica-Condensed",
    "Helvetica-Light",                          "Helvetica-Light",
    "Helvetica-LightOblique",                   "Helvetica-Light",
    "Helvetica-Narrow",                         "Helvetica-Narrow",
    "Helvetica-Narrow-Bold",                    "Helvetica-Narrow",
    "Helvetica-Narrow-BoldOblique",             "Helvetica-Narrow",
    "Helvetica-Narrow-Oblique",                 "Helvetica-Narrow",
    "Helvetica-Oblique",                        "Helvetica",
    "Hobo",                                     "Hobo",
    "Korinna-Bold",                             "Korinna",
    "Korinna-KursivBold",                       "Korinna-Kursiv",
    "Korinna-KursivRegular",                    "Korinna-Kursiv",
    "Korinna-Regular",                          "Korinna",
    "LetterGothic",                             "LetterGothic",
    "LetterGothic-Bold",                        "LetterGothic",
    "LetterGothic-BoldSlanted",                 "LetterGothic",
    "LetterGothic-Slanted",                     "LetterGothic",
    "LubalinGraph-Book",                        "LubalinGraph",
    "LubalinGraph-BookOblique",                 "LubalinGraph",
    "LubalinGraph-Demi",                        "LubalinGraph",
    "LubalinGraph-DemiOblique",                 "LubalinGraph",
    "Machine",                                  "Machine",
    "Melior",                                   "Melior",
    "Melior-Bold",                              "Melior",
    "Melior-BoldItalic",                        "Melior",
    "Melior-Italic",                            "Melior",
    "NewBaskerville-Bold",                      "NewBaskerville",
    "NewBaskerville-BoldItalic",                "NewBaskerville",
    "NewBaskerville-Italic",                    "NewBaskerville",
    "NewBaskerville-Roman",                     "NewBaskerville",
    "NewCenturySchlbk-Bold",                    "NewCenturySchlbk",
    "NewCenturySchlbk-BoldItalic",              "NewCenturySchlbk",
    "NewCenturySchlbk-Italic",                  "NewCenturySchlbk",
    "NewCenturySchlbk-Roman",                   "NewCenturySchlbk",
    "NewsGothic",                               "NewsGothic",
    "NewsGothic-Bold",                          "NewsGothic",
    "NewsGothic-BoldOblique",                   "NewsGothic",
    "NewsGothic-Oblique",                       "NewsGothic",
    "Optima",                                   "Optima",
    "Optima-Bold",                              "Optima",
    "Optima-BoldOblique",                       "Optima",
    "Optima-Oblique",                           "Optima",
    "Orator-Slanted",                           "Orator",
    "Palatino-Bold",                            "Palatino",
    "Palatino-BoldItalic",                      "Palatino",
    "Palatino-Italic",                          "Palatino",
    "Palatino-Roman",                           "Palatino",
    "ParkAvenue",                               "ParkAvenue",
    "PrestigeElite",                            "PrestigeElite",
    "PrestigeElite-Bold",                       "PrestigeElite",
    "PrestigeElite-BoldSlanted",                "PrestigeElite",
    "PrestigeElite-Slanted",                    "PrestigeElite",
    "Revue",                                    "Revue",
    "Sonata",                                   "Sonata",
    "Souvenir-Demi",                            "Souvenir",
    "Souvenir-DemiItalic",                      "Souvenir",
    "Souvenir-Light",                           "Souvenir",
    "Souvenir-LightItalic",                     "Souvenir",
    "Stencil",                                  "Stencil",
    "Symbol",                                   "Symbol",
    "Tiffany",                                  "Tiffany",
    "Tiffany-Demi",                             "Tiffany",
    "Tiffany-DemiItalic",                       "Tiffany",
    "Tiffany-Heavy",                            "Tiffany",
    "Tiffany-HeavyItalic",                      "Tiffany",
    "Tiffany-Italic",                           "Tiffany",
    "Times-Bold",                               "Times",
    "Times-BoldItalic",                         "Times",
    "Times-Italic",                             "Times",
    "Times-Roman",                              "Times",
    "TrumpMediaeval-Bold",                      "TrumpMediaeval",
    "TrumpMediaeval-BoldItalic",                "TrumpMediaeval",
    "TrumpMediaeval-Italic",                    "TrumpMediaeval",
    "TrumpMediaeval-Roman",                     "TrumpMediaeval",
    "UniversityRoman",                          "UniversityRoman",
    "Varitimes#Bold",                           "Times Roman",
    "Varitimes#BoldItalic",                     "Times Roman",
    "Varitimes#Italic",                         "Times Roman",
    "Varitimes#Roman",                          "Times Roman",
    "ZapfChancery-MediumItalic",                "ZapfChancery",
    "ZapfDingbats",                             "ZapfDingbats",
    NULL,                                       NULL
};


TABLE_ENTRY PaperSourceTable[] =
{
    "Auto",                         DMBIN_AUTO,
    "Automatic",                    DMBIN_AUTO,
    "AutoSelect",                   DMBIN_AUTO,
    "Cassette",                     DMBIN_CASSETTE,
    "Envelope",                     DMBIN_ENVELOPE,
    "LargeCapacity",                DMBIN_LARGECAPACITY,
    "Lower",                        DMBIN_LOWER,
    "Manual",                       DMBIN_MANUAL,
    "ManualEnvelope",               DMBIN_ENVMANUAL,
    "Middle",                       DMBIN_MIDDLE,
    "PowerEnvelope",                DMBIN_ENVELOPE,
    "Upper",                        DMBIN_UPPER,
    NULL,                           0
};
