4plane:  ega vga svga

ega:
        set T_INC=$(MASM)
        del rc_med\display.rcv
        del rc_med\*.res
        cd ega
        $(MAKE)
	cd ..


vga:
        del rc_high\display.rcv
        del rc_high\*.res
        cd vga
        $(MAKE)
	cd ..

svga:
        del rc_high\display.rcv
        del rc_high\*.res
        cd svga
        $(MAKE)
	cd ..
