all : debug retail

debug:
    @if not exist ..\lib\nul  md ..\lib
    @if not exist ..\lib\debug\nul md ..\lib\debug
    nmake /f cgutil.mak  CFG="Win32 Debug"
    nmake /f linklist.mak CFG="Win32 Debug"
    copy windebug\linklist.lib ..\lib\debug
    
retail:
    @if not exist ..\lib\nul  md ..\lib
    @if not exist ..\lib\retail\nul md ..\lib\retail
    nmake /f cgutil.mak  CFG="Win32 Release"
    nmake /f linklist.mak CFG="Win32 Release"
    copy winrel\linklist.lib ..\lib\retail

