# Windows COMM Driver Makefile
#
ccom.obj: ccom.asm            
        masm -z-t-b63 ccom;

ibmcom.obj: ibmcom.asm ibmcom1.asm ibmcom.inc comdev.inc ins8250.inc
        masm -z-t-b63 ibmcom;

ibmint.obj: ibmint.asm ibmcom.inc comdev.inc ins8250.inc
        masm -z-t-b63 ibmint;

comm.drv: ccom.obj ibmcom.obj ibmint.obj comm.def
    link4 @comm.lnk
    mapsym comm
