##************************************************************************
##**
##**  THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
##**  ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED
##**  TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR
##**  A PARTICULAR PURPOSE.
##**
##**  Copyright (C) 1992, 1993 Microsoft Corporation. All Rights Reserved.
##**
##**  makefile
##**
##**
##************************************************************************

NAME	=mcivisca
EXT	=drv
GOALS	=$(NAME).$(EXT) $(NAME).sym
LIBS	=libw mlibcew mmsystem
OBJS	=libinitv.obj viscacom.obj commtask.obj viscamsg.obj mcicmds.obj mcidelay.obj mcivisca.obj common.obj

!if "$(DEBUG)" == "NO"

LOPT	=
COPT	=
AOPT	=

!else

LOPT	=/CO /LI /MAP
COPT	=-Zid -Fc -DDEBUG
AOPT	=-Zi -DDEBUG
ROPT	=-v -DDEBUG

!endif

CC	=cl -nologo -c -W3 -AMnw -GD2s -Ox -Zp $(COPT) -DWIN31 -DUSECOMM
LINK	=link /NOLOGO /NOE/NOD/AL:16/ONERROR:NOEXE $(LOPT)
ASM	=masm -t -W2 -Zd -Mx -D?MEDIUM -D?QUIET $(AOPT)
RC	=rc $(ROPT)


.c.obj:
	$(CC) $*.c

.rc.res:
	$(RC) -r -v -z $*.rc

#
#  Explicit Rules
#

goal: $(GOALS)

$(NAME).$(EXT) $(NAME).map: $(OBJS) $*.res $*.def
	$(LINK) @<<
	$(OBJS),
	$*.$(EXT),
	$*.map,
	$(LIBS),
	$*.def
<<
	$(RC) -31 $*.res $*.$(EXT)

$(NAME).sym:	$$(@R).map
	mapsym $*.map


#
#  Dependencies
#
$(NAME).res: $*.rc $*.h cnfgdlg.dlg cnfgdlg.h

$(NAME).obj: $*.c mcivisca.h
        $(CC) -NT CONFIG_TEXT $*.c

mcidelay.obj: $*.c mcivisca.h viscadef.h viscamsg.h
        $(CC) -NT CONFIG_TEXT $*.c

viscamsg.obj: $*.c viscadef.h
        $(CC)  -NT CONFIG_TEXT $*.c

commtask.obj: $*.c viscadef.h mcivisca.h
        $(CC) -NT CONFIG_TEXT $*.c

viscacom.obj: $*.c mcivisca.h viscadef.h
        $(CC) -NT TEXT $*.c

mcicmds.obj: $*.c mcivisca.h viscadef.h viscamsg.h
        $(CC) -NT TEXT $*.c

libinitv.obj: $*.asm
        $(ASM) -DSEGNAME=_TEXT $(@B).asm,$@;

#
#  Clean up
#

clean:
            -@del *.obj
            -@del *.cod
            -@del $(NAME).$(EXT)
            -@del $(NAME).res
            -@del $(NAME).map
            -@del $(NAME).sym

copy:
	copy $(NAME).drv ..\..\bin
	copy $(NAME).sym ..\..\bin
