# Windows 2.1 Sample Keyboard Driver Makefile:
#
# Requires MASM 5.10 or above.
#


toascii.obj:    ..\common\toascii.asm  ..\common\keyboard.inc            \
                ..\common\vkoem.inc ..\common\vkwin.inc ..\common\olikbd.inc
 masm -DOPTALL -DVKFUN -DDEAD -I..\common -z-t-b63 ..\common\toascii;

xlatno.obj:     ..\common\xlat.asm xlatno.inc
 masm -DOPTALL -DVKFUN -DNOxlat -I..\common -z-t-b63 ..\common\xlat,xlatno.obj;


#### assemble national 83-key tables
# all but US have dead key table data.
# The definitions '-D_Snnn' define the space allowed for patches to the
# keyboard translation tables, determined by the sizes of the xxn.wk2
# binary files. See the ifdef's in KPAD.INC.  If MAXSIZE must increase,
# delete the dataxx.obj file and change the value in this makefile.

datada.obj:     da1.asm ..\common\kpad.inc ..\common\keyboard.inc \
                ..\common\olikbd.inc ..\common\vkwin.inc ..\common\vkoem.inc
 masm -DOPTALL -DVKFUN -DS_800 -DDEAD -DINDRIVER -I..\common -z-t-b63 da1.asm,datada;

#### assemble national versions of INIT.ASM (with patch tables)

# Denmark
initda.obj:     ..\common\init.asm ..\common\keyboard.inc ..\common\olikbd.inc \
                patch.inc oem1x.inc oem4x.inc
        masm -DOPTALL -DVKFUN -DX1X2 -I..\common -z-t-b63 ..\common\init,initda;

#### link national versions ####

#### Denmark ####

kbdda.drv:      kbdda.def initda.obj datada.obj xlatno.obj toascii.obj \
                ..\common\datacom.obj ..\common\date.obj \
                ..\common\enable.obj ..\common\setspeed.obj
           copy ..\common\*.obj
           link4 @kbdda.lnk
