#* MAKEFILE                                                                *#

#* FILE-DESCRIPTION:                                                       *#
#*                                                                         *#
#*  Handy samples makefile.
#*                                                                         *#
#*  Options:                                                               *#
#*                                                                         *#
#*      PLATFORM:                                                          *#
#*          INTEL       Window NT Intel platform.                          *#
#*                                                                         *#
#*      DEBUG:                                                             *#
#*          1                                                              *#
#*          0 or not defined                                               *#
#*                                                                         *#
!ifndef DEBUG
DEBUG=1
!endif

!if "$(PLATFORM)"=="INTEL"
TARGET=Win32
!else
!ERROR $(PLATFORM) is not supported
TARGET=None
!endif

!if "$(TARGET)"!="None"

!if "$(DEBUG)"=="1"
all:
   nmake -f Generic.mak CFG="Generic - $(TARGET) Debug"

!else

all:
   nmake -f Generic.mak CFG="Generic - $(TARGET) Release"
!endif
!endif

