#   Windows Low Resolution Resource build file for CGA Displays
#

color.obj:      color.asm
    masm -z-t-Ml-b63 color;

blkwhite.obj:   blkwhite.asm
    masm -z-t-Ml-b63 blkwhite;

config.obj:	config.asm
    masm -z-t-b63 config;

cconfig.bin:    config.obj color.obj
    link config color.obj,cconfig;
    exe2bin cconfig
    erase cconfig.exe

bconfig.bin:    config.obj blkwhite.obj
    link config blkwhite.obj,bconfig;
    exe2bin bconfig
    erase bconfig.exe

fonts.obj:	fonts.asm
    masm -z-t-b63 fonts;

fonts.bin:	fonts.obj
    link fonts;
    exe2bin fonts
    erase fonts.exe

# First build the color resource. This resource is not used by any of the
# sample drivers in the kit but is built for color screens with similar
# aspect ratios as the CGA.  The monochrome resource is then built (CGA.RES)
# which is used by the sample CGA driver in the kit.

colores.res:    cga.rc       cconfig.bin                          \
		normal.cur   ibeam.cur	  wait.cur    cross.cur   \
		up.cur	     size.cur	  icon.cur    sample.ico  \
		hand.ico     ques.ico	  bang.ico    note.ico	  \
		right.bmp    left.bmp	  up.bmp      down.bmp	  \
		check.bmp    btsize.bmp   size.bmp    close.bmp   \
		button.bmp   btncorn.bmp  fonts.bin   lozoom.bmp  \
		sizenwse.cur sizenesw.cur sizewe.cur  sizens.cur  \
		lored.bmp
    copy cconfig.bin config.bin
    rc -r cga.rc
    copy cga.res colores.res
    erase config.bin
    erase cga.res

cga.res:        cga.rc       bconfig.bin                          \
		normal.cur   ibeam.cur	  wait.cur    cross.cur   \
		up.cur	     size.cur	  icon.cur    sample.ico  \
		hand.ico     ques.ico	  bang.ico    note.ico	  \
		right.bmp    left.bmp	  up.bmp      down.bmp	  \
		check.bmp    btsize.bmp   size.bmp    close.bmp   \
		button.bmp   btncorn.bmp  fonts.bin   lozoom.bmp  \
		sizenwse.cur sizenesw.cur sizewe.cur  sizens.cur  \
		lored.bmp
    copy bconfig.bin config.bin
    rc -r cga.rc
    erase config.bin
