#* MAKEFILE                                                                *#

#* FILE-DESCRIPTION:                                                       *#
#*                                                                         *#
#*  MultiPad sample makefile.
#*                                                                         *#
#*  Options:                                                               *#
#*                                                                         *#
#*      PLATFORM:                                                          *#
#*          INTEL       Window NT Intel platform.                          *#
#*          M68K        WLM / 68K platform.                                *#
#*          MPPC        WLM / Power PC platform.                           *#
#*                                                                         *#
#*      MACNAME:                                                           *#
#*          name of remote location (ex. MacHd:MacFolder)                  *#
#*          if defined the result will be downloaded (on M68K & MPPC only) *#
#*                                                                         *#
#*      DEBUG:                                                             *#
#*          1                                                              *#
#*          0 or not defined                                               *#
#*                                                                         *#
PROJ=MultiPad

!ifndef DEBUG
DEBUG=1
!endif

!if "$(PLATFORM)"=="INTEL"
TARGET=Win32
!else
!if "$(PLATFORM)"=="M68K"
TARGET=Macintosh
OUTDIR=Mac
!else
!if "$(PLATFORM)"=="MPPC"
TARGET=Power Macintosh
OUTDIR=PMac
!else
!ERROR $(PLATFORM) is not supported
TARGET=None
!endif
!endif
!endif

!if "$(TARGET)"!="None"

!if "$(DEBUG)"=="1"
OUTDIR=$(OUTDIR)Dbg
all:
   nmake -f $(PROJ).mak CFG="$(PROJ) - $(TARGET) Debug"

!else
OUTDIR=$(OUTDIR)Rel
all:
   nmake -f $(PROJ).mak CFG="$(PROJ) - $(TARGET) Release"
!endif

!if "$(PLATFORM)"=="M68K" || "$(PLATFORM)"=="MPPC"
!if "$(MACNAME)" != ""
    MFILE copy -v $(OUTDIR)\$(PROJ).exe ":$(MACNAME):$(PROJ)"
!endif
!endif

!endif