all:    cga             ega             vga             8514

cga:
        cd cga
        $(MAKE) 
        cd ..

ega:
        cd ega
        $(MAKE)
        cd ..

vga:
        cd vga
        $(MAKE)
        cd ..

8514:
        cd 8514
        $(MAKE)
        cd ..
