@echo *
@echo ***Batch File to build examples with Visual C++
@echo *
cd ddex1
nmake %1 debug retail
cd ..\ddex2
nmake %1 debug retail
cd ..\ddex3
nmake %1 debug retail
cd ..\ddex4
nmake %1 debug retail
cd ..\ddex5
nmake %1 debug retail
cd ..\donut
nmake %1 debug retail
cd ..\fastfile
nmake %1 debug retail
cd ..\palette
nmake %1 debug retail
cd ..\dsshow
nmake %1 debug retail
cd ..\dsstream
nmake %1 debug retail
cd ..\mid2strm
nmake %1 debug retail 
cd ..\mstream
nmake %1 debug retail 
cd ..\dptest
nmake %1 debug retail
cd ..\duel
nmake %1 debug retail
cd ..\wormhole
nmake %1 debug retail
cd ..\stretch
nmake %1 debug retail
cd ..\memtime
nmake %1 debug retail
cd ..\dxview
nmake %1 debug retail
cd ..\flipcube
nmake %1 debug retail
cd ..\foxbear
nmake %1 debug retail
cd ..\flip2d
nmake %1 debug retail
cd ..\cgutil
nmake %1 debug retail
cd ..\iklowns
nmake %1 debug retail
cd ..\setup
nmake %1 debug retail
cd ..\egg
nmake %1 debug retail
cd ..\faces
nmake %1 debug retail
cd ..\fly
nmake %1 debug retail
cd ..\globe
nmake %1 debug retail
cd ..\hier1
nmake %1 debug retail
cd ..\hier2
nmake %1 debug retail
cd ..\oct1
nmake %1 debug retail
cd ..\oct2
nmake %1 debug retail
cd ..\quat
nmake %1 debug retail
cd ..\sphere
nmake %1 debug retail
cd ..\tex1
nmake %1 debug retail
cd ..\tex3
nmake %1 debug retail
cd ..\tex4
nmake %1 debug retail
cd ..\tex5
nmake %1 debug retail
cd ..\trans
nmake %1 debug retail
cd ..\triangle
nmake %1 debug retail
cd ..\tunnel
nmake %1 debug retail
cd ..\twist
nmake %1 debug retail
cd ..\viewer
nmake %1 debug retail
cd ..\uvis
nmake %1 debug retail
cd ..
