spooler.res:  spooler.rc spooler.ico
    rc -r spooler.rc

jcb.obj:   jcb.c
    cl -u -d -c -Asnw -Gsw -Oas -Zpe -PLM  jcb.c

spkey.obj:  spkey.c
    cl -u -d -c -Asnw -Gsw -Oas -Zpe -PLM  spkey.c

spooler.obj: spooler.c
    cl -u -d -c -Asnw -Gsw -Oas -Zpe -PLM  spooler.c

spinit.obj: spinit.c
    cl -u -d -c -Asnw -Gsw -Oas -Zpe -PLM  spinit.c

spport.obj:     spport.c
    cl -u -d -c -Asnw -Gsw -Oas -Zpe -PLM  spport.c

spoolaux.obj: spoolaux.asm
    masm -z-t-b63 spoolaux.asm;

spooler.exe: spooler.def spooler.obj jcb.obj spooler.res \
             spoolaux.obj spkey.obj spport.obj spooler.lnk spinit.obj
    link4 @spooler.lnk
    mapsym spooler
    rc spooler.res
