/*  Motion.c
    Motion Application
    Windows Version 1.01
    Copyright (c) Microsoft 1985        */

/***************************************************************************
**  This application is meant to be run when windows is running under a
**  debugger so that you can watch the messages generated by windows as it
**  moves code and data segments around and discards and reloads them.
**
**  There are four command that may be invoked either with the mouse or using
**  the function keys f1..f4.
**      f1  Call Nonres seg 1
**      f2  Call Nonres seg 2
**      f3  LocalAlloc(512)     does a allocation
**      f4  GlobalCompact(-1)   causes compaction of memory
**
**  This application also shows how to make libraries.
***************************************************************************/

#include "motion.h"

int  far PASCAL Lib1Proc(int);
int  far PASCAL Lib2Proc(int);

HBRUSH hbrWhite;
HANDLE hAccelTable;
HANDLE hInst;
FARPROC lpprocAbout;
char exename[ 128 ];
char szAppName[ 10 ];
char szLocalExpandFail[ 30 ];
char szAbout[ 10 ];
char szNRSeg1Msg[ 30 ];
char szNRSeg2Msg[ 30 ];

BOOL FAR PASCAL About( hDlg, message, wParam, lParam )
HWND hDlg;
unsigned message;
WORD wParam;
LONG lParam;
{
    if (message == WM_COMMAND) {
        EndDialog( hDlg, TRUE );
        return TRUE;
        }
    else if (message == WM_INITDIALOG)
        return TRUE;
    else return FALSE;
}

MotionCommand(hWnd, id, hWndCtl, codeCtl)
HWND hWnd;
int id;
HWND hWndCtl;
int codeCtl;
{
    switch (id) {
        case IDMNRCALL1:
            MotionNRSeg1(hWnd);
            break;

        case IDMNRCALL2:
            MotionNRSeg2(hWnd);
            break;

        case IDMLEXPAND:
            if (!LocalAlloc(0, 512))
                {
                MessageBeep(MB_OK | MB_ICONEXCLAMATION);
                MessageBox(hWnd, (LPSTR)szLocalExpandFail,
                                 (LPSTR)szAppName, MB_OK|MB_ICONEXCLAMATION);
                }
            Lib2Proc(3);
            break;

        case IDMGCOMPACT:
            GlobalCompact((LONG)-1);
            break;
        }
}

int PASCAL WinMain(hInstance, hPrevInstance, lpszCmdLine, cmdShow)
HANDLE hInstance, hPrevInstance;
LPSTR  lpszCmdLine;
int    cmdShow;
{
    MSG   msg;
    HWND  hWnd;
    HMENU hMenu;

    Lib1Proc(3);

    if (!hPrevInstance)
    {
        if (!MotionInit(hInstance))
            return FALSE;
    }
    else
    {
        GetInstanceData(hPrevInstance, (PSTR)&hbrWhite, sizeof(hbrWhite));
        GetInstanceData(hPrevInstance, (PSTR)&hAccelTable, sizeof(hAccelTable));
        GetInstanceData(hPrevInstance, (PSTR)szAppName, 10 );
        GetInstanceData(hPrevInstance, (PSTR)szLocalExpandFail, 30 );
        GetInstanceData(hPrevInstance, (PSTR)szAbout, 10 );
        GetInstanceData(hPrevInstance, (PSTR)szNRSeg1Msg, 30 );
        GetInstanceData(hPrevInstance, (PSTR)szNRSeg2Msg, 30 );
    }
    GetModuleFileName(hInstance, (LPSTR)exename, sizeof(exename));

    hWnd = CreateWindow((LPSTR)szAppName,
                        (LPSTR)exename,
                        WS_TILEDWINDOW,
                        0, 0, 0, 0,
                        (HWND)NULL,
                        (HMENU)NULL,
                        (HANDLE)hInstance,
                        (LPSTR)NULL
                       );

    ShowWindow(hWnd, cmdShow);
    UpdateWindow(hWnd);

    hInst = hInstance;
    lpprocAbout = MakeProcInstance( (FARPROC)About, hInstance);
    hMenu = GetSystemMenu(hWnd, FALSE);
    ChangeMenu(hMenu, 0, NULL, 999, MF_APPEND | MF_SEPARATOR);
    ChangeMenu(hMenu, 0, (LPSTR)szAbout, IDMABOUT, MF_APPEND | MF_STRING);

    while (GetMessage((LPMSG)&msg, NULL, 0, 0)) {
        if (TranslateAccelerator(hWnd, hAccelTable, (LPMSG)&msg) == 0) {
            TranslateMessage((LPMSG)&msg);
            DispatchMessage((LPMSG)&msg);
            }
        }
    exit(msg.wParam);
}

long FAR PASCAL MotionWndProc(hWnd, message, wParam, lParam)
HWND       hWnd;
unsigned   message;
WORD       wParam;
LONG       lParam;
{
    PAINTSTRUCT  ps;

    switch (message)
    {
        case WM_SYSCOMMAND:
            switch (wParam) {
                case IDMABOUT:
                    DialogBox(hInst, MAKEINTRESOURCE(ABOUTBOX), hWnd, lpprocAbout);
                    break;
                default:
                    return(DefWindowProc(hWnd, message, wParam, lParam));
                    break;
                }
            break;

        case WM_DESTROY:
            PostQuitMessage(0);
            break;

        case WM_COMMAND:
            MotionCommand(hWnd, wParam, (HWND)LOWORD(lParam),
                          HIWORD(lParam));
            break;

        default:
            return(DefWindowProc(hWnd, message, wParam, lParam));
            break;
    }

    return(0L);
}
