DIRLIST =   patron

all: $(DIRLIST)

$(DIRLIST):
        cd $@
        @echo *** ole\inole2\chap09\$@ *** >>$(MSTOOLS)\samples\chap09.tmp
        @nmake -a -i -nologo >>$(MSTOOLS)\samples\chap09.tmp
        cd ..

