#
# Windows/286 Version 2.10 MSDOSD.EXE Makefile.

#
#  First, compile the .C files using the C Compiler supplied in this
#  OEM Kit.  Also, make sure to use the .H files supplied with the kit.
#

format.obj: format.c msdosd.h
        cl -d -c -Asnw -Gsw -Oas -Zpe format.c

sys.obj: sys.c msdosd.h
        cl -d -c -Asnw -Gsw -Oas -Zpe sys.c

#
#  Next, compile the .ASM files using MASM v5.10 or greater:
#

disk.obj: disk.asm disk.inc
        masm -z-t-b63 disk;

file.obj: file.asm
        masm -z-t-b63 file;

adjust.obj: adjust.asm
        masm -z-t-b63 adjust;

msdosd.exe:  msdosd.def format.obj sys.obj disk.obj file.obj adjust.obj
    link4 @msdosd.lnk
    mapsym msdosd
