//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by cppdemo.rc
//
#define IDS_MAIN                        1
#define IDS_NOMEMORY                    2
#define IDS_SQLDEF                      3
#define IDS_SZNULL                      4
#define IDS_MSGFMT                      17
#define IDS_NODATAFOUND                 21
#define IDS_STILLEXECUTING              22
#define IDS_ABOUT						23
#define IDS_ASLMERROR					24
#define IDR_MENU                        101
#define ABOUTBOX                        102
#define SQLBOX                          104
#define CONFIRMBOX                      105
#define OKBOX                           106
#define IDI_ICON                        200
#define IDC_STATUS1                     1008
#define IDC_EDIT1                       1009
#define ID_FILE_EXIT                    40001
#define ID_HELP_ABOUT                   40002
#define ID_ENV_OPEN                     40004
#define ID_ENV_CLOSE                    40005
#define ID_ENV_ADD                      40006
#define ID_SQL_EXEC                     40007
#define ID_SQL_FETCH                    40008
#define ID_HELP_HELP                    40009
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         40010
#define _APS_NEXT_CONTROL_VALUE         1010
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
