/*----------------------------------------------------------------------------

	HEADERS.H - Shared headers for the ODBC SDK 2.0 C++ demo application
	
	This code is furnished on an as-is basis as part of the ODBC SDK and is
	intended for example purposes only.

	
----------------------------------------------------------------------------*/

#define		STRICT

#include	<windows.h>
#include	<windowsx.h>

#include	"ctl3d.h"

#include	<assert.h>
#include	<string.h>
#include	<sql.h>

#include    "codbc.h"
#include	<odbcinst.h>

#pragma		hdrstop
