@ECHO OFF
IF ERRORLEVEL 11 GOTO OutOfRange
IF ERRORLEVEL 10 GOTO L10
IF ERRORLEVEL  9 GOTO L9
IF ERRORLEVEL  8 GOTO L8
IF ERRORLEVEL  7 GOTO L7
IF ERRORLEVEL  6 GOTO L6
IF ERRORLEVEL  5 GOTO L5
IF ERRORLEVEL  4 GOTO L4
IF ERRORLEVEL  3 GOTO L3
IF ERRORLEVEL  2 GOTO L2
IF ERRORLEVEL  1 GOTO L1
:L0
ECHO 0 >RETVALUE.TMP
GOTO Done
:L1
ECHO 1 >RETVALUE.TMP
GOTO Done
:L2
ECHO 2 >RETVALUE.TMP
GOTO Done
:L3
ECHO 3 >RETVALUE.TMP
GOTO Done
:L4
ECHO 4 >RETVALUE.TMP
GOTO Done
:L5
ECHO 5 >RETVALUE.TMP
GOTO Done
:L6
ECHO 6 >RETVALUE.TMP
GOTO Done
:L7
ECHO 7 >RETVALUE.TMP
GOTO Done
:L8
ECHO 8 >RETVALUE.TMP
GOTO Done
:L9
ECHO 9 >RETVALUE.TMP
GOTO Done
:L10
ECHO 10 >RETVALUE.TMP
GOTO Done
:OutOfRange
ECHO 32767 >RETVALUE.TMP
:Done

