DIRLIST =   cosmo

all: $(DIRLIST)

$(DIRLIST):
        cd $@
        @echo *** ole\inole2\chap10\$@ *** >>$(MSTOOLS)\samples\chap10.tmp
        @nmake -a -i -nologo >>$(MSTOOLS)\samples\chap10.tmp
        cd ..

