# Microsoft Windows SYSTEM Makefile

system.obj: system.asm system.inc
        masm -z-t-b63 system;

timer.obj: timer.asm system.inc
        masm -z-t-b63 timer;

system.drv: system.def system.lnk \
            system.obj timer.obj
    link4 @system.lnk
    mapsym system
