bin2hex.obj:   bin2hex.asm
        masm -DEGACOLOR -z-t-b63 bin2hex;

block.obj:   block.asm
        masm -DEGACOLOR -z-t-b63 block;

edgrab.obj:   edgrab.asm
        masm -DEGACOLOR -z-t-b63 edgrab;

entry.obj:   entry.asm
        masm -DEGACOLOR -z-t-b63 entry;

getinfo.obj:   getinfo.asm
        masm -DEGACOLOR -z-t-b63 getinfo;

grabbits.obj:   grabbits.asm
        masm -DEGACOLOR -z-t-b63 grabbits;

grabscr.obj:   grabscr.asm
        masm -DEGACOLOR -z-t-b63 grabscr;

inout.obj:   inout.asm
        masm -DEGACOLOR -z-t-b63 inout;

inquire.obj:   inquire.asm
        masm -DEGACOLOR -z-t-b63 inquire;

oem.obj:   oem.asm
        masm -DEGACOLOR -z-t-b63 oem;

prompt.obj:   prompt.asm
        masm -DEGACOLOR -z-t-b63 prompt;

rcolor.obj:   rcolor.asm
        masm -DEGACOLOR -z-t-b63 rcolor;

bepaint.obj:           bepaint.asm
        masm -DEGACOLOR -z-t-b63 bepaint;

blockdev.obj:           blockdev.asm
        masm -DEGACOLOR -z-t-b63 blockdev;

devinit.obj:           devinit.asm
        masm -DEGACOLOR -z-t-b63 devinit;

edsave.obj:           edsave.asm
        masm -DEGACOLOR -z-t-b63 edsave;

egamisc.obj:           egamisc.asm
        masm -DEGACOLOR -z-t-b63 egamisc;

gsmode.obj:           gsmode.asm
        masm -DEGACOLOR -z-t-b63 gsmode;

setswap.obj:           setswap.asm
        masm -DEGACOLOR -z-t-b63 setswap;

srfontf.obj:           srfontf.asm
        masm -DEGACOLOR -z-t-b63 srfontf;

#
# Note:  Due to an error in build procedure, the retail Windows/286 was built
# without the -DEGACOLOR flag.  Therefore, for the sake of consistency, we
# build the same way in this kit.  However, it is MUCH more correct to
# build WITH the -DEGACOLOR flag.  Therefore, when you build your own grabbers,
# you should add this flag back into the command line.
#

srscr.obj:           srscr.asm
        masm -z-t-b63 srscr;

srscrf.obj:           srscrf.asm
        masm -DEGACOLOR -z-t-b63 srscrf;

egacolor.obj:           egacolor.asm
        masm -DEGACOLOR -z-t-b63 egacolor;

egacolor.exe:		egacolor.obj	  \
                        vga-ega.lnk       \
		        bepaint.obj	  \
		        blockdev.obj	  \
		        devinit.obj	  \
		        edsave.obj	  \
		        egamisc.obj	  \
		        gsmode.obj	  \
		        setswap.obj	  \
		        srfontf.obj	  \
		        srscr.obj	  \
		        srscrf.obj	  \
		        bin2hex.obj	  \
		        block.obj	  \
		        edgrab.obj	  \
		        entry.obj	  \
		        getinfo.obj	  \
		        grabbits.obj	  \
		        grabscr.obj	  \
		        inout.obj	  \
		        inquire.obj	  \
		        oem.obj 	  \
		        prompt.obj	  \
                        rcolor.obj
        link4 @vga-ega.lnk

egahires.grb:           egahires.exe
        exe2bin egahires.exe egahires.grb
