#===========================================================================;
#
#   AVIEdit -- AVI Editor sample application
#
#
#---------------------------------------------------------------------------;
#
#   to make a NON-DEBUG build, type the following line:
#       nmake DEBUG=NO
#   just typing 'nmake' will build a DEBUG build
#
#
#===========================================================================;
#############################################################################
#
#   THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
#   KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
#   PURPOSE.
#
#   Copyright (c) 1992, 1993  Microsoft Corporation.  All Rights Reserved.
#
#############################################################################


#---------------------------------------------------------------------------;
# DEBUG information
#---------------------------------------------------------------------------;
!if "$(DEBUG)" == "NO"
COPT = 
MOPT = 
LOPT =
DEF  =
!else
COPT = -Zi -Fc
MOPT = -Zi -L
LOPT = /CO
DEF  = -DDEBUG
!endif


#-------------------------------------------------------------------------;
# Build Defaults
#-------------------------------------------------------------------------;
CC   = cl -c -nologo -AM -Zp -Ox -G2s -GA -W3 -DWINVER=0x030A $(DEF) $(COPT)
RC   = rc $(DEF) 
ASM  = masm -Mx  -t $(MOPT) $(DEF)
LINK = link $(LOPT)/NOD/NOE/MAP/NOPACKC/AL:16/ONERROR:NOEXE



#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;
#
#   Goals and objects
#
#
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;

NAME	= aviedit
EXT	= exe
GOALS   = $(NAME).$(EXT)

OBJS	=$(NAME).obj audio.obj muldived.obj

LIBS	= libw mlibcew commdlg mmsystem vfw shell


#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;
#
#   Build rules
#
#
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;
.cpp.obj:
	$(CC) $*.cpp

.c.obj:
	$(CC) $*.c

.asm.obj:
	$(ASM) $*;

.rc.res:
	$(RC) -r $*.rc


goal: $(GOALS)
        @echo ***** Finished building $(NAME).$(EXT) *****


$(NAME).$(EXT): $(OBJS) $(NAME).res $(NAME).def
	$(LINK) @<<
$(OBJS),
$(NAME).$(EXT),
$(NAME),
$(LIBS),
$(NAME).def
<<
        mapsym $(NAME).map
        $(RC) -t -31 $(NAME).res $(NAME).$(EXT)
 
$(NAME).obj: $$(@B).c $(NAME).h
	$(CC) -NT _TEXT -Fo$@ $(@B).c

audio.obj: $$(@B).c
	$(CC) -NT _TEXT -Fo$@ $(@B).c

muldived.obj: $$(@B).c
	$(CC) -NT _TEXT -Fo$@ $(@B).c
 

clean:
	del $(NAME).$(EXT)
	del *.res
	del *.obj
	del *.map
	del *.sym
	del *.cod
	del *.pdb
	del *.lst

copy:
	copy $(NAME).$(EXT) ..\..\bin
	copy $(NAME).sym ..\..\bin
