bin2hex.obj:   bin2hex.asm
        masm -z-t-b63 bin2hex;

block.obj:   block.asm
        masm -z-t-b63 block;

edgrab.obj:   edgrab.asm
        masm -z-t-b63 edgrab;

entry.obj:   entry.asm
        masm -z-t-b63 entry;

getinfo.obj:   getinfo.asm
        masm -z-t-b63 getinfo;

grabbits.obj:   grabbits.asm
        masm -z-t-b63 grabbits;

grabscr.obj:   grabscr.asm
        masm -z-t-b63 grabscr;

inout.obj:   inout.asm
        masm -z-t-b63 inout;

inquire.obj:   inquire.asm
        masm -z-t-b63 inquire;

oem.obj:   oem.asm
        masm -z-t-b63 oem;

prompt.obj:   prompt.asm
        masm -z-t-b63 prompt;

rcolor.obj:   rcolor.asm
        masm -z-t-b63 rcolor;

bepaint.obj:           bepaint.asm
        masm -DCGA -z-t-b63 bepaint;

blockdev.obj:           blockdev.asm
        masm -DCGA -z-t-b63 blockdev;

edsave.obj:           edsave.asm
        masm -DCGA -z-t-b63 edsave;

gsmode.obj:           gsmode.asm
        masm -DCGA -z-t-b63 gsmode;

setswap.obj:           setswap.asm
        masm -DCGA -z-t-b63 setswap;

srscr.obj:           srscr.asm
        masm -DCGA -z-t-b63 srscr;

cga.obj:                cga.asm
        masm -DCGA -z-t-b63 cga;

cga.exe:		cga.obj 	  \
			cga.lnk 	  \
		        bepaint.obj	  \
		        blockdev.obj	  \
		        edsave.obj	  \
		        gsmode.obj	  \
		        setswap.obj	  \
		        srscr.obj	  \
		        block.obj	  \
		        edgrab.obj	  \
		        entry.obj	  \
		        getinfo.obj	  \
		        grabbits.obj	  \
		        grabscr.obj	  \
		        inout.obj	  \
		        inquire.obj	  \
		        oem.obj 	  \
		        prompt.obj	  \
                        rcolor.obj
        link4 @cga.lnk

cga.grb:                cga.exe
        exe2bin cga.exe cga.grb

