all: Win32 FrmWork OLE OpenGL RPC SDKTools MM MAPI

win32:
!IF EXIST (win32)
		cd win32
		@nmake -a -i -nologo
		cd ..
		@if exist samples.log copy samples.log+*.tmp samples.log >nul
		@if not exist samples.log copy *.tmp samples.log >nul
		@del *.tmp >nul
!ENDIF

frmwork:
!IF EXIST (frmwork)
		cd frmwork
		@nmake -a -i -nologo
		cd ..
		@if exist samples.log copy samples.log+*.tmp samples.log >nul
		@if not exist samples.log copy *.tmp samples.log >nul
		@del *.tmp >nul
!ENDIF

ole:
!IF EXIST (ole)
		cd ole
		@nmake -a -i -nologo
		cd ..
		@if exist samples.log copy samples.log+*.tmp samples.log >nul
		@if not exist samples.log copy *.tmp samples.log >nul
		@del *.tmp >nul
!ENDIF

opengl:
!IF EXIST (opengl)
		cd opengl
		@nmake -a -i -nologo
		cd ..
		@if exist samples.log copy samples.log+*.tmp samples.log >nul
		@if not exist samples.log copy *.tmp samples.log >nul
		@del *.tmp >nul
!ENDIF

rpc:
!IF EXIST (rpc)
		cd rpc
		@nmake -a -i -nologo
		cd ..
		@if exist samples.log copy samples.log+*.tmp samples.log >nul
		@if not exist samples.log copy *.tmp samples.log >nul
		@del *.tmp >nul
!ENDIF

sdktools:
!IF EXIST (sdktools)
		cd sdktools
		@nmake -a -i -nologo
		cd ..
		@if exist samples.log copy samples.log+*.tmp samples.log >nul
		@if not exist samples.log copy *.tmp samples.log >nul
		@del *.tmp >nul
!ENDIF

mm:
!IF EXIST (mm)
		cd mm
		@nmake -a -i -nologo
		cd ..
		@if exist samples.log copy samples.log+*.tmp samples.log >nul
		@if not exist samples.log copy *.tmp samples.log >nul
		@del *.tmp >nul
!ENDIF

mapi:
!IF EXIST (mapi)
		cd mapi
		@nmake -a -i -nologo
		cd ..
		@if exist samples.log copy samples.log+*.tmp samples.log >nul
		@if not exist samples.log copy *.tmp samples.log >nul
		@del *.tmp >nul
!ENDIF
