#############################################################################
#
#   THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
#   KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
#   PURPOSE.
#
#   Copyright (c) 1992, 1993  Microsoft Corporation.  All Rights Reserved.
#
#############################################################################
#
#   MAKEFILE
#
#   constructs the AVICap window test program
#
#   to build a debug version:
#       NMAKE
#   to build a non debug version:
#       NMAKE DEBUG=NO
#
############################################################################

NAME     = CapTest
DEFFILE  = $(NAME).def

!if "$(DEBUG)" == "NO"

DEF = 
CC  = cl -c -nologo -W3 -Alnw -Gsw -Zip -Od $(DEF)
ASM = masm -Mx -t -DSEGNAME=CAPTEST_TEXT -D?QUIET $(DEF)
LINK= link /NOE/MAP/NOD/AL:16/NOPACKC/ONERROR:NOEXE
LIBMAN = lib /NOE

!else

DEF   = -DDEBUG 
MASMOPT = -Zi -DDEBUG
CC  = cl -c -nologo -W3 -Alnw -Gsw -Zip -Fc $(DEF)
ASM = masm -Mx -t -D?QUIET -DSEGNAME=CAPTEST_TEXT  $(MASMOPT)
LINK= link /NOE/CO/LI/MAP/NOD/AL:16/NOPACKC/ONERROR:NOEXE
LIBMAN = lib /NOE

!endif


OBJ1    = $(NAME).obj dialogs.obj

OBJ    = $(OBJ1)
LIBS = libw mlibcew commdlg vfw msacm mmsystem

.c.obj:
	$(CC) $*.c

###################### goal ######################

goal:  $(NAME).exe


##################################################

$(NAME).exe $(NAME).map: $(OBJ) $(NAME).res $(DEFFILE)
   $(LINK) @<<
	$(OBJ),
	$(NAME),
   $(NAME),
	$(LIBS),
	$(NAME).def
<<
	rc -31 $(NAME).res
!if "$(DEBUG)" != "NO"
	cvpack -p $(NAME).exe
!endif
   mapsym $(NAME).map


$(NAME).res: $(NAME).rc $(NAME).ico 
	rc -r $(DEF) $(NAME).rc

$(NAME).rc:  $(NAME).dlg $(NAME).h


##################### clean ######################

clean:
	del $(NAME).exe
	del *.obj
	del *.res
	del *.map
	del *.sym

##################### copy #######################
copy:
	copy $(NAME).exe ..\..\bin
	copy $(NAME).sym ..\..\bin


##################### depend #####################

$(NAME).obj: $(NAME).c $(NAME).h 
$(NAME).c: $(NAME).h 
$dialogs.obj: dialogs.c $(NAME).h
dialogs.c: $(NAME).h
$(NAME).h: dialogs.h
$(NAME).res: $(NAME).rc
$(NAME).rc: $(NAME).dlg $(NAME).ico dialogs.h

# END Dependencies 
