@ECHO OFF
SET XHOST=.
COPY %XHOST%\%PROCESSOR_ARCHITECTURE%\*.SYS  %WINDIR%\SYSTEM32\DRIVERS\ >NUL 2>NUL
COPY %XHOST%\%PROCESSOR_ARCHITECTURE%\*.EXE  %WINDIR%\ >NUL 2>NUL
%XHOST%\%PROCESSOR_ARCHITECTURE%\REGINI      %XHOST%\HALTEST.INI        >NUL 2>NUL
@ECHO HAL TEST DRIVER INSTALLED......
@ECHO Please Reboot the Computer Now and run %WINDIR%\HALTEST.EXE
@ECHO haltest.log will be written where .exe is run from
@ECHO IMPORTANT: A Debugger will give additional info.
