# Windows 2.1 Sample Keyboard Driver Makefile:
#
# Requires MASM 5.10 or above.
#


toascii.obj:    ..\common\toascii.asm  ..\common\keyboard.inc            \
                ..\common\vkoem.inc ..\common\vkwin.inc ..\common\olikbd.inc
 masm -DOPTALL -DVKFUN -DNODEAD -I..\common -z-t-b63 ..\common\toascii;

xlatus.obj:     ..\common\xlat.asm xlatus.inc
 masm -DOPTALL -DVKFUN -I..\common -z-t-b63 ..\common\xlat,xlatus.obj;


#### assemble national 83-key tables
# all but US have dead key table data.
# The definitions '-D_Snnn' define the space allowed for patches to the
# keyboard translation tables, determined by the sizes of the xxn.wk2
# binary files. See the ifdef's in KPAD.INC.  If MAXSIZE must increase,
# delete the dataxx.obj file and change the value in this makefile.

datauk.obj:     uk1.asm ..\common\kpad.inc ..\common\keyboard.inc \
                ..\common\olikbd.inc ..\common\vkwin.inc ..\common\vkoem.inc
 masm -DOPTALL -DVKFUN -DS_670 -DNODEAD -DINDRIVER -I..\common -z-t-b63 uk1.asm,datauk;

#### assemble national versions of INIT.ASM (with patch tables)

# United Kingdom English
inituk.obj:     ..\common\init.asm ..\common\keyboard.inc ..\common\olikbd.inc \
                patch.inc oem1x.inc oem4x.inc
        masm -DOPTALL -DVKFUN -DX1X2 -I..\common -z-t-b63 ..\common\init,inituk;

#### link national versions ####

#### United Kingdom English ####

kbduk.drv:      kbduk.def inituk.obj datauk.obj xlatus.obj toascii.obj \
                ..\common\datacom.obj ..\common\date.obj \
                ..\common\enable.obj ..\common\setspeed.obj
           copy ..\common\*.obj
           link4 @kbduk.lnk
