DIRLIST =   patron

all: $(DIRLIST)

$(DIRLIST):
        cd $@
        @echo *** ole\inole2\chap15\$@ *** >>$(MSTOOLS)\samples\chap15.tmp
        @nmake -a -i -nologo >>$(MSTOOLS)\samples\chap15.tmp
        cd ..

