#
# environment variables:
#
# VERSION:  DEV or PRODUCT
# TARGETOS: OS2 or DOS
# LISTINGS: YES or NO (default)
#

#
# compilation flags:
#
MFLAGS = /t /D$(TARGETOS)

!IF "$(VERSION)" == "DEV"
MFLAGS = $(MFLAGS) /DDEV
!ENDIF
#
# linker options
#
LFLAGS = /NOI

!IF "$(LISTINGS)" == "YES"
ASM = masm /c $(*B) $(MFLAGS),$*,$[p,$*]LIST\$[r,$*]/n,nul;
!ELSE
ASM = masm $(*B) $(MFLAGS),$*,nul,nul;
!ENDIF

#
# general equates
#
OBJ1 = $(TARGETOS)\data.obj $(TARGETOS)\msg.obj $(TARGETOS)\init.obj 
OBJ2 = $(TARGETOS)\bind.obj $(TARGETOS)\util.obj $(TARGETOS)\req.obj
OBJ3 = $(TARGETOS)\recv.obj $(TARGETOS)\xmit.obj $(TARGETOS)\intr.obj
OBJS = $(OBJ1) $(OBJ2) $(OBJ3)
INCS = includes.mac equ.mac struc.mac adapter.mac macros.mac segdef.mac

$(TARGETOS)\$(VERSION)\ibmtok.$(TARGETOS): $(OBJS)
    @echo $(OBJ1) >  linkfile.$(TARGETOS) +
    @echo $(OBJ2) >> linkfile.$(TARGETOS) +
    @echo $(OBJ3) >> linkfile.$(TARGETOS)
	@echo $(TARGETOS)\$(VERSION)\ibmtok.$(TARGETOS) >> linkfile.$(TARGETOS)
!IF "$(TARGETOS)" == "OS2"
    @echo $(TARGETOS)\$(VERSION)\ibmtok.map/M >> linkfile.$(TARGETOS)
    @echo doscalls >> linkfile.$(TARGETOS)
    @echo ibmtok.def >> linkfile.$(TARGETOS)
!ELSE
    @echo $(TARGETOS)\$(VERSION)\ibmtok.map/M; >> linkfile.$(TARGETOS)
!ENDIF
    link $(LFLAGS) @linkfile.$(TARGETOS)
    @del linkfile.$(TARGETOS)
!IF "$(TARGETOS)" == "OS2"
    mapsym $*
    @copy $(*B).sym $*.sym >nul
    @del $(*B).sym >nul
!ELSE
    @copy $@ $(@B).exe >nul
	exe2com $(@B).exe
	@del $(@B).exe >nul
	@copy $(@B).com $@ >nul
	@del $(@B).com >nul
!ENDIF

#
# MAC Object files dependencies
#
$(TARGETOS)\data.obj: data.asm $(INCS)
    $(ASM)

$(TARGETOS)\msg.obj: msg.asm $(INCS)
    $(ASM)

$(TARGETOS)\init.obj: init.asm $(INCS)
    $(ASM)

$(TARGETOS)\bind.obj: bind.asm $(INCS)
    $(ASM)

$(TARGETOS)\util.obj: util.asm $(INCS)
    $(ASM)

$(TARGETOS)\req.obj: req.asm $(INCS)
    $(ASM)

$(TARGETOS)\recv.obj: recv.asm $(INCS)
    $(ASM)

$(TARGETOS)\xmit.obj: xmit.asm $(INCS)
    $(ASM)

$(TARGETOS)\intr.obj: intr.asm $(INCS)
    $(ASM)

.INIT:
!IF "$(TARGETOS)" == "OS2" && "$(TARGETOS)" == "DOS"
!ELSE
        @echo Invalid TargetOS "$(TARGETOS)".  Should be DOS or OS2.
        @%exit 1
!ENDIF
!IF "$(VERSION)" == "DEV"  && "$(VERSION)" == "PRODUCT"
!ELSE
        @echo Invalid Version "$(VERSION)".  Should be PRODUCT or DEV.
        @%exit 1
!ENDIF
    @echo .
    @echo building $(TARGETOS) IBM Token Ring Driver, $(VERSION) version
    @echo .
