bin2hex.obj:   bin2hex.asm
        masm -z-t-b63 bin2hex;

block.obj:   block.asm
        masm -z-t-b63 block;

edgrab.obj:   edgrab.asm
        masm -z-t-b63 edgrab;

entry.obj:   entry.asm
        masm -z-t-b63 entry;

getinfo.obj:   getinfo.asm
        masm -z-t-b63 getinfo;

grabbits.obj:   grabbits.asm
        masm -z-t-b63 grabbits;

grabscr.obj:   grabscr.asm
        masm -z-t-b63 grabscr;

inout.obj:   inout.asm
        masm -z-t-b63 inout;

inquire.obj:   inquire.asm
        masm -z-t-b63 inquire;

oem.obj:   oem.asm
        masm -z-t-b63 oem;

prompt.obj:   prompt.asm
        masm -z-t-b63 prompt;

rcolor.obj:   rcolor.asm
        masm -z-t-b63 rcolor;

bepaint.obj:           bepaint.asm
        masm -DEGAMONO -z-t-b63 bepaint;

blockdev.obj:           blockdev.asm
        masm -DEGAMONO -z-t-b63 blockdev;

devinit.obj:           devinit.asm
        masm -DEGAMONO -z-t-b63 devinit;

edsave.obj:           edsave.asm
        masm -DEGAMONO -z-t-b63 edsave;

egamisc.obj:           egamisc.asm
        masm -DEGAMONO -z-t-b63 egamisc;

gsmode.obj:           gsmode.asm
        masm -DEGAMONO -z-t-b63 gsmode;

setswap.obj:           setswap.asm
        masm -DEGAMONO -z-t-b63 setswap;

srfontf.obj:           srfontf.asm
        masm -DEGAMONO -z-t-b63 srfontf;

srscr.obj:           srscr.asm
        masm -DEGAMONO -z-t-b63 srscr;

srscrf.obj:           srscrf.asm
        masm -DEGAMONO -z-t-b63 srscrf;

egamono.obj:            egamono.asm
        masm -DEGAMONO -z-t-b63 egamono;

egamono.exe:		egamono.obj	  \
			egamono.lnk	  \
		        bepaint.obj	  \
		        blockdev.obj	  \
		        devinit.obj	  \
		        edsave.obj	  \
		        egamisc.obj	  \
		        gsmode.obj	  \
		        setswap.obj	  \
		        srfontf.obj	  \
		        srscr.obj	  \
		        srscrf.obj	  \
		        bin2hex.obj	  \
		        block.obj	  \
		        edgrab.obj	  \
		        entry.obj	  \
		        getinfo.obj	  \
		        grabbits.obj	  \
		        grabscr.obj	  \
		        inout.obj	  \
		        inquire.obj	  \
		        oem.obj 	  \
		        prompt.obj	  \
                        rcolor.obj
        link4 @egamono.lnk

egamono.grb:            egamono.exe
        exe2bin egamono.exe egamono.grb
