All: wfwapi.exe


LINKFLAGS=/NOD /NOE /align:16 /MAP
LIBS=slibcew libw ctl3d netapi wfwnet

OBJS=wfwapi.obj net.obj multinet.obj wnet.obj output.obj utility.obj
LINKFILES=wfwapi+net+multinet+wnet+output+utility


!if "$(DEBUG)"=="1"
CFLAGS= /nologo -c -AS -Gsw -W3 /Od /Zi
LINKFLAGS=$(LINKFLAGS) /CO
!else
CFLAGS= /nologo -c -AS -Gsw -W3 /Ox
!endif


wfwapi.res: wfwapi.rc wfwapi.h wfwapi.ico dialogs.dlg
   rc -r wfwapi.rc

wfwapi.obj: wfwapi.c
   $(CC) $(CFLAGS) wfwapi.c

net.obj: net.c
   $(CC) $(CFLAGS) net.c

multinet.obj: multinet.c
   $(CC) $(CFLAGS) multinet.c

wnet.obj: wnet.c
   $(CC) $(CFLAGS) wnet.c

output.obj: output.c
   $(CC) $(CFLAGS) output.c

utility.obj: utility.c
   $(CC) $(CFLAGS) utility.c

wfwapi.exe: $(OBJS) wfwapi.def wfwapi.res
 link $(LINKFLAGS) $(LINKFILES), wfwapi, NUL, $(LIBS), wfwapi.def
 rc wfwapi.res


clean:
    -erase *.exe
    -erase *.obj
    -erase wfwapi.res
