cconfig.obj:     config.asm
    masm -DCOLOR -z-t-b63 config,cconfig;

cconfig.bin:     cconfig.obj
    link cconfig;
    exe2bin cconfig

bconfig.obj:     config.asm
    masm -DBLKWHITE -z-t-b63 config,bconfig;

bconfig.bin:     bconfig.obj
    link bconfig;
    exe2bin bconfig

fonts.obj:      fonts.asm
    masm  -z-t-b63 fonts;

fonts.bin:      fonts.obj
    link fonts;
    exe2bin fonts

#
# First, build the monochrome resource.  This is not used by any sample 
# drivers in the kit but can be used as resources for other ultra-high 
# resolution monochrome display devices.
# Then, build the color resource.  This .RES file will be used by the
# sample 8514/A driver.  

8514mono.res:   8514.rc                                         \
                normal.cur  ibeam.cur   wait.cur    cross.cur   \
                up.cur      size.cur    icon.cur    sample.ico  \
                hand.ico    ques.ico    bang.ico    note.ico    \
                right.bmp   left.bmp    up.bmp      down.bmp    \
                check.bmp   btsize.bmp  size.bmp    close.bmp   \
                button.bmp  btncorn.bmp bconfig.bin  fonts.bin
     copy bconfig.bin config.bin
     rc -r 8514.rc
     copy 8514.res 8514mono.res
     erase 8514.res

8514.res:       8514.rc                                         \
                normal.cur  ibeam.cur   wait.cur    cross.cur   \
                up.cur      size.cur    icon.cur    sample.ico  \
                hand.ico    ques.ico    bang.ico    note.ico    \
                right.bmp   left.bmp    up.bmp      down.bmp    \
                check.bmp   btsize.bmp  size.bmp    close.bmp   \
                button.bmp  btncorn.bmp cconfig.bin  fonts.bin
     copy cconfig.bin config.bin
     rc -r 8514.rc
     erase config.bin
