#
#  Definition of macros
#

# Flags for masm.
# Use first definition for debugging only
# Use second definition for building only.
#AFLAGS = -MX -ZI
AFLAGS = -MX 

# Flags for C Compiler.
# Use first definition for debugging only
# Use second definition for building only.
#CFLAGS = -c -Od -Zi
CFLAGS = -c -Os -Zp

OBJLIST = sudisk.obj subinovl.obj sufont.obj sucopy.obj sureadme.obj \
graphics.obj suinf.obj sudata.obj susel.obj suscr.obj sumain.obj \
susource.obj sudest.obj suwinini.obj sudriver.obj suprintr.obj suintl.obj \
disptests.obj decide.obj sucompat.obj

#
#  Standard inference rules
#

.c.obj:
    cl $(CFLAGS) $*.c

disptests.obj: disptests.asm
	masm $(AFLAGS) disptests.asm;

#
#  The C File List
#
graphics.obj: graphics.c

decide.obj: decide.c id.h

sureadme.obj: sureadme.c setup.h

suwinini.obj: suwinini.c setup.h

sudest.obj: sudest.c setup.h

suprintr.obj: suprintr.c setup.h

suintl.obj: suintl.c setup.h

sudriver.obj: sudriver.c setup.h

subinovl.obj: subinovl.c setup.h

sudisk.obj: sudisk.c setup.h

sufont.obj: sufont.c setup.h

sucopy.obj: sucopy.c setup.h

suinf.obj: suinf.c setup.h

sudata.obj: sudata.c setup.h

susel.obj: susel.c setup.h id.h

suscr.obj: suscr.c setup.h

susource.obj: susource.c setup.h

sumain.obj: sumain.c  setup.h id.h

sucompat.obj: sucompat.c setup.h

setup.exe: $(OBJLIST)
	link @setup.lnk;
    mapsym setup

# MSLOGO.LGD

convlogo.exe: convlogo.c
    cl -c -Ox convlogo.c
    link convlogo,,,slibcec/NOD

mslogo.lgd: logo.bmp convlogo.c
    convlogo logo.bmp > mslogo.asm
    masm mslogo;
    link mslogo;
    exe2bin mslogo.exe mslogo.lgd
    erase mslogo.obj
    erase mslogo.exe
