
PROJ=SHESAMP
OBJS=shesamp.obj defclsf.obj
MAKEDLL=1
#LIBS=OLE32.lib SHELL32.LIB COMCTL32.LIB uuid.lib
LIBS=SHELL32.LIB COMCTL32.LIB uuid.lib
DLLENTRY=LibMain

!include $(SDKROOT)\inc32\w32chico.mk
