FILES = cm02z.asm cm03z.asm cm04z.asm \
        cm05z.asm cm06z.asm cm07z.asm cm08z.asm \
        cm09z.asm cm0az.asm cm0bz.asm cm0cz.asm \
        cm0dz.asm cm0ez.asm cm0fz.asm cm10z.asm \
        cm11z.asm cm12z.asm cm13z.asm cm14z.asm \
        cm15z.asm cm16z.asm cm17z.asm cm18z.asm \
        cm19z.asm cm1az.asm cm1bz.asm cm1cz.asm \
        cm1dz.asm cm1ez.asm cm1fz.asm cm20z.asm \
        cm21z.asm cm22z.asm cm23z.asm cm24z.asm \
        cm25z.asm cm26z.asm cm27z.asm cm28z.asm \
        cm29z.asm cm2az.asm cm2bz.asm cm2cz.asm \
        cm2dz.asm cm2ez.asm cm2fz.asm cm30z.asm \
        cm31z.asm cm32z.asm cm33z.asm cm34z.asm \
        cm35z.asm cm36z.asm cm37z.asm cm38z.asm \
        cm39z.asm cm3az.asm cm3bz.asm cm3cz.asm \
        cm3dz.asm cm3ez.asm cm3fz.asm cm40z.asm \
        cm41z.asm cm42z.asm cm43z.asm cm44z.asm \
        cm45z.asm cm46z.asm cm47z.asm cm48z.asm \
        cm49z.asm cm4az.asm cm4bz.asm cm4cz.asm \
        cm4dz.asm cm4ez.asm cm4fz.asm cm50z.asm \
        cm51z.asm cm52z.asm cm53z.asm cm54z.asm \
        cm55z.asm cm56z.asm cm57z.asm cm58z.asm \
        cm59z.asm cm5az.asm cm5bz.asm 

!include ..\local.mk

