
#############################################################################
#
#   THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
#   KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
#   PURPOSE.
#
#   Copyright (c) 1992, 1993  Microsoft Corporation.  All Rights Reserved.
#
#############################################################################

CC  = cl -c -W3 -AS -Gs -GA -Zip -Oxwt $(DEF)
ASM = masm -Mx -Zi
LINK= link /CO/NOE/NOD/LI/MAP/AL:16/ONERROR:NOEXE
NAME= icwalk
DEF =-DDEBUG -DSTRICT
RC  = rc

OBJ  = icwalk.obj
LIBS = libw slibcew vfw

.c.obj:
        $(CC) $*.c

.asm.obj:
	$(ASM) $*;

goal: $(NAME).exe

$(NAME).exe: $(OBJ) $(NAME).res $(NAME).def makefile
        $(LINK) $(OBJ), $(NAME), $(NAME),$(LIBS), $(NAME).def
        $(RC) -31 $(NAME).res
        -cvpack -p $(NAME).exe
        -mapsym $(NAME).map

$(NAME).res: $(NAME).rc $(NAME).ico $(NAME).dlg
        $(RC) -r $(NAME).rc

clean:
        del $(NAME).exe
        del *.res
        del *.obj
        del *.map
        del *.sym
        del *.pdb

copy:
	copy $(NAME).exe ..\..\bin
	copy $(NAME).sym ..\..\bin

depend:
	mv makefile makefile.old
	sed "/^# START Dependencies/,/^# END Dependencies/D" makefile.old > makefile
	del makefile.old
	echo # START Dependencies >> makefile
	includes -l *.c *.asm >> makefile
	echo # END Dependencies >> makefile

# START Dependencies  
# END Dependencies  
