* _ui.h

***********************************************************
localization strings and constants for _ui.vcx 
***********************************************************

* this one may be removed:
* _WindowHandler:
#DEFINE MENUPROMPT_MED_UNDO  "\<Undo"
#DEFINE MENUKEY_MED_UNDO     [KEY CTRL+Z, "Ctrl+Z"]
#DEFINE MENUPROMPT_MED_REDO  "Re\<do"
#DEFINE MENUKEY_MED_REDO     [KEY CTRL+R, "Ctrl+R"]
#DEFINE MENUPROMPT_MED_CUT   "Cu\<t"
#DEFINE MENUKEY_MED_CUT      [KEY CTRL+X, "Ctrl+X"]
#DEFINE MENUPROMPT_MED_COPY  "\<Copy"
#DEFINE MENUKEY_MED_COPY     [KEY CTRL+C, "Ctrl+C"] 
#DEFINE MENUPROMPT_MED_PASTE "\<Paste"
#DEFINE MENUKEY_MED_PASTE    [KEY CTRL+V, "Ctrl+V"]
#DEFINE MENUPROMPT_MED_CLEAR "Cle\<ar"  
#DEFINE MENUKEY_MED_CLEAR    []
#DEFINE MENUPROMPT_MED_SLCTA "Se\<lect All"
#DEFINE MENUKEY_MED_SLCTA    [KEY CTRL+A, "Ctrl+A"]
#DEFINE MENUPROMPT_MED_FIND  "\<Find..."
#DEFINE MENUKEY_MED_FIND     [KEY CTRL+F, "Ctrl+F"]
#DEFINE MENUPROMPT_MED_FINDA "Find A\<gain"
#DEFINE MENUKEY_MED_FINDA    [KEY CTRL+G, "Ctrl+G"]
#DEFINE MENUPROMPT_MED_REPL  "R\<eplace..."
#DEFINE MENUKEY_MED_REPL     [KEY CTRL+L, "Ctrl+L"]
#DEFINE MENUPROMPT_MED_PSTLK "Paste \<Special..." 
#DEFINE MENUKEY_MED_PSTLK    []
#DEFINE MENUPROMPT_MED_GOTO  "Go to Li\<ne..."
#DEFINE MENUKEY_MED_GOTO     [] 
#DEFINE MENUPROMPT_MED_INSOB "\<Insert Object..." 
#DEFINE MENUKEY_MED_INSOB    []
#DEFINE MENUPROMPT_MED_OBJ   "\<Object..."
#DEFINE MENUKEY_MED_OBJ      []
#DEFINE MENUPROMPT_MED_LINK  "Lin\<ks..."
#DEFINE MENUKEY_MED_LINK     []
#DEFINE MENUPROMPT_MED_PREF  "Prope\<rties..."   
#DEFINE MENUKEY_MED_PREF     []
* #DEFINE MENUPROMPT_MED_... ""
* #DEFINE MENUKEY_MED_...    []
   
* _ModalAwareToolbar:
#DEFINE WINDOWTYPE_MODELESS   0
#DEFINE WINDOWTYPE_MODAL      1
#DEFINE WINDOWTYPE_READ       2
#DEFINE WINDOWTYPE_READMODAL  3

