DEVICE=NE3200

OBJS=\
$(BIN)\ne3200.obj\
$(BIN)\command.obj\
$(BIN)\interrup.obj\
$(BIN)\packet.obj\
$(BIN)\request.obj\
$(BIN)\reset.obj\
$(BIN)\loopback.obj\
$(BIN)\send.obj\
$(BIN)\transfer.obj\
$(BIN)\ndisdev.obj


!include $(DDKROOT)\net\ndis3\src\ndis.mk
