!ifdef NTMAKEENV
all:            # NTMAKEENV
clean:          # NTMAKEENV
!else  # NTMAKEENV
#----------------------------------------------------------------------------
#
#  ActiveX SDK makefile
#
#  THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
#  KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
#  PURPOSE.
#
#  Copyright (c) 1992 - 1997 Microsoft Corporation.  All Rights Reserved.
#
#----------------------------------------------------------------------------

!ifndef AXSDK
AXSDK = ..
!endif

DIR_LIST = base


#----------------------------------------------------------------------------

!include $(AXSDK)\tools\activex.mak
!endif          # NTMAKEENV
