;**********************************************************************;
;**********************************************************************;
;								       ;
; File Name:       KEYS.INC                      		       ;
;								       ;
; Program Name:    RIPL DLC Boot ROM Module             	       ;
;								       ;
; Companion Files: None						       ;
;								       ;
; Function:        This module contains all the very important         ;
;		   directives that control the way the source code is  ;
;		   assembled.                                          ;
;                                                                      ;     
; History:             						       ;
;								       ;
;     02/20/90  Mike Witkowski - Original Version 0.0		       ;
;								       ;
;**********************************************************************;
;**********************************************************************;


		.8086
