# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (C) 1992 Microsoft Corporation
# All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and Microsoft
# QuickHelp and/or WinHelp documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=DOCKTOOL
OBJS=docktool.obj dockdoc.obj dockvw.obj tooldlg.obj editbar.obj mainfrm.obj \
	palette.obj searchbx.obj

!include ..\sample_.mak
