# Microsoft HIMEM Device Driver Makefile
#                                       
# First build HIMEM.SYS (the actual device driver):
#                                                  

himem.obj: himem.asm
    masm -z-t-b63 himem;

himem.exe: himem.obj
    link4 himem;

himem.sys: himem.exe
    exe2bin himem.exe himem.sys

#
# Now, build a test program for the HIMEM.SYS device driver:
#

hitest.obj: hitest.asm
    masm -z-t-b63 hitest;

hitest.exe: hitest.obj
    link4 hitest;

hitest.com: hitest.exe
    exe2bin hitest.exe hitest.com

