#############################################################################
#
#   THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
#   KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
#   PURPOSE.
#
#   Copyright (c) 1992, 1993  Microsoft Corporation.  All Rights Reserved.
#
#############################################################################
#
#   MAKEFILE
#
#   constructs the DIB Sequence File Handler
#
#   to build a debug version:
#       NMAKE
#   to build a non debug version:
#       NMAKE DEBUG=NO
#
############################################################################

NAME	=wavefile
DEFFILE	=$(NAME).def


!if "$(DEBUG)" == "NO"

DEF = 
CC  = cl -c -nologo -W3 -ASw -G2s -GA -GEd -DWINDLL -Zdp -Oxws $(DEF)
ASM = masm -Mx -t -DSEGNAME=_TEXT -D?QUIET $(DEF)
LINK= link /L /MAP /NOPACKCODE /NOE /NOD /ONERROR:NOEXE
LIBMAN = lib /NOE

!else

DEF   = -DDEBUG 
MASMOPT = -Zi -DDEBUG
ASM = masm -Mx -t -DSEGNAME=_TEXT -D?QUIET $(DEF) $(MASMOPT)
CC  = cl -c -nologo -W3 -ASw -G2s -GA -GEd -DWINDLL -Zdp -Oxws -Zid $(DEF)
LINK	= link /L /MAP /NOPACKCODE /NOE /NOD /CO /LI /ONERROR:NOEXE
LIBMAN = lib /NOE

!endif



OBJ1	= muldiv32.obj extra.obj factory1.obj $(NAME).obj 

OBJ    = $(OBJ1)
LIBS	=libw sdllcew shell compobj mmsystem


.c.obj:
	$(CC) $*.c
.asm.obj:
	$(ASM) $*.asm;

###################### goal ######################

goal:  $(NAME).dll


##################################################

$(NAME).dll $(NAME).map: $(OBJ) $(NAME).res $(DEFFILE)
   $(LINK) @<<
	$(OBJ),
	$(NAME).dll,
	$(NAME),
	$(LIBS),
	$(NAME).def
<<
	rc -31 $(NAME).res $(NAME).dll
!if "$(DEBUG)" != "NO"
	cvpack -p $(NAME).dll
!endif
   mapsym $(NAME).map


$(NAME).res: $(NAME).rc 
	rc -r $(DEF) $(NAME).rc

$(NAME).rc:  $(NAME).h


##################### clean ######################

clean:
	del $(NAME).dll
	del *.obj
	del *.res
	del *.map
	del *.sym
	del *.pdb
	del *.lst

##################### copy #######################
copy:
	copy $(NAME).dll ..\..\bin
	copy $(NAME).sym ..\..\bin


##################### depend #####################

$(NAME).obj: $(NAME).c $(NAME).h 
extra.obj: extra.c extra.h 
$(NAME).c: $(NAME).h 
factory1.obj: factory1.c $(NAME).h
$(NAME).res: $(NAME).rc
$(NAME).rc: $(NAME).h

# END Dependencies 
