/*++ BUILD Version: 0001    // Increment this if a change has global effects

Copyright (c) 1992  Microsoft Corporation

Module Name:

    netevent.h

Abstract:

    Definitions for network events.

Author:

    Portable Systems Group 6-May-1992

Revision History:

Notes:

    This file is generated by the MC tool from the netevent.mc file.

--*/

#ifndef _NETEVENT_
#define _NETEVENT_


/////////////////////////////////////////////////////////////////////////
//
// Lanman Server Events (2000 - 2999)
//     2000-2499 are generated by the server driver (kernel mode)
//     2500-2999 are generated by the server service (user mode)
//
/////////////////////////////////////////////////////////////////////////


// Server driver events, issued from kernel mode.  Don't use %1 for
// server-supplied insertion strings -- the I/O system provides the
// first string.

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//
#define STATUS_SEVERITY_WARNING          0x2
#define STATUS_SEVERITY_SUCCESS          0x0
#define STATUS_SEVERITY_INFORMATIONAL    0x1
#define STATUS_SEVERITY_ERROR            0x3


//
// MessageId: EVENT_SRV_SERVICE_FAILED
//
// MessageText:
//
//  The server's call to a system service failed unexpectedly.
//
#define EVENT_SRV_SERVICE_FAILED         0xC00007D0L

//
// MessageId: EVENT_SRV_RESOURCE_SHORTAGE
//
// MessageText:
//
//  The server was unable to perform an operation due to a shortage of available resources.
//
#define EVENT_SRV_RESOURCE_SHORTAGE      0xC00007D1L

//
// MessageId: EVENT_SRV_CANT_CREATE_DEVICE
//
// MessageText:
//
//  The server could not create its device.  The server could not be started.
//
#define EVENT_SRV_CANT_CREATE_DEVICE     0xC00007D2L

//
// MessageId: EVENT_SRV_CANT_CREATE_PROCESS
//
// MessageText:
//
//  The server could not create a process.  The server could not be started.
//
#define EVENT_SRV_CANT_CREATE_PROCESS    0xC00007D3L

//
// MessageId: EVENT_SRV_CANT_CREATE_THREAD
//
// MessageText:
//
//  The server could not create a startup thread.  The server could not be started.
//
#define EVENT_SRV_CANT_CREATE_THREAD     0xC00007D4L

//
// MessageId: EVENT_SRV_UNEXPECTED_DISC
//
// MessageText:
//
//  The server received an unexpected disconnection from a client.
//
#define EVENT_SRV_UNEXPECTED_DISC        0xC00007D5L

//
// MessageId: EVENT_SRV_INVALID_REQUEST
//
// MessageText:
//
//  The server received an incorrectly formatted request from %2.
//
#define EVENT_SRV_INVALID_REQUEST        0xC00007D6L

//
// MessageId: EVENT_SRV_CANT_OPEN_NPFS
//
// MessageText:
//
//  The server could not open the named pipe file system.  Remote named pipes are disabled.
//
#define EVENT_SRV_CANT_OPEN_NPFS         0xC00007D7L

//
// MessageId: EVENT_SRV_CANT_GROW_TABLE
//
// MessageText:
//
//  The server could not expand a table because the table reached the maximum size.
//
#define EVENT_SRV_CANT_GROW_TABLE        0xC00007D9L

//
// MessageId: EVENT_SRV_CANT_START_SCAVENGER
//
// MessageText:
//
//  The server could not start the scavenger thread.  The server could not be started.
//
#define EVENT_SRV_CANT_START_SCAVENGER   0xC00007DAL

//
// MessageId: EVENT_SRV_IRP_STACK_SIZE
//
// MessageText:
//
//  The server's configuration parameter "irpstacksize" is too small for the server to use a local device.  Please increase the value of this parameter.
//
#define EVENT_SRV_IRP_STACK_SIZE         0xC00007DBL

//
// MessageId: EVENT_SRV_NETWORK_ERROR
//
// MessageText:
//
//  The server has encountered a network error.
//
#define EVENT_SRV_NETWORK_ERROR          0xC00007DCL

//
// MessageId: EVENT_SRV_DISK_FULL
//
// MessageText:
//
//  The %2 disk is at or near capacity.  You may need to delete some files.
//
#define EVENT_SRV_DISK_FULL              0x800007DDL

//
// MessageId: EVENT_SRV_NO_VIRTUAL_MEMORY
//
// MessageText:
//
//  The server was unable to allocate virtual memory.
//
#define EVENT_SRV_NO_VIRTUAL_MEMORY      0xC00007E0L

//
// MessageId: EVENT_SRV_NONPAGED_POOL_LIMIT
//
// MessageText:
//
//  The server was unable to allocate from the system nonpaged pool because the server reached the configured limit for nonpaged pool allocations.
//
#define EVENT_SRV_NONPAGED_POOL_LIMIT    0xC00007E1L

//
// MessageId: EVENT_SRV_PAGED_POOL_LIMIT
//
// MessageText:
//
//  The server was unable to allocate from the system paged pool because the server reached the configured limit for paged pool allocations.
//
#define EVENT_SRV_PAGED_POOL_LIMIT       0xC00007E2L

//
// MessageId: EVENT_SRV_NO_NONPAGED_POOL
//
// MessageText:
//
//  The server was unable to allocate from the system nonpaged pool because the pool was empty.
//
#define EVENT_SRV_NO_NONPAGED_POOL       0xC00007E3L

//
// MessageId: EVENT_SRV_NO_PAGED_POOL
//
// MessageText:
//
//  The server was unable to allocate from the system paged pool because the pool was empty.
//
#define EVENT_SRV_NO_PAGED_POOL          0xC00007E4L


// Server service events, issued from user mode.  %1 is the first
// service-supplied insertion string.

//
// MessageId: EVENT_SRV_KEY_NOT_FOUND
//
// MessageText:
//
//  The server's Registry key %1 was not present.  The server could not start.
//
#define EVENT_SRV_KEY_NOT_FOUND          0xC00009C5L

//
// MessageId: EVENT_SRV_KEY_NOT_CREATED
//
// MessageText:
//
//  The server's Registry key %1 was not present and could not be created.  The server could not start.
//
#define EVENT_SRV_KEY_NOT_CREATED        0xC00009C6L

//
// MessageId: EVENT_SRV_NO_TRANSPORTS_BOUND
//
// MessageText:
//
//  The server did not bind to any transports.  The server could not start.
//
#define EVENT_SRV_NO_TRANSPORTS_BOUND    0xC00009C7L

//
// MessageId: EVENT_SRV_CANT_BIND_TO_TRANSPORT
//
// MessageText:
//
//  The server could not bind to the transport %1.
//
#define EVENT_SRV_CANT_BIND_TO_TRANSPORT 0x800009C8L

//
// MessageId: EVENT_SRV_CANT_BIND_DUP_NAME
//
// MessageText:
//
//  The server could not bind to the transport %1 because another computer on the network has the same name.  The server could not start.
//
#define EVENT_SRV_CANT_BIND_DUP_NAME     0xC00009C9L

//
// MessageId: EVENT_SRV_INVALID_REGISTRY_VALUE
//
// MessageText:
//
//  The value named %1 in the server's Registry key %2 was invalid.  The value was ignored, and processing continued.
//
#define EVENT_SRV_INVALID_REGISTRY_VALUE 0x800009CAL

//
// MessageId: EVENT_SRV_INVALID_SD
//
// MessageText:
//
//  The security descriptor stored in the Registry for the share %1 was invalid.  The share was not automatically recreated.
//
#define EVENT_SRV_INVALID_SD             0x800009CBL

//
// MessageId: EVENT_SRV_CANT_LOAD_DRIVER
//
// MessageText:
//
//  The Server service was unable to load the server driver.
//
#define EVENT_SRV_CANT_LOAD_DRIVER       0x800009CCL

//
// MessageId: EVENT_SRV_CANT_UNLOAD_DRIVER
//
// MessageText:
//
//  The Server service was unable to unload the server driver.
//
#define EVENT_SRV_CANT_UNLOAD_DRIVER     0x800009CDL


/////////////////////////////////////////////////////////////////////////
//
// Lanman Redirector Events
//
//
/////////////////////////////////////////////////////////////////////////


//
// MessageId: EVENT_RDR_RESOURCE_SHORTAGE
//
// MessageText:
//
//  The redirector was unable to allocate memory.
//
#define EVENT_RDR_RESOURCE_SHORTAGE      0x80000BB9L

//
// MessageId: EVENT_RDR_CANT_CREATE_DEVICE
//
// MessageText:
//
//  The redirector could not create its device.  The redirector could not be started.
//
#define EVENT_RDR_CANT_CREATE_DEVICE     0x80000BBAL

//
// MessageId: EVENT_RDR_CANT_CREATE_THREAD
//
// MessageText:
//
//  The redirector could not create a system thread.
//
#define EVENT_RDR_CANT_CREATE_THREAD     0x80000BBBL

//
// MessageId: EVENT_RDR_CANT_SET_THREAD
//
// MessageText:
//
//  The redirector could not set the priority for a system thread.
//
#define EVENT_RDR_CANT_SET_THREAD        0x80000BBCL

//
// MessageId: EVENT_RDR_INVALID_REPLY
//
// MessageText:
//
//  The redirector received an incorrectly formatted response from %2.
//
#define EVENT_RDR_INVALID_REPLY          0x80000BBDL

//
// MessageId: EVENT_RDR_INVALID_SMB
//
// MessageText:
//
//  The redirector received an SMB that was too short.
//
#define EVENT_RDR_INVALID_SMB            0x80000BBEL

//
// MessageId: EVENT_RDR_INVALID_LOCK_REPLY
//
// MessageText:
//
//  The redirector received an incorrect response from %2 to a lock request.
//
#define EVENT_RDR_INVALID_LOCK_REPLY     0x80000BBFL

//
// MessageId: EVENT_RDR_FAILED_UNLOCK
//
// MessageText:
//
//  The redirector failed to unlock part of a file on server %2.
//
#define EVENT_RDR_FAILED_UNLOCK          0x80000BC1L

//
// MessageId: EVENT_RDR_CLOSE_BEHIND
//
// MessageText:
//
//  The redirector failed to write data to server %2 after the file was closed.
//
#define EVENT_RDR_CLOSE_BEHIND           0x80000BC3L

//
// MessageId: EVENT_RDR_UNEXPECTED_ERROR
//
// MessageText:
//
//  An unexpected network error has occurred on the virtual circuit to %2.
//
#define EVENT_RDR_UNEXPECTED_ERROR       0x80000BC4L

//
// MessageId: EVENT_RDR_TIMEOUT
//
// MessageText:
//
//  The redirector has timed out a request to %2.
//
#define EVENT_RDR_TIMEOUT                0x80000BC5L

//
// MessageId: EVENT_RDR_INVALID_OPLOCK
//
// MessageText:
//
//  The redirector received an invalid oplock level from %2.
//
#define EVENT_RDR_INVALID_OPLOCK         0x80000BC6L

//
// MessageId: EVENT_RDR_CONNECTION_REFERENCE
//
// MessageText:
//
//  The redirector dereferenced a connection through zero.
//
#define EVENT_RDR_CONNECTION_REFERENCE   0x80000BC7L

//
// MessageId: EVENT_RDR_SERVER_REFERENCE
//
// MessageText:
//
//  The redirector dereferenced a server through zero.
//
#define EVENT_RDR_SERVER_REFERENCE       0x80000BC8L

//
// MessageId: EVENT_RDR_SMB_REFERENCE
//
// MessageText:
//
//  The redirector dereferenced the allocated SMB count through zero.
//
#define EVENT_RDR_SMB_REFERENCE          0x80000BC9L

//
// MessageId: EVENT_RDR_ENCRYPT
//
// MessageText:
//
//  The redirector accessed a share-level server that indicates it encrypts passwords.
//  This combination is not supported.
//
#define EVENT_RDR_ENCRYPT                0x80000BCAL

//
// MessageId: EVENT_RDR_CONNECTION
//
// MessageText:
//
//  The redirector failed to determine the connection type.
//
#define EVENT_RDR_CONNECTION             0x80000BCBL

//
// MessageId: EVENT_RDR_MAXCMDS
//
// MessageText:
//
//  The redirector failed to allocate a multiplex table entry.  This indicates that
//  the MAXCMDS parameter to the redirector is insufficient for the users needs.
//
#define EVENT_RDR_MAXCMDS                0x80000BCDL

//
// MessageId: EVENT_RDR_OPLOCK_SMB
//
// MessageText:
//
//  The redirector failed to allocate a buffer for an oplock break.
//
#define EVENT_RDR_OPLOCK_SMB             0x80000BCEL

//
// MessageId: EVENT_RDR_DISPOSITION
//
// MessageText:
//
//  The redirector failed to map the requested file disposition (for NtCreateFile).
//
#define EVENT_RDR_DISPOSITION            0x80000BCFL

//
// MessageId: EVENT_RDR_CONTEXTS
//
// MessageText:
//
//  The redirector is allocating additional resources for input/output request packet contexts.  This is
//  probably caused by a resource leak in the redirector.
//
#define EVENT_RDR_CONTEXTS               0x80000BD0L

//
// MessageId: EVENT_RDR_WRITE_BEHIND_FLUSH_FAILED
//
// MessageText:
//
//  A write-behind operation has failed to the remote server %2.  The data contains the amount requested to write and the amount actually written.
//
#define EVENT_RDR_WRITE_BEHIND_FLUSH_FAILED 0x80000BD1L

//
// MessageId: EVENT_RDR_AT_THREAD_MAX
//
// MessageText:
//
//  The redirector was unable to create a worker thread because it has already created the maximum number of configured work threads.
//
#define EVENT_RDR_AT_THREAD_MAX          0x80000BD2L

//
// MessageId: EVENT_RDR_CANT_READ_REGISTRY
//
// MessageText:
//
//  The redirector was unable to initialize variables from the Registry.
//
#define EVENT_RDR_CANT_READ_REGISTRY     0x80000BD3L

//
// MessageId: EVENT_RDR_TIMEZONE_BIAS_TOO_LARGE
//
// MessageText:
//
//  The time zone bias calculated between %2 and the current workstation is too
//  large.  The data specifies the number of 100ns units between the workstation
//  and server.  Make sure that the time of day on the workstation and server are
//  correct.
//
#define EVENT_RDR_TIMEZONE_BIAS_TOO_LARGE 0x80000BD4L

//
// MessageId: EVENT_RDR_PRIMARY_TRANSPORT_CONNECT_FAILED
//
// MessageText:
//
//  The redirector has failed to connect to the server %2 on the primary transport.  The data contains the error.
//
#define EVENT_RDR_PRIMARY_TRANSPORT_CONNECT_FAILED 0x80000BD5L



/////////////////////////////////////////////////////////////////////////
//
// STREAMS Environment Events
//
// Codes 4000 - 4099
//
/////////////////////////////////////////////////////////////////////////


//
// MessageId: EVENT_STREAMS_STRLOG
//
// MessageText:
//
//  %2.
//
#define EVENT_STREAMS_STRLOG             0xC0000FA0L

//
// MessageId: EVENT_STREAMS_ALLOCB_FAILURE
//
// MessageText:
//
//  Unable to allocate a %2 byte message.
//
#define EVENT_STREAMS_ALLOCB_FAILURE     0x80000FA1L

//
// MessageId: EVENT_STREAMS_ALLOCB_FAILURE_CNT
//
// MessageText:
//
//  %2 message allocations have failed since initialization.
//
#define EVENT_STREAMS_ALLOCB_FAILURE_CNT 0x80000FA2L

//
// MessageId: EVENT_STREAMS_ESBALLOC_FAILURE
//
// MessageText:
//
//  Unable to allocate a %2 byte external message.
//
#define EVENT_STREAMS_ESBALLOC_FAILURE   0x80000FA3L

//
// MessageId: EVENT_STREAMS_ESBALLOC_FAILURE_CNT
//
// MessageText:
//
//  %2 external message allocations have failed since initialization.
//
#define EVENT_STREAMS_ESBALLOC_FAILURE_CNT 0x80000FA4L



/////////////////////////////////////////////////////////////////////////
//
// TCP/IP Events
//
// Codes 4100 - 4299
//
/////////////////////////////////////////////////////////////////////////


//
// Common TCP/IP messages
//
// Codes 4100 - 4149
//
//

//
// MessageId: EVENT_TCPIP_INIT_FAIL
//
// MessageText:
//
//  %2 initialization failed. Unable to allocate critical resources.
//
#define EVENT_TCPIP_INIT_FAIL            0xC0001004L

//
// MessageId: EVENT_TCPIP_PARAM_INIT_FAILURE
//
// MessageText:
//
//  %2 was unable to extract the value of parameter %3 from the Registry.
//  Setting to the default value of %4.
//
#define EVENT_TCPIP_PARAM_INIT_FAILURE   0x80001005L

//
// MessageId: EVENT_TCPIP_PARAM_BAD_VALUE
//
// MessageText:
//
//  The %2 Registry parameter %3 was set to invalid value %4.
//  Setting to the default value of %5.
//
#define EVENT_TCPIP_PARAM_BAD_VALUE      0x80001006L

//
// MessageId: EVENT_TCPIP_DRIVER_NOT_INIT
//
// MessageText:
//
//  Open of %2 attempted prior to initialization.
//
#define EVENT_TCPIP_DRIVER_NOT_INIT      0xC0001007L

//
// MessageId: EVENT_TCPIP_NONCLONE_OPEN
//
// MessageText:
//
//  Non-clone open of %2 attempted.
//
#define EVENT_TCPIP_NONCLONE_OPEN        0xC0001008L

//
// MessageId: EVENT_TCPIP_REOPEN
//
// MessageText:
//
//  Reopen of same %2 stream attempted.
//
#define EVENT_TCPIP_REOPEN               0xC0001009L

//
// MessageId: EVENT_TCPIP_BAD_READ_IOCTL
//
// MessageText:
//
//  %2 discarded a read IOCTL message of unknown type %3.
//
#define EVENT_TCPIP_BAD_READ_IOCTL       0x4000100AL

//
// MessageId: EVENT_TCPIP_BAD_WRITE_IOCTL
//
// MessageText:
//
//  %2 discarded a write IOCTL message of unknown type %3.
//
#define EVENT_TCPIP_BAD_WRITE_IOCTL      0x4000100BL

//
// MessageId: EVENT_TCPIP_BAD_READ_IOCTL_ACK
//
// MessageText:
//
//  %2 discarded a read IOCTL ACK/NAK message of unknown type %3.
//
#define EVENT_TCPIP_BAD_READ_IOCTL_ACK   0x4000100CL

//
// MessageId: EVENT_TCPIP_BAD_READ_PROTO
//
// MessageText:
//
//  %2 discarded a read PROTO message of unknown type %3.
//
#define EVENT_TCPIP_BAD_READ_PROTO       0x8000100DL

//
// MessageId: EVENT_TCPIP_BAD_WRITE_PROTO
//
// MessageText:
//
//  %2 discarded a write PROTO message of unknown type %3.
//
#define EVENT_TCPIP_BAD_WRITE_PROTO      0x8000100EL

//
// MessageId: EVENT_TCPIP_BAD_READ_MSG
//
// MessageText:
//
//  %2 discarded a read message of unknown type %3.
//
#define EVENT_TCPIP_BAD_READ_MSG         0x8000100FL

//
// MessageId: EVENT_TCPIP_BAD_WRITE_MSG
//
// MessageText:
//
//  %2 discarded a write message of unknown type %3.
//
#define EVENT_TCPIP_BAD_WRITE_MSG        0x80001010L

//
// MessageId: EVENT_TCPIP_BAD_PKT_LEN
//
// MessageText:
//
//  Amount of data in received packet does not match the size specified in
//  the header. Source %2, Destination %3, Protocol %4,
//  Specified size %5, Actual size %6.
//
#define EVENT_TCPIP_BAD_PKT_LEN          0x40001011L

//
// MessageId: EVENT_TCPIP_ORPHAN_ICMP
//
// MessageText:
//
//  %2 received an ICMP error packet on a nonexistent connection.
//  Type %3, Code %4, Source %5:%6, Destination %7:%8.
//
#define EVENT_TCPIP_ORPHAN_ICMP          0x40001012L

//
// MessageId: EVENT_TCPIP_NUM_ORPHAN_ICMPS
//
// MessageText:
//
//  %2 has received %3 ICMP error packets on nonexistent connections.
//
#define EVENT_TCPIP_NUM_ORPHAN_ICMPS     0x40001013L

//
// MessageId: EVENT_TCPIP_INVALID_ICMP
//
// MessageText:
//
//  %2 received an ICMP error packet of type %3, code %4.
//  The packet that caused the error was sent from source %5:%6
//  to destination %7:%8.
//
#define EVENT_TCPIP_INVALID_ICMP         0x40001014L


//
// ARP messages
//
// Codes 4150-4174

//
// MessageId: EVENT_ARP_NONUNICAST_ADDR
//
// MessageText:
//
//  Attempted to add nonunicast IP address %2 to the ARP cache.
//
#define EVENT_ARP_NONUNICAST_ADDR        0x80001036L

//
// MessageId: EVENT_ARP_CACHE_FULL
//
// MessageText:
//
//  The ARP cache is full. Unable to add entry for IP address %2.
//
#define EVENT_ARP_CACHE_FULL             0x80001037L

//
// MessageId: EVENT_ARP_BAD_REQUEST
//
// MessageText:
//
//  An ARP request was received for IP address %2 on network %3.
//
#define EVENT_ARP_BAD_REQUEST            0x40001038L

//
// MessageId: EVENT_ARP_BAD_REQUEST_CNT
//
// MessageText:
//
//  %2 ARP requests received from other networks.
//
#define EVENT_ARP_BAD_REQUEST_CNT        0x40001039L

//
// MessageId: EVENT_ARP_REG_FAILURE
//
// MessageText:
//
//  ARP-datalink registration failed. Unable to allocate a %2 byte message.
//
#define EVENT_ARP_REG_FAILURE            0xC000103AL

//
// MessageId: EVENT_ARP_CACHE_FAILURE
//
// MessageText:
//
//  Unable to allocate a %2 byte message to create the ARP cache.
//
#define EVENT_ARP_CACHE_FAILURE          0xC000103BL

//
// MessageId: EVENT_ARP_BAD_DL_VERSION
//
// MessageText:
//
//  ARP cannot link to DataLink interface version %2.
//
#define EVENT_ARP_BAD_DL_VERSION         0xC000103CL

//
// MessageId: EVENT_ARP_IPADDR_IN_USE
//
// MessageText:
//
//  ARP IP address %2 is already in use by another node.
//  TCP/IP will not use an address that is already in use.
//
#define EVENT_ARP_IPADDR_IN_USE          0xC000103DL


//
// IP Loopback messages
//
// Codes 4175-4184
//

//
// MessageId: EVENT_IPLOOP_OPEN_FAIL
//
// MessageText:
//
//  Open of IPLOOP failed due to lack of available buffers.
//
#define EVENT_IPLOOP_OPEN_FAIL           0xC000104FL


//
// IP/ICMP messages
//
// Codes 4185 - 4224

//
// MessageId: EVENT_IP_PROT_TAB_FULL
//
// MessageText:
//
//  Open of IP failed. The IP protocol table is full.
//
#define EVENT_IP_PROT_TAB_FULL           0xC0001059L

//
// MessageId: EVENT_IP_REG_FAILURE
//
// MessageText:
//
//  Unable to register protocol %2 with IP due to lack of available buffers.
//
#define EVENT_IP_REG_FAILURE             0xC000105AL

//
// MessageId: EVENT_IP_DEREG_FAILURE
//
// MessageText:
//
//  Unable to deregister protocol %2 with IP due to lack of available buffers.
//
#define EVENT_IP_DEREG_FAILURE           0xC000105BL

//
// MessageId: EVENT_IP_NO_WCARD_GWAY_DEL
//
// MessageText:
//
//  Wildcard deletion of IP gateway table entries is not permitted.
//
#define EVENT_IP_NO_WCARD_GWAY_DEL       0x8000105CL

//
// MessageId: EVENT_ICMP_BAD_CKSUM
//
// MessageText:
//
//  IP received an ICMP packet with a bad checksum.
//  Source %2, Destination %3.
//
#define EVENT_ICMP_BAD_CKSUM             0x4000105DL

//
// MessageId: EVENT_ICMP_BAD_TYPE
//
// MessageText:
//
//  IP received an ICMP packet with invalid type %2.
//  Source %3, Destination %4.
//
#define EVENT_ICMP_BAD_TYPE              0x4000105EL

//
// MessageId: EVENT_ICMP_BAD_OPT_LEN
//
// MessageText:
//
//  IP received an ICMP packet with option %2 of invalid length %3.
//  Type %4, Code %5, Source %6, Destination %7.
//
#define EVENT_ICMP_BAD_OPT_LEN           0x4000105FL

//
// MessageId: EVENT_ICMP_BAD_PROTOCOL
//
// MessageText:
//
//  IP received an ICMP packet with invalid destination protocol %2.
//  Type %3, Code %4, Source %5, Destination %6.
//
#define EVENT_ICMP_BAD_PROTOCOL          0x40001060L

//
// MessageId: EVENT_ICMP_BAD_PROTOCOL2
//
// MessageText:
//
//  IP received an ICMP packet with invalid destination protocol %2, muxid %3.
//  Type %4, Code %5, Source %6, Destination %7.
//
#define EVENT_ICMP_BAD_PROTOCOL2         0x40001061L

//
// MessageId: EVENT_IP_INVALID_BCAST
//
// MessageText:
//
//  IP broadcast attempted to invalid address %2.
//
#define EVENT_IP_INVALID_BCAST           0x80001062L

//
// MessageId: EVENT_IP_CANT_XMIT_DF
//
// MessageText:
//
//  IP could not transmit a packet of size %2 marked Don't Fragment.
//  Source %3, Destination %4.
//
#define EVENT_IP_CANT_XMIT_DF            0x80001063L

//
// MessageId: EVENT_IP_SMALL_HEADER
//
// MessageText:
//
//  IP has received %2 packets with headers of insufficient size.
//
#define EVENT_IP_SMALL_HEADER            0x40001064L

//
// MessageId: EVENT_IP_BAD_VERSION
//
// MessageText:
//
//  IP received a packet with incompatible header version %2.
//
#define EVENT_IP_BAD_VERSION             0x40001065L

//
// MessageId: EVENT_IP_BAD_CKSUM
//
// MessageText:
//
//  IP has received %2 packets with invalid header checksums.
//
#define EVENT_IP_BAD_CKSUM               0x40001066L

//
// MessageId: EVENT_IP_BAD_LENGTH
//
// MessageText:
//
//  Length mismatch in received IP packet header. Specified length %2,
//  actual %3. Source %4, Destination %5.
//
#define EVENT_IP_BAD_LENGTH              0x40001067L

//
// MessageId: EVENT_IP_BAD_LENGTHS
//
// MessageText:
//
//  
//  IP has received %2 packets with invalid lengths.
//
#define EVENT_IP_BAD_LENGTHS             0x40001068L

//
// MessageId: EVENT_IP_S_SRC_ROUTE_BCAST
//
// MessageText:
//
//  IP cannot source-route a broadcast packet.
//  Source %2, Destination %3.
//
#define EVENT_IP_S_SRC_ROUTE_BCAST       0x40001069L

//
// MessageId: EVENT_IP_TTL_EXPIRED
//
// MessageText:
//
//  Time To Live expired on received IP packet.
//  Protocol %2, Source %3, Destination %4.
//
#define EVENT_IP_TTL_EXPIRED             0x4000106AL

//
// MessageId: EVENT_IP_BAD_OPTION_LEN
//
// MessageText:
//
//  IP received a packet with option %2 of invalid length %3.
//  Source %4, Destination %5.
//
#define EVENT_IP_BAD_OPTION_LEN          0x4000106BL

//
// MessageId: EVENT_IP_R_SRC_ROUTE_BCAST
//
// MessageText:
//
//  IP received a source-routed broadcast.
//  Source %2, Destination %3.
//
#define EVENT_IP_R_SRC_ROUTE_BCAST       0x4000106CL

//
// MessageId: EVENT_IP_NET_ERROR
//
// MessageText:
//
//  IP received error %2 on network %3. Marking network as down.
//
#define EVENT_IP_NET_ERROR               0xC000106DL

//
// MessageId: EVENT_IP_FRAG_TIMEOUT
//
// MessageText:
//
//  IP has discarded %2 packets due to fragment reassembly timeout.
//
#define EVENT_IP_FRAG_TIMEOUT            0x4000106EL


//
// TCP messages
//
// Codes 4225 - 4264
//

//
// MessageId: EVENT_TCP_SYN_NO_OPTIONS
//
// MessageText:
//
//  TCP received a SYN packet with no options.
//  Source %2:%3, Destination %4:%5.
//
#define EVENT_TCP_SYN_NO_OPTIONS         0x40001081L

//
// MessageId: EVENT_TCP_BAD_TLI_TYPE
//
// MessageText:
//
//  TCP received a TLI write message of unknown type %2.
//
#define EVENT_TCP_BAD_TLI_TYPE           0x80001082L


//
// UDP messages
//
// Codes 4265 - 4299



/////////////////////////////////////////////////////////////////////////
//
// NBT Events
//
// Codes 4300 - 4399
//
/////////////////////////////////////////////////////////////////////////


//
// MessageId: EVENT_NBT_NOT_INIT
//
// MessageText:
//
//  Open of NBT attempted prior to initialization.
//
#define EVENT_NBT_NOT_INIT               0xC00010CCL

//
// MessageId: EVENT_NBT_LMHOSTS_TOO_BIG
//
// MessageText:
//
//  The NBT LMHOSTS file is too large to be loaded. The file may be at
//  most 4,194,304K in size.
//
#define EVENT_NBT_LMHOSTS_TOO_BIG        0xC00010CDL

//
// MessageId: EVENT_NBT_LMHOSTS_LOAD_FAILURE
//
// MessageText:
//
//  The NBT LMHOSTS file could not be loaded.
//
#define EVENT_NBT_LMHOSTS_LOAD_FAILURE   0xC00010CEL

//
// MessageId: EVENT_NBT_LMHOSTS_SYNTAX_ERROR
//
// MessageText:
//
//  The NBT LMHOSTS has a syntax error in line %2.
//  This Line will be skipped.
//
#define EVENT_NBT_LMHOSTS_SYNTAX_ERROR   0xC00010CFL



/////////////////////////////////////////////////////////////////////////
//
// TCP/IP and NBT Service Events
//
// Codes 4400 - 4499
//
/////////////////////////////////////////////////////////////////////////


//
// MessageId: EVENT_TCPIPSVC_NO_MEMORY
//
// MessageText:
//
//  Unable to allocate critical memory resources. The service could not be
//  started.
//
#define EVENT_TCPIPSVC_NO_MEMORY         0x00001130L

//
// MessageId: EVENT_TCPIPSVC_NO_REG_KEY
//
// MessageText:
//
//  Required Registry key %1 is missing.
//  The service could not be started.
//
#define EVENT_TCPIPSVC_NO_REG_KEY        0x00001131L

//
// MessageId: EVENT_TCPIPSVC_NO_REG_VALUE
//
// MessageText:
//
//  Required Registry value %1 is missing.
//  The service could not be started.
//
#define EVENT_TCPIPSVC_NO_REG_VALUE      0x00001132L

//
// MessageId: EVENT_TCPIPSVC_ARP_INIT_FAIL
//
// MessageText:
//
//  Unable to initialize ARP. Error code %1.
//  The service could not be started.
//
#define EVENT_TCPIPSVC_ARP_INIT_FAIL     0x00001133L

//
// MessageId: EVENT_TCPIPSVC_NO_DRV_UNDER_MOD
//
// MessageText:
//
//  No driver was specified under module %1.
//  The service could not be started.
//
#define EVENT_TCPIPSVC_NO_DRV_UNDER_MOD  0x00001134L

//
// MessageId: EVENT_TCPIPSVC_MUX_MOD
//
// MessageText:
//
//  Cannot multiplex module %1.
//  The service could not be started.
//
#define EVENT_TCPIPSVC_MUX_MOD           0x00001135L

//
// MessageId: EVENT_TCPIPSVC_UNKNOWN_MOD
//
// MessageText:
//
//  Cannot plumb unknown driver/module %1.
//  The service could not be started.
//
#define EVENT_TCPIPSVC_UNKNOWN_MOD       0x00001136L

//
// MessageId: EVENT_TCPIPSVC_BAD_MOD_INSTANCE
//
// MessageText:
//
//  Invalid instance number %1 specified for module %2.
//  The service could not be started.
//
#define EVENT_TCPIPSVC_BAD_MOD_INSTANCE  0x00001137L

//
// MessageId: EVENT_TCPIPSVC_BAD_MUXID
//
// MessageText:
//
//  Invalid muxid %1 specified for upper driver %2.
//  The service could not be started.
//
#define EVENT_TCPIPSVC_BAD_MUXID         0x00001138L

//
// MessageId: EVENT_TCPIPSVC_UNKNOWN_CTRL
//
// MessageText:
//
//  Unknown control action %1 for link %2 - %3.
//  The service could not be started.
//
#define EVENT_TCPIPSVC_UNKNOWN_CTRL      0x00001139L

//
// MessageId: EVENT_TCPIPSVC_IP_INIT_FAIL
//
// MessageText:
//
//  Unable to initialize IP. Error code %1.
//  The service could not be started.
//
#define EVENT_TCPIPSVC_IP_INIT_FAIL      0x0000113AL

//
// MessageId: EVENT_TCPIPSVC_BAD_IP_ADDR
//
// MessageText:
//
//  IP address %1 is not valid. No link to this network
//  was established.
//
#define EVENT_TCPIPSVC_BAD_IP_ADDR       0x0000113BL

//
// MessageId: EVENT_TCPIPSVC_BAD_SUBNET_MASK
//
// MessageText:
//
//  Subnet mask %2 for IP address %1 is not valid.
//  No link to this network was established.
//
#define EVENT_TCPIPSVC_BAD_SUBNET_MASK   0x0000113CL

//
// MessageId: EVENT_TCPIPSVC_NDIS_INIT_FAIL
//
// MessageText:
//
//  Unable to bind to interface %1.
//  Error code %2.
//
#define EVENT_TCPIPSVC_NDIS_INIT_FAIL    0x0000113DL

//
// MessageId: EVENT_TCPIPSVC_DRV_OPEN_FAIL
//
// MessageText:
//
//  Unable to open driver %1. Error code %2.
//  The service could not be started.
//
#define EVENT_TCPIPSVC_DRV_OPEN_FAIL     0x0000113EL

//
// MessageId: EVENT_TCPIPSVC_MOD_PUSH_FAIL
//
// MessageText:
//
//  Unable to push module %1 onto a stream. Error code %2.
//  The service could not be started.
//
#define EVENT_TCPIPSVC_MOD_PUSH_FAIL     0x0000113FL

//
// MessageId: EVENT_TCPIPSVC_LINK_FAIL
//
// MessageText:
//
//  Unable to link driver %1 under driver %2. Error code %3.
//  The service could not be started.
//
#define EVENT_TCPIPSVC_LINK_FAIL         0x00001140L

//
// MessageId: EVENT_TCPIPSVC_SC_REG_FAIL
//
// MessageText:
//
//  Unable to register with the service controller. Error code %1.
//  The service could not be started.
//
#define EVENT_TCPIPSVC_SC_REG_FAIL       0x00001141L

//
// MessageId: EVENT_TCPIPSVC_BAD_GWAY
//
// MessageText:
//
//  %1 is not a valid default gateway. The service could
//  not be started.
//
#define EVENT_TCPIPSVC_BAD_GWAY          0x00001142L

//
// MessageId: EVENT_TCPIPSVC_BAD_TRAILER
//
// MessageText:
//
//  Invalid ARP trailer specification %1.
//
#define EVENT_TCPIPSVC_BAD_TRAILER       0x00001143L

//
// MessageId: EVENT_TCPIPSVC_TRACE
//
// MessageText:
//
//  %1
//
#define EVENT_TCPIPSVC_TRACE             0x00001144L

//
// MessageId: EVENT_NBTSVC_DRV_OPEN_FAIL
//
// MessageText:
//
//  Unable to open driver %1. Error code %2.
//
#define EVENT_NBTSVC_DRV_OPEN_FAIL       0x00001145L

//
// MessageId: EVENT_NBTSVC_LINK_FAIL
//
// MessageText:
//
//  Unable to link driver %1 under driver %2. Error code %3.
//
#define EVENT_NBTSVC_LINK_FAIL           0x00001146L

//
// MessageId: EVENT_NBTSVC_UNLINK_FAIL
//
// MessageText:
//
//  Unable to unlink driver %1 from under driver %2.
//  Error code %3.
//
#define EVENT_NBTSVC_UNLINK_FAIL         0x00001147L

//
// MessageId: EVENT_NBTSVC_LINK_NACK_FAIL
//
// MessageText:
//
//  Unable to inform NBT of failure to link driver %1. Error code %2.
//
#define EVENT_NBTSVC_LINK_NACK_FAIL      0x00001148L

//
// MessageId: EVENT_NBTSVC_LINKREQ_FAIL
//
// MessageText:
//
//  Unable to communicate with the NBT driver. Error code %1.
//
#define EVENT_NBTSVC_LINKREQ_FAIL        0x00001149L

//
// MessageId: EVENT_NBTSVC_BAD_LINKREQ
//
// MessageText:
//
//  Received unknown request %1 from NBT.
//
#define EVENT_NBTSVC_BAD_LINKREQ         0x0000114AL

//
// MessageId: EVENT_NBTSVC_UNKNOWN_SERVICE
//
// MessageText:
//
//  Cannot locate %1 service for protocol %2 in the TCP/IP
//  network services database. The service could not be started.
//
#define EVENT_NBTSVC_UNKNOWN_SERVICE     0x0000114BL

//
// MessageId: EVENT_NBTSVC_NBT_CONFIG_FAIL
//
// MessageText:
//
//  Unable to configure NBT. Error code %1.
//  The service could not be started.
//
#define EVENT_NBTSVC_NBT_CONFIG_FAIL     0x0000114CL

//
// MessageId: EVENT_NBTSVC_LMHOST_SYNC_FAIL
//
// MessageText:
//
//  Unable to prime the NBT name cache from the LMHOSTS file.
//  Error code %1.
//
#define EVENT_NBTSVC_LMHOST_SYNC_FAIL    0x0000114DL



/////////////////////////////////////////////////////////////////////////
//
// Telnet Service Events
//
// Codes 4500 - 4599
//
/////////////////////////////////////////////////////////////////////////


//
// MessageId: EVENT_TELNET_SERVICE_NO_MEMORY
//
// MessageText:
//
//  Unable to allocate critical memory resources. The service failed to start.
//
#define EVENT_TELNET_SERVICE_NO_MEMORY   0x00001194L

//
// MessageId: EVENT_TELNET_SERVICE_STARTUP
//
// MessageText:
//
//  Startup failed to create critical resource: %1.
//
#define EVENT_TELNET_SERVICE_STARTUP     0x00001195L

//
// MessageId: EVENT_TELNET_SERVICE_SHUTDOWN
//
// MessageText:
//
//  Shut down failed to delete critical resource: %1.
//
#define EVENT_TELNET_SERVICE_SHUTDOWN    0x00001196L

//
// MessageId: EVENT_TELNET_SERVICE_RUNTIME
//
// MessageText:
//
//  Critical runtime service error at: %1.
//
#define EVENT_TELNET_SERVICE_RUNTIME     0x00001197L


/////////////////////////////////////////////////////////////////////////
//
// NDIS Environment Events
//
// Codes 5000 - 5099
//
/////////////////////////////////////////////////////////////////////////


//
// MessageId: EVENT_NDIS_RESOURCE_CONFLICT
//
// MessageText:
//
//  %2 : Has encountered a conflict in resources and could not load.
//
#define EVENT_NDIS_RESOURCE_CONFLICT     0xC0001388L

//
// MessageId: EVENT_NDIS_OUT_OF_RESOURCE
//
// MessageText:
//
//  %2 : Could not allocate the resources necessary for operation.
//
#define EVENT_NDIS_OUT_OF_RESOURCE       0xC0001389L

//
// MessageId: EVENT_NDIS_HARDWARE_FAILURE
//
// MessageText:
//
//  %2 : Has determined that the adapter is not functioning properly.
//
#define EVENT_NDIS_HARDWARE_FAILURE      0xC000138AL

//
// MessageId: EVENT_NDIS_ADAPTER_NOT_FOUND
//
// MessageText:
//
//  %2 : Could not find an adapter.
//
#define EVENT_NDIS_ADAPTER_NOT_FOUND     0xC000138BL

//
// MessageId: EVENT_NDIS_INTERRUPT_CONNECT
//
// MessageText:
//
//  %2 : Could not connect to the interrupt number supplied.
//
#define EVENT_NDIS_INTERRUPT_CONNECT     0xC000138CL

//
// MessageId: EVENT_NDIS_DRIVER_FAILURE
//
// MessageText:
//
//  %2 : Has encountered an internal error and has failed.
//
#define EVENT_NDIS_DRIVER_FAILURE        0xC000138DL

//
// MessageId: EVENT_NDIS_BAD_VERSION
//
// MessageText:
//
//  %2 : The version number is incorrect for this driver.
//
#define EVENT_NDIS_BAD_VERSION           0xC000138EL

//
// MessageId: EVENT_NDIS_TIMEOUT
//
// MessageText:
//
//  %2 : Timed out during an operation.
//
#define EVENT_NDIS_TIMEOUT               0x8000138FL

//
// MessageId: EVENT_NDIS_NETWORK_ADDRESS
//
// MessageText:
//
//  %2 : Has encountered an invalid network address.
//
#define EVENT_NDIS_NETWORK_ADDRESS       0xC0001390L

//
// MessageId: EVENT_NDIS_UNSUPPORTED_CONFIGURATION
//
// MessageText:
//
//  %2 : Does not support the configuration supplied.
//
#define EVENT_NDIS_UNSUPPORTED_CONFIGURATION 0xC0001391L

//
// MessageId: EVENT_NDIS_INVALID_VALUE_FROM_ADAPTER
//
// MessageText:
//
//  %2 : The adapter has returned an invalid value to the driver.
//
#define EVENT_NDIS_INVALID_VALUE_FROM_ADAPTER 0xC0001392L

//
// MessageId: EVENT_NDIS_MISSING_CONFIGURATION_PARAMETER
//
// MessageText:
//
//  %2 : A required parameter is missing from the Registry.
//
#define EVENT_NDIS_MISSING_CONFIGURATION_PARAMETER 0xC0001393L

//
// MessageId: EVENT_NDIS_BAD_IO_BASE_ADDRESS
//
// MessageText:
//
//  %2 : The I/O base address supplied does not match the jumpers on the adapter.
//
#define EVENT_NDIS_BAD_IO_BASE_ADDRESS   0xC0001394L

//
// MessageId: EVENT_NDIS_RECEIVE_SPACE_SMALL
//
// MessageText:
//
//  %2 : The adapter is configured such that the receive space is smaller than
//  the maximum packet size.  Some packets may be lost.
//
#define EVENT_NDIS_RECEIVE_SPACE_SMALL   0x40001395L

//
// MessageId: EVENT_NDIS_ADAPTER_DISABLED
//
// MessageText:
//
//  %2 : The adapter is disabled.  The driver cannot open the adapter.
//
#define EVENT_NDIS_ADAPTER_DISABLED      0x80001396L

//
// MessageId: EVENT_NDIS_IO_PORT_CONFLICT
//
// MessageText:
//
//  %2 : There is an I/O port conflict.
//
#define EVENT_NDIS_IO_PORT_CONFLICT      0x80001397L

//
// MessageId: EVENT_NDIS_PORT_OR_DMA_CONFLICT
//
// MessageText:
//
//  %2 : There is an I/O port or DMA channel conflict.
//
#define EVENT_NDIS_PORT_OR_DMA_CONFLICT  0x80001398L

//
// MessageId: EVENT_NDIS_MEMORY_CONFLICT
//
// MessageText:
//
//  %2 : There is a memory conflict at address 0x%3.
//
#define EVENT_NDIS_MEMORY_CONFLICT       0x80001399L

//
// MessageId: EVENT_NDIS_INTERRUPT_CONFLICT
//
// MessageText:
//
//  %2 : There is a interrupt conflict at interrupt number %3.
//
#define EVENT_NDIS_INTERRUPT_CONFLICT    0x8000139AL

//
// MessageId: EVENT_NDIS_DMA_CONFLICT
//
// MessageText:
//
//  %2 : There is a resource conflict at DMA channel %3.
//
#define EVENT_NDIS_DMA_CONFLICT          0x8000139BL


/////////////////////////////////////////////////////////////////////////
//
// General NT System Events
//
/////////////////////////////////////////////////////////////////////////

//
// Eventlog Events 6000 - 6999
//
//
// MessageId: EVENT_LOG_FULL
//
// MessageText:
//
//  The %1 log file is full.
//
#define EVENT_LOG_FULL                   0x80001770L

//
// MessageId: EVENT_LogFileNotOpened
//
// MessageText:
//
//  The %1 log file cannot be opened.
//
#define EVENT_LogFileNotOpened           0x80001771L

//
// MessageId: EVENT_LogFileCorrupt
//
// MessageText:
//
//  The %1 log file is corrupted and will be cleared.
//
#define EVENT_LogFileCorrupt             0x80001772L

//
// MessageId: EVENT_DefaultLogCorrupt
//
// MessageText:
//
//  The Application log file could not be opened.  %1 will be used as the default
//  log file.
//
#define EVENT_DefaultLogCorrupt          0x80001773L

//
// MessageId: EVENT_BadDriverPacket
//
// MessageText:
//
//  A driver packet received from the I/O subsystem was invalid.  The data is the
//  packet.
//
#define EVENT_BadDriverPacket            0x80001774L

//
// MessageId: EVENT_EventlogStarted
//
// MessageText:
//
//  The Event log service was started.
//
#define EVENT_EventlogStarted            0x80001775L

//
// MessageId: EVENT_EventlogStopped
//
// MessageText:
//
//  The Event log service was stopped.
//
#define EVENT_EventlogStopped            0x80001776L

//
// Service Controller Events 7000 - 7999
//
//
// MessageId: EVENT_SERVICE_START_FAILED
//
// MessageText:
//
//  The %1 service failed to start due to the following error: %n%2
//
#define EVENT_SERVICE_START_FAILED       0x80001B58L

//
// MessageId: EVENT_SERVICE_START_FAILED_II
//
// MessageText:
//
//  The %1 service depends on the %2 service which failed to start because of the following error: %n%3
//
#define EVENT_SERVICE_START_FAILED_II    0x80001B59L

//
// MessageId: EVENT_SERVICE_START_FAILED_GROUP
//
// MessageText:
//
//  The %1 service depends on the %2 group and no member of this group started.
//
#define EVENT_SERVICE_START_FAILED_GROUP 0x80001B5AL

//
// MessageId: EVENT_SERVICE_START_FAILED_NONE
//
// MessageText:
//
//  The %1 service depends on the following nonexistent service: %2
//
#define EVENT_SERVICE_START_FAILED_NONE  0x80001B5BL

//
// MessageId: EVENT_CALL_TO_FUNCTION_FAILED
//
// MessageText:
//
//  The %1 call failed with the following error: %n%2
//
#define EVENT_CALL_TO_FUNCTION_FAILED    0x80001B5DL

//
// MessageId: EVENT_CALL_TO_FUNCTION_FAILED_II
//
// MessageText:
//
//  The %1 call failed for %2 with the following error: %n%3
//
#define EVENT_CALL_TO_FUNCTION_FAILED_II 0x80001B5EL

//
// MessageId: EVENT_REVERTED_TO_LASTKNOWNGOOD
//
// MessageText:
//
//  The system reverted to its last known good configuration.  The system is restarting....
//
#define EVENT_REVERTED_TO_LASTKNOWNGOOD  0x80001B5FL

//
// MessageId: EVENT_BAD_ACCOUNT_NAME
//
// MessageText:
//
//  No backslash is in the account name.
//
#define EVENT_BAD_ACCOUNT_NAME           0x80001B60L

//
// MessageId: EVENT_CONNECTION_TIMEOUT
//
// MessageText:
//
//  Timeout (%1 milliseconds) waiting for service to connect.
//
#define EVENT_CONNECTION_TIMEOUT         0x80001B61L

//
// MessageId: EVENT_READFILE_TIMEOUT
//
// MessageText:
//
//  Timeout (%1 milliseconds) waiting for ReadFile.
//
#define EVENT_READFILE_TIMEOUT           0x80001B62L

//
// MessageId: EVENT_TRANSACT_TIMEOUT
//
// MessageText:
//
//  Timeout (%1 milliseconds) waiting for transaction response.
//
#define EVENT_TRANSACT_TIMEOUT           0x80001B63L

//
// MessageId: EVENT_TRANSACT_INVALID
//
// MessageText:
//
//  Message returned in transaction has incorrect size.
//
#define EVENT_TRANSACT_INVALID           0x80001B64L

//
// MessageId: EVENT_FIRST_LOGON_FAILED
//
// MessageText:
//
//  Logon attempt with current password failed with the following error: %n%1
//
#define EVENT_FIRST_LOGON_FAILED         0x80001B65L

//
// MessageId: EVENT_SECOND_LOGON_FAILED
//
// MessageText:
//
//  Second logon attempt with old password also failed with the following error: %n%1
//
#define EVENT_SECOND_LOGON_FAILED        0x80001B66L

//
// MessageId: EVENT_INVALID_DRIVER_DEPENDENCY
//
// MessageText:
//
//  Boot-start or system-start driver (%1) must not depend on a service.
//
#define EVENT_INVALID_DRIVER_DEPENDENCY  0x80001B67L

//
// MessageId: EVENT_BAD_SERVICE_STATE
//
// MessageText:
//
//  The %1 service has reported an invalid current state %2.
//
#define EVENT_BAD_SERVICE_STATE          0x80001B68L

//
// MessageId: EVENT_CIRCULAR_DEPENDENCY_DEMAND
//
// MessageText:
//
//  Detected circular dependencies demand starting %1.
//
#define EVENT_CIRCULAR_DEPENDENCY_DEMAND 0x80001B69L

//
// MessageId: EVENT_CIRCULAR_DEPENDENCY_AUTO
//
// MessageText:
//
//  Detected circular dependencies auto-starting services.
//
#define EVENT_CIRCULAR_DEPENDENCY_AUTO   0x80001B6AL

//
// MessageId: EVENT_DEPEND_ON_LATER_SERVICE
//
// MessageText:
//
//  Circular dependency: The %1 service depends on a service in a group which starts later.
//
#define EVENT_DEPEND_ON_LATER_SERVICE    0x80001B6BL

//
// MessageId: EVENT_DEPEND_ON_LATER_GROUP
//
// MessageText:
//
//  Circular dependency: The %1 service depends on a group which starts later.
//
#define EVENT_DEPEND_ON_LATER_GROUP      0x80001B6CL

//
// MessageId: EVENT_SEVERE_SERVICE_FAILED
//
// MessageText:
//
//  About to revert to the last known good configuration because the %1 service failed to start.
//
#define EVENT_SEVERE_SERVICE_FAILED      0x80001B6DL

//
// MessageId: EVENT_SERVICE_START_HUNG
//
// MessageText:
//
//  The %1 service hung on starting.
//
#define EVENT_SERVICE_START_HUNG         0x80001B6EL

//
// MessageId: EVENT_SERVICE_EXIT_FAILED
//
// MessageText:
//
//  The %1 service terminated with the following error: %n%2
//
#define EVENT_SERVICE_EXIT_FAILED        0x80001B6FL

//
// MessageId: EVENT_SERVICE_EXIT_FAILED_SPECIFIC
//
// MessageText:
//
//  The %1 service terminated with service-specific error %2.
//
#define EVENT_SERVICE_EXIT_FAILED_SPECIFIC 0x80001B70L

//
// MessageId: EVENT_SERVICE_START_AT_BOOT_FAILED
//
// MessageText:
//
//  At least one service or driver failed during system startup.  Use Event Viewer to examine the event log for details.
//
#define EVENT_SERVICE_START_AT_BOOT_FAILED 0x80001B71L

//
// MessageId: EVENT_BOOT_SYSTEM_DRIVERS_FAILED
//
// MessageText:
//
//  The following boot-start or system-start driver(s) failed to load: %1
//
#define EVENT_BOOT_SYSTEM_DRIVERS_FAILED 0x80001B72L

//
// MessageId: EVENT_RUNNING_LASTKNOWNGOOD
//
// MessageText:
//
//  Windows NT could not be started as configured.  A previous working configuration was used instead.
//
#define EVENT_RUNNING_LASTKNOWNGOOD      0x80001B73L

//
// MessageId: EVENT_TAKE_OWNERSHIP
//
// MessageText:
//
//  The %1 Registry key denied access to SYSTEM account programs so the Service Control Manager took ownership of the Registry key.
//
#define EVENT_TAKE_OWNERSHIP             0x80001B74L

//
// This Text is used as a title for the message box used to display
// MessageId 7027.  It is not an event or error message.
//
//
// MessageId: TITLE_SC_MESSAGE_BOX
//
// MessageText:
//
//  Service Control Manager %0
//
#define TITLE_SC_MESSAGE_BOX             0x80001B75L


/////////////////////////////////////////////////////////////////////////
//
// Lanman Bowser/Browser Events (8000-8999)
//
//
/////////////////////////////////////////////////////////////////////////


//
// MessageId: EVENT_BOWSER_OTHER_MASTER_ON_NET
//
// MessageText:
//
//  The master browser has received a server announcement from the computer %2
//  that believes that it is the master browser for the domain.  The master browser is
//  stopping.
//
#define EVENT_BOWSER_OTHER_MASTER_ON_NET 0xC0001F43L

//
// MessageId: EVENT_BOWSER_PROMOTED_WHILE_ALREADY_MASTER
//
// MessageText:
//
//  A request has been submitted to promote the computer to backup when it is already a
//  master browser.
//
#define EVENT_BOWSER_PROMOTED_WHILE_ALREADY_MASTER 0x80001F44L

//
// MessageId: EVENT_BOWSER_NON_MASTER_MASTER_ANNOUNCE
//
// MessageText:
//
//  The browser has received a server announcement indicating that the computer %2
//  is a master browser, but this computer is not a master browser.
//
#define EVENT_BOWSER_NON_MASTER_MASTER_ANNOUNCE 0x80001F45L

//
// MessageId: EVENT_BOWSER_ILLEGAL_DATAGRAM
//
// MessageText:
//
//  The browser has received an illegal datagram from the remote computer %2 to name %3 on transport %4.  The data is the datagram.
//
#define EVENT_BOWSER_ILLEGAL_DATAGRAM    0x80001F46L

//
// MessageId: EVENT_BROWSER_STATUS_BITS_UPDATE_FAILED
//
// MessageText:
//
//  The browser was unable to update the service status bits.  The data is the error.
//
#define EVENT_BROWSER_STATUS_BITS_UPDATE_FAILED 0xC0001F47L

//
// MessageId: EVENT_BROWSER_ROLE_CHANGE_FAILED
//
// MessageText:
//
//  The browser was unable to update its role.  The data is the error.
//
#define EVENT_BROWSER_ROLE_CHANGE_FAILED 0xC0001F48L

//
// MessageId: EVENT_BROWSER_MASTER_PROMOTION_FAILED
//
// MessageText:
//
//  The browser was unable to promote itself to master browser.  The computer that currently
//  believes it is the master browser is %1.
//
#define EVENT_BROWSER_MASTER_PROMOTION_FAILED 0xC0001F49L

//
// MessageId: EVENT_BOWSER_NAME_CONVERSION_FAILED
//
// MessageText:
//
//  The browser driver was unable to convert a character string to a unicode string.
//
#define EVENT_BOWSER_NAME_CONVERSION_FAILED 0xC0001F4AL

//
// MessageId: EVENT_BROWSER_OTHERDOMAIN_ADD_FAILED
//
// MessageText:
//
//  The browser was unable to add the configuration parameter %1.
//
#define EVENT_BROWSER_OTHERDOMAIN_ADD_FAILED 0xC0001F4BL

//
// MessageId: EVENT_BOWSER_ELECTION_RECEIVED
//
// MessageText:
//
//  The browser driver has received an election packet from computer %2 on network %3.  The data is the packet received.
//
#define EVENT_BOWSER_ELECTION_RECEIVED   0x00001F4CL

//
// MessageId: EVENT_BOWSER_ELECTION_SENT_GETBLIST_FAILED
//
// MessageText:
//
//  The browser driver has forced an election on network %2 because it was unable to find a master browser to retrieve a backup list on that network.
//
#define EVENT_BOWSER_ELECTION_SENT_GETBLIST_FAILED 0x40001F4DL

//
// MessageId: EVENT_BOWSER_ELECTION_SENT_FIND_MASTER_FAILED
//
// MessageText:
//
//  The browser driver has forced an election on network %2 because it was unable to find a master browser for that network.
//
#define EVENT_BOWSER_ELECTION_SENT_FIND_MASTER_FAILED 0x40001F4EL

//
// MessageId: EVENT_BROWSER_ELECTION_SENT_LANMAN_NT_STARTED
//
// MessageText:
//
//  The browser has forced an election on network %1 because a Windows NT Advanced Server (or domain master) browser is started.
//
#define EVENT_BROWSER_ELECTION_SENT_LANMAN_NT_STARTED 0x00001F4FL

//
// MessageId: EVENT_BOWSER_ILLEGAL_DATAGRAM_THRESHOLD
//
// MessageText:
//
//  The browser driver has received too many illegal datagrams from the remote computer %2 to name %3 on transport %4.  The data is the datagram.
//  No more events will be generated until the reset frequency has expired.
//
#define EVENT_BOWSER_ILLEGAL_DATAGRAM_THRESHOLD 0xC0001F50L

//
// MessageId: EVENT_BROWSER_DEPENDANT_SERVICE_FAILED
//
// MessageText:
//
//  The browser has failed to start because the dependent service %1 had invalid service status %2.
//  Status             Meaning
//    1              Service Stopped%n
//    2              Start Pending%n
//    3              Stop Pending%n
//    4              Running%n
//    5              Continue Pending%n
//    6              Pause Pending%n
//    7              Paused%n
//
#define EVENT_BROWSER_DEPENDANT_SERVICE_FAILED 0xC0001F51L

//
// MessageId: EVENT_BROWSER_MASTER_PROMOTION_FAILED_STOPPING
//
// MessageText:
//
//  The browser was unable to promote itself to master browser.  The browser will continue
//  to attempt to promote itself to the master browser, but will no longer log any events in the event log in Event Viewer.
//
#define EVENT_BROWSER_MASTER_PROMOTION_FAILED_STOPPING 0xC0001F53L

//
// MessageId: EVENT_BROWSER_MASTER_PROMOTION_FAILED_NO_MASTER
//
// MessageText:
//
//  The browser was unable to promote itself to master browser.  The computer that currently
//  believes it is the master browser is unknown.
//
#define EVENT_BROWSER_MASTER_PROMOTION_FAILED_NO_MASTER 0xC0001F54L

//
// MessageId: EVENT_BROWSER_SERVER_LIST_FAILED
//
// MessageText:
//
//  The browser was unable to retrieve a list of servers from the browser master %1 on the network %2.
//  The data is the error code.
//
#define EVENT_BROWSER_SERVER_LIST_FAILED 0x80001F55L

//
// MessageId: EVENT_BROWSER_DOMAIN_LIST_FAILED
//
// MessageText:
//
//  The browser was unable to retrieve a list of domains from the browser master %1 on the network %2.
//  The data is the error code.
//
#define EVENT_BROWSER_DOMAIN_LIST_FAILED 0x80001F56L

//
// MessageId: EVENT_BROWSER_ILLEGAL_CONFIG
//
// MessageText:
//
//  The value for the parameter %1 to the browser service was illegal.
//
#define EVENT_BROWSER_ILLEGAL_CONFIG     0x80001F57L

//
// MessageId: EVENT_BOWSER_OLD_BACKUP_FOUND
//
// MessageText:
//
//  The backup browser server %2 is out-of-date.  Consider upgrading this computer.
//
#define EVENT_BOWSER_OLD_BACKUP_FOUND    0x40001F58L

//
// MessageId: EVENT_BROWSER_SERVER_LIST_RETRIEVED
//
// MessageText:
//
//  The browser has retrieved a list of servers from remote computer %1 on transport %2.%n
//  There were %3 entries read, and %4 total entries.
//
#define EVENT_BROWSER_SERVER_LIST_RETRIEVED 0x00001F59L

//
// MessageId: EVENT_BROWSER_DOMAIN_LIST_RETRIEVED
//
// MessageText:
//
//  The browser has retrieved a list of domains from remote computer %1 on transport %2.%n
//  There were %3 entries read, and %4 total entries.
//
#define EVENT_BROWSER_DOMAIN_LIST_RETRIEVED 0x00001F5AL

//
// MessageId: EVENT_BOWSER_PDC_LOST_ELECTION
//
// MessageText:
//
//  The browser running on the Domain Controller has lost an election.  The computer that won the election is %2, on the transport %3.%n
//  The data contains the election version, election criteria, and remote computer time up, and the same information for
//  the current computer.
//
#define EVENT_BOWSER_PDC_LOST_ELECTION   0x40001F5BL

//
// MessageId: EVENT_BOWSER_NON_PDC_WON_ELECTION
//
// MessageText:
//
//  The browser running on this computer has won a browser election on network %2.
//  This computer is a member of a domain, so the Domain Controller should become the master
//  browser.
//
#define EVENT_BOWSER_NON_PDC_WON_ELECTION 0x40001F5CL

//
// MessageId: EVENT_BOWSER_CANT_READ_REGISTRY
//
// MessageText:
//
//  The browser driver was unable to initialize variables from the Registry.
//
#define EVENT_BOWSER_CANT_READ_REGISTRY  0x40001F5DL

//
// MessageId: EVENT_BOWSER_MAILSLOT_DATAGRAM_THRESHOLD_EXCEEDED
//
// MessageText:
//
//  The browser driver has discarded too many mailslot messages.
//
#define EVENT_BOWSER_MAILSLOT_DATAGRAM_THRESHOLD_EXCEEDED 0x40001F5EL

//
// MessageId: EVENT_BOWSER_GETBROWSERLIST_THRESHOLD_EXCEEDED
//
// MessageText:
//
//  The browser driver has discarded too many GetBrowserServerList requests.
//
#define EVENT_BOWSER_GETBROWSERLIST_THRESHOLD_EXCEEDED 0x40001F5FL

//
// MessageId: EVENT_BROWSER_BACKUP_STOPPED
//
// MessageText:
//
//  The browser service has failed to retrieve the backup list too many times on transport %1.
//  The backup browser is stopping.
//
#define EVENT_BROWSER_BACKUP_STOPPED     0xC0001F60L

//
// MessageId: EVENT_BROWSER_ELECTION_SENT_LANMAN_NT_STOPPED
//
// MessageText:
//
//  The browser has forced an election on network %1 because a master browser was stopped.
//
#define EVENT_BROWSER_ELECTION_SENT_LANMAN_NT_STOPPED 0x40001F61L

//
// MessageId: EVENT_BROWSER_GETBLIST_RECEIVED_NOT_MASTER
//
// MessageText:
//
//  The browser has received a GetBrowserServerList request when it is not the master browser.
//
#define EVENT_BROWSER_GETBLIST_RECEIVED_NOT_MASTER 0xC0001F62L

//
// MessageId: EVENT_BROWSER_ELECTION_SENT_ROLE_CHANGED
//
// MessageText:
//
//  The browser has forced an election on network %1 because the Domain Controller (or Server) has changed its role
//
#define EVENT_BROWSER_ELECTION_SENT_ROLE_CHANGED 0x40001F63L


/////////////////////////////////////////////////////////////////////////
//
// Transport Events (9000-9999)
//
//
/////////////////////////////////////////////////////////////////////////


//
// MessageId: EVENT_TRANSPORT_RESOURCE_POOL
//
// MessageText:
//
//  %2 could not allocate a resource of type %3 due to system resource problems.
//
#define EVENT_TRANSPORT_RESOURCE_POOL    0x80002329L

//
// MessageId: EVENT_TRANSPORT_RESOURCE_LIMIT
//
// MessageText:
//
//  %2 could not allocate a resource of type %3 due to its configured size of %4.
//
#define EVENT_TRANSPORT_RESOURCE_LIMIT   0x8000232AL

//
// MessageId: EVENT_TRANSPORT_RESOURCE_SPECIFIC
//
// MessageText:
//
//  %2 could not allocate a resource of type %3 due to a specifically configured limit of %4.
//
#define EVENT_TRANSPORT_RESOURCE_SPECIFIC 0x8000232BL

//
// MessageId: EVENT_TRANSPORT_REGISTER_FAILED
//
// MessageText:
//
//  %2 failed to register itself with the NDIS wrapper.
//
#define EVENT_TRANSPORT_REGISTER_FAILED  0xC000232CL

//
// MessageId: EVENT_TRANSPORT_BINDING_FAILED
//
// MessageText:
//
//  %2 failed to bind to adapter %3.
//
#define EVENT_TRANSPORT_BINDING_FAILED   0xC000232DL

//
// MessageId: EVENT_TRANSPORT_ADAPTER_NOT_FOUND
//
// MessageText:
//
//  %2 could not find adapter %3.
//
#define EVENT_TRANSPORT_ADAPTER_NOT_FOUND 0xC000232EL

//
// MessageId: EVENT_TRANSPORT_SET_OID_FAILED
//
// MessageText:
//
//  %2 failed while setting OID %3 on adapter %4.
//
#define EVENT_TRANSPORT_SET_OID_FAILED   0xC000232FL

//
// MessageId: EVENT_TRANSPORT_QUERY_OID_FAILED
//
// MessageText:
//
//  %2 failed while querying OID %3 on adapter %4.
//
#define EVENT_TRANSPORT_QUERY_OID_FAILED 0xC0002330L

//
// MessageId: EVENT_TRANSPORT_TRANSFER_DATA
//
// MessageText:
//
//  %2 could not transfer a packet from the adapter.  The packet was dropped.
//
#define EVENT_TRANSPORT_TRANSFER_DATA    0x40002331L

//
// MessageId: EVENT_TRANSPORT_TOO_MANY_LINKS
//
// MessageText:
//
//  %2 could not create a link to a remote computer.  Your computer has exceeded the number of connections it can make to that remote computer.
//
#define EVENT_TRANSPORT_TOO_MANY_LINKS   0x40002332L

//
// MessageId: EVENT_TRANSPORT_BAD_PROTOCOL
//
// MessageText:
//
//  %2 received an unexpected %3 packet from a remote computer.
//
#define EVENT_TRANSPORT_BAD_PROTOCOL     0x40002333L


#endif // _NETEVENT

