### EGA System 10 Pt.
egasys.fon:  egasys.fnt egasys.lnk egasys.rc makefile egasys.def \
             egasys.rc egasys.rcv
        ..\..\link4 @egasys.lnk
        rc -k egasys.rc egasys.fon
        del egasys.res
