#   Windows EGA & VGA driver makefile.
#
#   Requirements:
#
#       MASM 5.10 or greater with the environment variable INCLUDE set to
#	the directories containing CMACROS.INC, GDIDEFS.INC, and WINDEFS.INC.
#

#   Define the dependencies

inquire.obj:    inquire.asm
        masm -z-t-Ml-b63 inquire;

setmode.obj:   setmode.asm
        masm -z-t-Ml-b63 setmode;

enable.obj:   enable.asm
        masm -z-t-Ml-b63 enable;

disable.obj:   disable.asm
        masm -z-t-Ml-b63 disable;

chkstk.obj:   chkstk.asm
        masm -z-t-Ml-b63 chkstk;

cursors.obj:   cursors.asm
        masm -z-t-Ml-b63 cursors;

control.obj:   control.asm
        masm -z-t-Ml-b63 control;

fb.obj:   fb.asm
        masm -z-t-Ml-b63 fb;

charwdth.obj:   charwdth.asm fontseg.inc
        masm -z-t-Ml-b63 charwdth;

dither.obj:     dither.asm
        masm -z-t-Ml-b63 dither;

sswitch.obj:   sswitch.asm
        masm -z-t-Ml-b63 sswitch;

robject.obj:   robject.asm
        masm -z-t-Ml-b63 robject;

enum.obj:   enum.asm
        masm -z-t-Ml-b63 enum;

colorinf.obj:   colorinf.asm
        masm -z-t-Ml-b63 colorinf;

pixel.obj:   pixel.asm
        masm -z-t-Ml-b63 pixel;

cblt.obj:    cblt.asm                           \
		             genlocal.blt	\
		             genconst.blt	\
		             gendata.blt	\
		             ropdefs.blt	\
		             roptable.blt	\
			     clrlocal.blt	\
			     clrconst.blt	\
			     clrdata.blt	\
			     devlocal.blt	\
			     devconst.blt	\
			     devdata.blt
        masm -z-t-Ml-b63 cblt;

egainit.obj:   egainit.asm
        masm -z-t-Ml-b63 egainit;

output.obj:   output.asm
        masm -z-t-Ml-b63 output;

scanlr.obj:   scanlr.asm
        masm -z-t-Ml-b63 scanlr;

scanline.obj:   scanline.asm
        masm -z-t-Ml-b63 scanline;

polyline.obj:   polyline.asm polyline.inc plylocal.inc
        masm -z-t-Ml-b63 polyline;

polybitm.obj:   polybitm.asm polyline.inc plylocal.inc polyline.mac
        masm -z-t-Ml-b63 polybitm;

polystyl.obj:   polystyl.asm polyline.inc plylocal.inc polyline.mac
        masm -z-t-Ml-b63 polystyl;

strblt.obj:   strblt.asm strblt.inc fontseg.inc
        masm -z-t-Ml-b63 strblt;

buildstr.obj:   buildstr.asm strblt.inc fontseg.inc
        masm -z-t-Ml-b63 buildstr;

smartfix.obj:   smartfix.asm strblt.inc fontseg.inc
        masm -z-t-Ml-b63 smartfix;

smartpro.obj:   smartpro.asm strblt.inc fontseg.inc
        masm -z-t-Ml-b63 smartpro;

ssb.obj:   ssb.asm
        masm -z-t-Ml-b63 ssb;

bitblt.obj:                     bitblt.asm      \
		                genlocal.blt	\
		                genconst.blt	\
		                gendata.blt	\
		                ropdefs.blt	\
		                roptable.blt	\
			        clrlocal.blt	\
			        clrconst.blt	\
			        clrdata.blt	\
			        pdevice.blt	\
			        pattern.blt	\
			        copydev.blt	\
			        devlocal.blt	\
			        devconst.blt	\
			        devdata.blt	\
			        computey.blt	\
			        special.blt	\
			        exit.blt	\
				cursor.inc
        masm -z-t-Ml-b63 bitblt;

cursor.obj:      cursor.asm    egamemd.inc cursor.inc
        masm -z-t-Ml-b63 cursor;

egahibw.obj:   egahibw.asm
        masm -z-t-Ml-b63 egahibw;

3xswitch.obj:   3xswitch.asm
        masm -z-t-Ml-b63 3xswitch;

egahibw.drv: egahibw.def egahibw.lnk egahibw.res                \
		         egahibw.obj	       cursor.obj	\
		         bitblt.obj	       3xswitch.obj	\
		         cblt.obj 	       scanlr.obj	\
		         pixel.obj	       polystyl.obj	\
		         output.obj	       polyline.obj	\
		         polybitm.obj				\
		         strblt.obj	       buildstr.obj	\
		         smartfix.obj	       smartpro.obj	\
		         scanline.obj				\
		         ssb.obj	       egainit.obj	\
		         robject.obj	       colorinf.obj	\
		         enum.obj				\
		         control.obj           cursors.obj	\
		         inquire.obj           setmode.obj	\
                         dither.obj            disable.obj      \
		         enable.obj            chkstk.obj	\
		         charwdth.obj          fb.obj		\
                         sswitch.obj
    link4 @egahibw.lnk
    rc egahibw.res egahibw.drv
    copy egahibw.map display.map
    mapsym display    
    copy display.sym egahibw.sym
    erase display.sym
    erase display.map

