[Fresh Mirror]
number=6
title=Fresh Mirror
[Fresh Mirror0]
number=3
entry0=fat
entry1=hpfs
entry2=ntfs
[Fresh Mirror1]
number=1
entry0=300
[Fresh Mirror2]
number=1
entry0=AllPrimary
[Fresh Mirror3]
number=3
entry0=badsectors
entry1=orphan_reads
entry2=orphan_writes
[Fresh Mirror4]
number=1
entry0=AnyController
[Fresh Mirror5]
number=1
entry0=AnyController
[Stripe With Parity]
number=6
title=Stripe With Parity
[Stripe With Parity0]
number=3
entry0=fat
entry1=hpfs
entry2=ntfs
[Stripe With Parity1]
number=1
entry0=300
[Stripe With Parity2]
number=1
entry0=Mixed
[Stripe With Parity3]
number=3
entry0=badsectors
entry1=orphan_reads
entry2=orphan_writes
[Stripe With Parity4]
number=1
entry0=3
[Stripe With Parity5]
number=1
entry0=AnyController
[Heading]
number=2
entry0=Fresh Mirror
entry1=Stripe With Parity
