
@echo.
@if "%1"=="" goto usage
@if "%2"=="" goto usage
@if "%3"=="" goto usage
@if "%4"=="" goto usage

set startup=%3
set langfile=%4
set ft_version=1.0A

@rem
@rem del state.ini and config.ini which are generated by FTTEST.EXE
@rem and could be in conflict with our generic partloc.ini and parteloc.ini 
@rem
del /q state.ini
del /q config.ini

echo %2 >  n

comp n n < n > local.dat

querydsk

copy partloc.ini run.ini
scenario .\run.ini -l
copy create.dat createp.dat

copy parteloc.ini run.ini
scenario .\run.ini -l
copy create.dat createe.dat

mtrun local.pcd  /c %1_%2 /h

@rem
@rem Do a little cleanup
@rem

del local.dat 
del create.dat createe.dat createp.dat
del state.ini config.ini

goto end

:usage
@echo usage: local (word_for_yes) (word_for_no) (startup group) (langfile)
@echo example: local ja nien autostart german
@echo.

:end
