# Windows 2.1 Sample Keyboard Driver Makefile -- Common .OBJs:
#
# Requires MASM 5.10 or above.
#


date.obj:       date.asm
        masm -DOPTALL -DVKFUN -z-t-b63 date;

setspeed.obj:   setspeed.asm keyboard.inc
        masm -DOPTALL -DVKFUN -z-t-b63 setspeed;

datacom.obj:    datacom.asm keyboard.inc olikbd.inc        \
                vkwin.inc vkoem.inc equate.inc
        masm -DOPTALL -DVKFUN -z-t-b63 datacom;

enable.obj:     enable.asm vkwin.inc vkoem.inc keyboard.inc equate.inc
        masm -DOPTALL -DVKFUN -z-t-b63 enable;
