# Windows/286 WINOLDAP.MOD Makefile
#

#
# First, compile the C source files using the compiler and .H files
# supplied with the OEM Kit:
#

dde.obj:	dde.c		\
                dde.h
        cl -c -AS -Gw -W2 -Oas -Zpd -PLM dde.c

hothelp.obj:    hothelp.c
        cl -c -AS -Gw -W2 -Oas -Zpd -PLM hothelp.c

execmac.obj:   execmac.asm     \
                execmac.inc     
        masm50A -z-t-b63 execmac;

hotkey.obj:   hotkey.asm
        masm50A -z-t-b63 hotkey;

macro.obj:   macro.asm       \
                macro.inc     
        masm50A -z-t-b63 macro;

macromem.obj:   macromem.asm    \
                macro.inc        
        masm50A -z-t-b63 macromem;

menu.obj:   menu.asm        \
                menu.inc     
        masm50A -z-t-b63 menu;

menudisp.obj:   menudisp.asm    \
                menu.inc         
        masm50A -z-t-b63 menudisp;

menumem.obj:   menumem.asm     \
                menu.inc        
        masm50A -z-t-b63 menumem;

ttyclip.obj:   ttyclip.asm
        masm50A -z-t-b63 ttyclip; 

ttycopy.obj:	ttycopy.asm	\
		copyeq.inc
                masm50A -DMOUSE -z-t-b63 ttycopy.asm;

ttydos.obj:   ttydos.asm
        masm50A -z-t-b63 ttydos;

ttyems.obj:	ttyems.asm	\
		ems.inc 	\
		mac.inc
                masm50A -DEMS5 -z-t-b63 ttyems;

ttyexec.obj:	ttyexec.asm	\
		galloc.inc	\
		handle.inc
                masm50A -DSHORTER -z-t-b63 ttyexec;

ttyext.obj:	ttyext.asm	\
		ems.inc 	\
		ttyext.inc	\
		mac.inc
                masm50A -DEMS5 -z-t-b63 ttyext;

ttyfunc.obj:    ttyfunc.asm
        masm50A -z-t-b63 ttyfunc;

ttymem.obj:   ttymem.asm      \
                galloc.inc    \
		pdb.inc
        masm50A -z-t-b63 ttymem;

ttymouse.obj:   ttymouse.asm    \
                mouse.inc        
        masm50A -z-t-b63 ttymouse;

ttyoem.obj:   ttyoem.asm
        masm50A -z-t-b63 ttyoem;

ttypaint.obj:   ttypaint.asm
        masm50A -z-t-b63 ttypaint;

ttypaste.obj:   ttypaste.asm
        masm50A -z-t-b63 ttypaste;

ttysel.obj:   ttysel.asm
        masm50A -z-t-b63 ttysel;

ttyswap.obj:	ttyswap.asm	\
		ems.inc 	\
		galloc.inc	\
		partitio.inc
                masm50A -DEMS5 -z-t-b63 ttyswap;

ttysys.obj:   ttysys.asm      \
                ttysys.inc     
        masm50A -z-t-b63 ttysys;

ttytask.obj:	ttytask.asm	\
		galloc.inc	\
		partitio.inc
                masm50A -DMOUSE -R -z-t-b63 ttytask.asm;

ttywin.obj:   ttywin.asm      \
                windows.inc    
        masm50A -z-t-b63 ttywin;

#
# Now, create the resource for WINOLDAP:
#

winoldap.res:   winoldap.rc
        rc -r winoldap.rc winoldap.res

#
# Create WINOLDAP.MOD.  YOU MUST USE THE CUSTOM VERSION OF LINK4.EXE
# (LINK412.EXE) and MASM.EXE (MASM50A.EXE) WHICH ARE SUPPLIED ON THE 
# CUSTOM C COMPILER DISK PROVIDED WITH THE OEM KIT!!!!
#

winoldap.mod:	dde.obj 	\
		execmac.obj	\
		hotkey.obj	\
		hothelp.obj	\
		macro.obj	\
		macromem.obj	\
		menu.obj	\
		menudisp.obj	\
		menumem.obj	\
		ttyclip.obj	\
		ttycopy.obj	\
		ttydos.obj	\
		ttyems.obj	\
		ttyexec.obj	\
		ttyext.obj	\
		ttyfunc.obj	\
		ttymem.obj	\
		ttymouse.obj	\
		ttyoem.obj	\
		ttypaint.obj	\
		ttypaste.obj	\
		ttysel.obj	\
		ttyswap.obj	\
		ttysys.obj	\
		ttytask.obj	\
		ttywin.obj	\
		winoldap.def	\
		winoldap.lnk	\
		winoldap.rc	\
		winoldap.res
                link412 @winoldap.lnk
                mapsym winoldap
                rc -L winoldap.res winoldap.mod

