# Master make file.  Creates all necessary sub-components
# of the Immortal Klowns project, while allowing those components
# to be compiled w/VC

!IF ("$(CFG)" == "") || ("$(CFG)" == "Win32 Debug")
CFG=Win32 Debug
TARGDIR=windebug
TARGET=debug
!ELSE
TARGDIR=winrel
TARGET=retail
!ENDIF

default:
    cd ..\cgutil
    nmake $(MISC) /nologo $(TARGET)
    cd ..\iklowns
    nmake $(MISC) /nologo /f splash.mak CFG="$(CFG)"
    copy  $(TARGDIR)\splash.exe iklowns.exe
    nmake $(MISC) /nologo /f iklowns.mak CFG="$(CFG)"
        copy $(TARGDIR)\iklowns.ovl iklowns.ovl
    nmake $(MISC) /nologo /f cgkrusty.mak CFG="$(CFG)"
    copy $(TARGDIR)\krusty.dll krusty.dll
    nmake $(MISC) /nologo /f misc.mak CFG="$(CFG)"
    copy $(TARGDIR)\misc.dll misc.dll

all: debug retail

retail:
    nmake CFG="Win32 Release"

debug:
    nmake CFG="Win32 Debug"

