;****************************************************************************;
;*                                                                          *;
;*      (C) Copyright 1988,1989 by 3Com Corporation                         *;
;*                                                                          *;
;*      This IBM Token Ring NDIS Driver source is the property of Microsoft *;
;*      Corporation and is provided only as an example of an NDIS MAC       *;
;*      driver for use with Microsoft's OS/2 LAN Manager, DOS LAN Manager,  *;
;*      or LM/X products.                                                   *;
;*                                                                          *;
;****************************************************************************;

;------ INCLUDES.MAC --------------------------------------------------------;
;                                                                            ;
;       Include files used by all IBM Token Ring MAC source files.           ;
;                                                                            ;
;       09-21-88 Connery                                                     ;
;       Original version.                                                    ;
;                                                                            ;
;----------------------------------------------------------------------------;

;
; MACROS.MAC defines macros differently depending upon which cpus the code
; is required to execute on.  The following equates determine this.
;
IFDEF DOS
oa              equ     1                       ; support all processors
ELSE
o80286          equ     1                       ; 286 and 386 only
o80386          equ     1
ENDIF

IFDEF DOS
include dossdk.inc
ENDIF

include segdef.mac
include macros.mac
include mac.inc
include adapter.mac
include equ.mac
include struc.mac

                PRIV_CPU
