# Windows/286 Makefile for System and Terminal (OEM) fonts
#                                                         

fonts.obj:      fonts.asm
        masm -z-t-b63 fonts;

### CGA System Font
fontlo.fon:     SYS08CGA.FNT
        link4 fonts,fontlo.exe /align:16,,/NOD,fontlo
        rc fontlo.rc fontlo.exe
        command /c copy fontlo.exe fontlo.off
        command /c del  fontlo.exe
        command /c del  fontlo.res
        newfon fontlo.off fontlo.fon
        command /c del  fontlo.off


### EGA System Font
fonthi.fon:     SYS08EGA.FNT
        link4 fonts,fonthi.exe /align:16,,/NOD,fonthi
        rc fonthi.rc fonthi.exe
        command /c copy fonthi.exe fonthi.off
        command /c del  fonthi.exe
        command /c del  fonthi.res
        newfon fonthi.off fonthi.fon
        command /c del  fonthi.off


### VGA System Font
fontsq.fon:     SYS12VGA.FNT
        link4 fonts,fontsq.exe /align:16,,/NOD,fontsq
        rc fontsq.rc fontsq.exe
        command /c copy fontsq.exe fontsq.off
        command /c del  fontsq.exe
        command /c del  fontsq.res
        newfon fontsq.off fontsq.fon
        command /c del  fontsq.off


### 8514 System Font
8514.fon:       SYS20GAD.FNT
        link4 fonts,8514.exe /align:16,,/NOD,8514
        rc 8514.rc 8514.exe
        command /c copy 8514.exe 8514.off
        command /c del  8514.exe
        command /c del  8514.res
        newfon 8514.off 8514.fon
        command /c del  8514.off


### CGA OEM Font
fontlous.fon:   OEM08CGA.FNT
        link4 fonts,fontlous.exe /align:16,,/NOD,fontlous
        rc fontlous.rc fontlous.exe
        command /c copy fontlous.exe fontlous.off
        command /c del  fontlous.exe
        command /c del  fontlous.res
        newfon fontlous.off fontlous.fon
        command /c del  fontlous.off


### EGA OEM Font
fonthius.fon:   OEM08EGA.FNT
        link4 fonts,fonthius.exe /align:16,,/NOD,fonthius
        rc fonthius.rc fonthius.exe
        command /c copy fonthius.exe fonthius.off
        command /c del  fonthius.exe
        command /c del  fonthius.res
        newfon fonthius.off fonthius.fon
        command /c del  fonthius.off


### VGA OEM Font
fontsqus.fon:   OEM12VGA.FNT
        link4 fonts,fontsqus.exe /align:16,,/NOD,fontsqus
        rc fontsqus.rc fontsqus.exe
        command /c copy fontsqus.exe fontsqus.off
        command /c del  fontsqus.exe
        command /c del  fontsqus.res
        newfon fontsqus.off fontsqus.fon
        command /c del  fontsqus.off


### 8514 OEM Font
8514us.fon:     OEM20GAD.FNT
        link4 fonts,8514us.exe /align:16,,/NOD,8514us
        rc 8514us.rc 8514us.exe
        command /c copy 8514us.exe 8514us.off
        command /c del  8514us.exe
        command /c del  8514us.res
        newfon 8514us.off 8514us.fon
        command /c del  8514us.off
