DEVICE=SONIC

OBJS=\
$(BIN)\alloc.obj\
$(BIN)\interrup.obj\
$(BIN)\packet.obj\
$(BIN)\request.obj\
$(BIN)\send.obj\
$(BIN)\sonic.obj\
$(BIN)\transfer.obj\
$(BIN)\loopback.obj\
$(BIN)\ndisdev.obj

!include $(DDKROOT)\net\ndis3\src\ndis.mk
