#define IDC_APPLICATION      200
#define IDC_CANCEL           0
#define IDC_CONVBOX          202
#define IDC_EXECUTE_STRING   206
#define IDC_ITEM             203
#define IDC_ITEMBOX          204
#define IDC_OK               1
#define IDC_TOPIC            201
#define IDC_VALUE            205
#define IDM_ABOUT            109
#define IDM_ADVISE           102
#define IDM_CLEAR            107
#define IDM_INITIATE         100
#define IDM_PASTELINK        106
#define IDM_POKE             105
#define IDM_REQUEST          104
#define IDM_TERMINATE        101
#define IDM_UNADVISE         103
#define IDM_EXECUTE          108

