grabbers:  cga hercules egamono egacolor vgamono vgacolor 

cga:
	cd cgaherc\cga
	$(MAKE)
        cd ..\..

hercules:
	cd cgaherc\hercules
	$(MAKE)
        cd ..\..

egamono:
	cd ega\egamono
	$(MAKE)
        cd ..\..

egacolor:
	cd ega\egacolor
	$(MAKE)
        cd ..\..

vgamono:
	cd vga\vgamono
	$(MAKE)
        cd ..\..

vgacolor:
	cd vga\vgacolor
	$(MAKE)
        cd ..\..
