#===========================================================================;
#
#   AVIView -- AVI Viewer sample application
#
#############################################################################
#
#   THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
#   KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
#   PURPOSE.
#
#   Copyright (c) 1992, 1993  Microsoft Corporation.  All Rights Reserved.
#
#############################################################################
#
#---------------------------------------------------------------------------;
#
#   to make a NON-DEBUG build, type the following line:
#       nmake DEBUG=NO
#   just typing 'nmake' will build a DEBUG build
#
#
#===========================================================================;


#---------------------------------------------------------------------------;
# DEBUG information
#---------------------------------------------------------------------------;
!if "$(DEBUG)" == "NO"
COPT = 
MOPT = 
LOPT =
DEF  =
!else
COPT = -Zi -Fc
MOPT = -Zi -L
LOPT = /CO
DEF  = -DDEBUG
!endif


#-------------------------------------------------------------------------;
# Build Defaults
#-------------------------------------------------------------------------;
CC   = cl -c -nologo -AM -Zp -Od -G2s -GA $(DEF) $(COPT)
RC   = rc $(DEF) 
ASM  = masm -Mx  -t $(MOPT) $(DEF)
LINK = link $(LOPT)/NOD/NOE/MAP/NOPACKC/AL:16/ONERROR:NOEXE



#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;
#
#   Goals and objects
#
#
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;

NAME	= aviview
EXT	= exe
GOALS   = $(NAME).$(EXT)

OBJS	=$(NAME).obj audplay.obj aviball.obj muldivav.obj
LIBS	= libw mlibcew commdlg mmsystem vfw compobj


#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;
#
#   Build rules
#
#
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;
.c.obj:
	$(CC) $*.c

.asm.obj:
	$(ASM) $*;

.rc.res:
	$(RC) -r $*.rc


goal: $(GOALS)
        @echo ***** Finished building $(NAME).$(EXT) *****


$(NAME).$(EXT): $(OBJS) $(NAME).res $(NAME).def
	$(LINK) @<<
$(OBJS),
$(NAME).$(EXT),
$(NAME),
$(LIBS),
$(NAME).def
<<
        mapsym $(NAME).map
        $(RC) -t -31 $(NAME).res $(NAME).$(EXT)

aviview.obj: $$(@B).c aviview.h  
        $(CC) -NT _TEXT -Fo$@ $(@B).c 

audplay.obj: $$(@B).c audplay.h    
	$(CC) -NT _TEXT -Fo$@ $(@B).c

aviball.obj: $$(@B).c  
	$(CC) -NT BALL_TEXT -Fo$@ $(@B).c

muldivav.obj: $$(@B).c
	$(CC) -NT _TEXT -Fo$@ $(@B).c
 


clean:
	del $(NAME).$(EXT)
	del *.res
	del *.obj
	del *.map
	del *.sym
	del *.cod
	del *.pdb

copy:
	copy $(NAME).$(EXT) ..\..\bin
	copy $(NAME).sym ..\..\bin
