# Microsoft Windows SOUND Driver Makefile
#

sndcint1.obj: sndcint1.asm
        masm -z-t-b63 sndcint1;

sndcint2.obj: sndcint2.asm
        masm -z-t-b63 sndcint2;

sndcint3.obj: sndcint3.asm
        masm -z-t-b63 sndcint3;

mdd_play.obj: mdd_play.asm
        masm -z-t-b63 mdd_play;

mdd_core.obj: mdd_core.asm
        masm -z-t-b63 mdd_core;

mdd_beep.obj: mdd_beep.asm
        masm -z-t-b63 mdd_beep;

sound.drv: sound.def sndcint1.obj sndcint2.obj sndcint3.obj mdd_play.obj \
           mdd_core.obj mdd_beep.obj
    link4 @sound.lnk
    mapsym sound

