#   Microsoft Mouse Driver Makefile
#
#   Requirements:
#
#       MASM 5.10 or greater with the environment variable INCLUDE set to
#	the directories containing CMACROS.INC, and WINDEFS.INC.

mouse.obj:   mouse.asm mouse.inc
        masm -z-t-Ml-b63 mouse;

bus8255.obj:   bus8255.asm mouse.inc
        masm -z-t-Ml-b63 bus8255;

ser8250.obj:   ser8250.asm mouse.inc ins8250.inc
        masm -z-t-Ml-b63 ser8250;

inport.obj:   inport.asm mouse.inc inport.inc
        masm -z-t-Ml-b63 inport;

ps2.obj:   ps2.asm mouse.inc
        masm -z-t-Ml-b63 ps2;

int33h.obj:   int33h.asm mouse.inc
        masm -z-t-Ml-b63 int33h;

mouse.drv:	mouse.def mouse.obj ser8250.obj 	\
		inport.obj bus8255.obj ps2.obj int33h.obj
      link4 @mouse.lnk
      mapsym mouse
