//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by generic.rc
//
#define IDS_HELPMENUTEXT                1
#define IDM_NEW                         100
#define IDM_OPEN                        101
#define IDM_SAVE                        102
#define IDM_SAVEAS                      103
#define IDM_PRINT                       104
#define IDM_PRINTSETUP                  105
#define IDM_EXIT                        106
#define IDM_UNDO                        200
#define IDM_CUT                         201
#define IDM_COPY                        202
#define IDM_PASTE                       203
#define IDM_LINK                        204
#define IDM_LINKS                       205
#define IDM_HELPCONTENTS                300
#define IDM_HELPSEARCH                  301
#define IDM_HELPHELP                    302
#define IDM_ABOUT                       303
#define IDM_HELPTOPICS                  304
#define IDM_HELP_MENU                   305

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
