#************************************************************************
##**
##**  THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
##**  ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED
##**  TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR
##**  A PARTICULAR PURPOSE.
##**
##**  Copyright (C) 1992, 1993 Microsoft Corporation. All Rights Reserved.
##**
##**  makefile
##**
##**   to build a debug version:
##**       NMAKE
##**   to build a non debug version:
##**       NMAKE DEBUG=NO
##**
##**  DESCRIPTION:
##**     This will make the ACMAPP utility.
##**
##************************************************************************

NAME	=ACMAPP
EXT	=exe
GOALS	=$(NAME).$(EXT) $(NAME).sym
LIBS	=libw commdlg shell mmsystem mlibcew
OBJ1    =aadrvs.obj aafile.obj aainit.obj aaplyrec.obj aaprops.obj aasysinf.obj
OBJ2    =acmapp.obj acmthunk.obj debug.obj waveio.obj tlb.obj muldiv32.obj
OBJ3	=aawavdev.obj aachoose.obj
OBJS	=$(OBJ1) $(OBJ2) $(OBJ3)

!if "$(DEBUG)" == "NO"

LOPT	=
COPT	=
AOPT	=

!else

LOPT	=/CO /LI 
COPT	=-Zid -Fc -DDEBUG
AOPT	=-Zi -Fl -Sc -DDEBUG
ROPT	=-v -DDEBUG

!endif

CC	=cl -nologo -c -W3 -AM -GA3s -Ox -Z7p -DWIN16 -DWIN31 -DSTRICT $(COPT)
LINK	=link /NOLOGO /NOPACKC/MAP/NOE/NOD/AL:16/ONERROR:NOEXE $(LOPT)
ASM	=ml -nologo -c $(AOPT)
RC	=rc -DWIN16 -DWIN31 -DSTRICT $(ROPT)


.c.obj:
	$(CC) $*.c

.rc.res:
	$(RC) -r -v -z $*.rc

#
#  Explicit Rules
#

goal: $(GOALS)

$(NAME).$(EXT) $(NAME).map: $(OBJS) acmapp.res acmapp16.def
	$(LINK) @<<
	$(OBJS),
	$*.$(EXT),
	$*.map,
	$(LIBS),
	acmapp16.def
<<
	$(RC) -31 acmapp.res $*.$(EXT)

$(NAME).sym:	$$(@R).map
	mapsym  $*.map

#
#  Dependencies
#
#appinit.obj: $*.c acmapp.h appport.h debug.h
#	$(CC) -NT INIT_TEXT $*.c

aadrvs.obj: $*.c acmapp.h appport.h debug.h tlb.h
	$(CC) -NT ACMAPP_TEXT $*.c

aafile.obj: $*.c acmapp.h appport.h debug.h waveio.h
	$(CC) -NT ACMAPP_TEXT $*.c

aainit.obj: $*.c acmapp.h appport.h debug.h
	$(CC) -NT ACMAPP_TEXT $*.c

aaplyrec.obj: $*.c acmapp.h appport.h debug.h
	$(CC) -NT ACMAPP_TEXT $*.c

aaprops.obj: $*.c acmapp.h appport.h debug.h
	$(CC) -NT ACMAPP_TEXT $*.c

aasysinf.obj: $*.c acmapp.h appport.h debug.h
	$(CC) -NT ACMAPP_TEXT $*.c

aawavdev.obj: $*.c acmapp.h 
	$(CC) -NT ACMAPP_TEXT $*.c

aachoose.obj: $*.c acmapp.h 
	$(CC) -NT ACMAPP_TEXT $*.c

acmapp.obj: $*.c acmapp.h appport.h debug.h
	$(CC) -NT ACMAPP_TEXT $*.c

acmthunk.obj: $*.c 
	$(CC) -NT ACMAPP_TEXT $*.c

appinit.obj: $*.c acmapp.h appport.h debug.h
	$(CC) -NT _TEXT $*.c

debug.obj:  $*.c debug.h
	$(CC) -NT _TEXT $*.c

waveio.obj: $*.c appport.h debug.h waveio.h
	$(CC) -NT ACMAPP_TEXT $*.c

tlb.obj: $*.c appport.h debug.h tlb.h
	$(CC) -NT _TEXT $*.c

muldiv32.obj: $*.c muldiv32.h
	$(CC) -NT _TEXT $*.c

#
#  Clean up
#

clean:
            -@del *.obj
            -@del *.cod
            -@del $(NAME).$(EXT)
            -@del *.res
            -@del $(NAME).map
            -@del $(NAME).sym

copy:	
	copy $(NAME).$(EXT) ..\..\bin
	copy $(NAME).sym ..\..\bin
		