FILES = reg01z.asm reg02z.asm reg03z.asm reg04z.asm \
        reg05z.asm reg06z.asm reg07z.asm reg08z.asm \
        reg09z.asm reg0Az.asm reg0Bz.asm reg0Cz.asm \
        reg0Dz.asm reg0Ez.asm reg0Fz.asm reg10z.asm \
        reg11z.asm reg12z.asm

!include ..\local.mk

