### VGA System 10 Pt.
vgasys.fon:  vgasys.fnt vgasys.lnk vgasys.rc makefile vgasys.def \
             vgasys.rc vgasys.rcv
        ..\..\link4 @vgasys.lnk
        rc -k vgasys.rc vgasys.fon
        del vgasys.res
