### 8514sys System 10 Pt.
8514sys.fon:  8514sys.fnt 8514sys.lnk 8514sys.rc makefile 8514sys.def \
              8514sys.rc 8514sys.rcv
        ..\..\link4 @8514sys.lnk
        rc -k 8514sys.rc 8514sys.fon
        del 8514sys.res
