# Windows/286 Version 2.1 Sample Color Printer Driver
#
# Please note: This driver does not build to the IBMCOLOR.DRV included in
#              the Windows/286 Version 2.1 Retail Kit.  It is intended only
#              as a sample color printer driver.  Remember to copy DMCOLOR.LIB
#              from the \PRINTERS\COLOR directory on this disk before linking.
#                                                                             

ctofnt.obj: ctofnt.c
        cl -c -Zep -DLINT_ARGS ctofnt.c

ocr_b10.fnt: ocr_b10.c
        cl -c -Zep ocr_b10.c
        link4 ctofnt ocr_b10;
        ctofnt
        del ocr_b10.obj
        del ctofnt.exe

ocr_b5.fnt: ocr_b5.c
        cl -c -Zep ocr_b5.c
        link4 ctofnt ocr_b5;
        ctofnt
        del ocr_b5.obj
        del ctofnt.exe

ibmcolor.res:  ibmcolor.rc ocr_b5.fnt ocr_b10.fnt
    rc -r ibmcolor.rc

epson.obj:   epson.asm  epson.inc
    masm -DR140x84 -DWIDE_PG_SUPPORT epson.asm;

reset.obj:   reset.c
    cl -u -d -c -Asnw -PLM -Gsw -Oas -Zpe -I. -NT _TEXT reset.c

physical.obj:     physical.c
    cl -u -d -c -Asnw -PLM -Gsw -Oas -Zpe -I.  -NT _TEXT physical.c

stubs.obj:     stubs.c
    cl -u -d -c -Asnw -PLM -Gsw -Oas -Zpe -I. -NT _TEXT stubs.c

devmode.obj:    devmode.c
    cl -u -d -c -Asnw -PLM -Gsw -Oas -Zpe -I.  -NT _CHAR devmode.c

control.obj:    control.c
    cl -u -d -c -Asnw -PLM -Gsw -Oas -Zpe -I. -NT _TEXT control.c

realize.obj:  realize.c
    cl -u -d -c -Alnw -PLM -Gsw -Oas -Zpe -I. -NT _CHAR realize.c

chphys.obj:     chphys.c chp1.c
    cl -u -d -c -Alnw -PLM -Gsw -Oas -Zpe -I. -NT _CHAR chphys.c

data.obj: data.c trans.dat  control.dat
    cl -u -d -c -Asnw -PLM -Gsw -Oas -Zpe -I. -NT _CHAR data.c

ibmcolor.exe:   ibmcolor.lnk ibmcolor.def epson.obj devmode.obj \
                physical.obj stubs.obj control.obj reset.obj realize.obj \
                chphys.obj data.obj
    link4 @ibmcolor.lnk
    mapsym ibmcolor

ibmcolor.drv:   ibmcolor.exe ibmcolor.res
    rc ibmcolor.res
    command /c copy ibmcolor.exe ibmcolor.drv
    command /c del ibmcolor.exe
