#############################################################################
#
#   THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
#   KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
#   PURPOSE.
#
#   Copyright (c) 1992, 1993  Microsoft Corporation.  All Rights Reserved.
#
#############################################################################
#
#   MAKEFILE
#
#   constructs the DIB Sequence File Handler
#
#   to build a debug version:
#       NMAKE
#   to build a non debug version:
#       NMAKE DEBUG=NO
#
############################################################################

NAME	=dseqfile
DEFFILE	=$(NAME).def


!if "$(DEBUG)" == "NO"

DEF = 
CC  = cl -c -nologo -W3 -ASw -G2s -GA -GEd -DWINDLL -Zdp -Oxws $(DEF)
LINK= link /L /MAP /NOPACKCODE /NOE /NOD /ONERROR:NOEXE
LIBMAN = lib /NOE

!else

DEF   = -DDEBUG 
MASMOPT = -Zi -DDEBUG
CC  = cl -c -nologo -W3 -ASw -G2s -GA -GEd -DWINDLL -Zdp -Oxws -Zid $(DEF)
LINK	= link /L /MAP /NOPACKCODE /NOE /NOD /CO /LI /ONERROR:NOEXE
LIBMAN = lib /NOE

!endif



OBJ1	=factory.obj $(NAME).obj 

OBJ    = $(OBJ1)
LIBS	=libw sdllcew shell compobj mmsystem


.cpp.obj:
	$(CC) $*.cpp

###################### goal ######################

goal:  $(NAME).dll


##################################################

$(NAME).dll $(NAME).map: $(OBJ) $(NAME).res $(DEFFILE)
   $(LINK) @<<
	$(OBJ),
	$(NAME).dll,
	$(NAME),
	$(LIBS),
	$(NAME).def
<<
        rc -t -31 $(NAME).res $(NAME).dll
!if "$(DEBUG)" != "NO"
	cvpack -p $(NAME).dll
!endif
   mapsym $(NAME).map


$(NAME).res: handler.rc 
	rc -r $(DEF) -fo$(NAME).res handler.rc

handler.rc:  handler.h


##################### clean ######################

clean:
	del $(NAME).dll
	del *.obj
	del *.res
	del *.map
	del *.sym

##################### copy #######################
copy:
	copy $(NAME).dll ..\..\bin
	copy $(NAME).sym ..\..\bin


##################### depend #####################

$(NAME).obj: $(NAME).cpp handler.h 
$(NAME).cpp: handler.h 
factory.obj: factory.cpp handler.h
$(NAME).res: handler.rc
handler.rc: handler.h

# END Dependencies 
