
/*---------------------------------------------------------------------
|
| MovPlay.h - Movie player include file
|
+-------------------------------------------------------------------*/
/**************************************************************************
 *
 *  THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
 *  KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
 *  PURPOSE.
 *
 *  Copyright (c) 1992, 1993  Microsoft Corporation.  All Rights Reserved.
 * 
 **************************************************************************/

/* constants */
#define BUFFER_LENGTH  256

/* Menu items */
/* File menu */
#define IDM_OPEN   1
#define IDM_CLOSE  2
#define IDM_EXIT   3
#define IDM_ANOTHER 4

/* Movie menu */
#define IDM_PLAY   10
#define IDM_HOME   11
#define IDM_END    12
#define IDM_STEP   13
#define IDM_RSTEP  14
#define IDM_RPLAY  15

