####
# makefile - Makefile for Microsoft Visual C++ Run-Time Libraries
#
#   Copyright (c) 1993-1995, Microsoft Corporation. All rights reserved.
#
# Purpose:
#   This makefile builds the Visual C++ run-time release libraries.
#   Just type NMAKE in the \MSDEV\CRT\SRC directory to build all target
#   libraries.
#
###############################################################################

#
# The name of the user-generated C/C++ Run-Time Library DLL and
# imports library can be set here.  Names beginning with MSVC*
# may not be used as these are reserved for use by Microsoft.
# The names shown here are samples and are for information only.
#
RETAIL_DLL_NAME=_sample_
RETAIL_LIB_NAME=_sample_
DEBUG_DLL_NAME=_sampld_
DEBUG_LIB_NAME=_sampld_
#
POST_BLD=1

# If your MSVC++ 4.0 installation is not in \MSDEV on the current drive,
# set the environment variable V4TOOLS to point to the main directory
# of your installation.  (For example, "set V4TOOLS=C:\MSDEV".)

!if "$(V4TOOLS)"==""
V4TOOLS=\MSDEV
!endif


#
# Directories, Tools and Misc Definitions:
#
###############################################################################

#
# Determine target CPU, defaulting to same as host CPU.
#
###############################################################################

!if "$(PROCESSOR_ARCHITECTURE)"=="x86"
TARGET_CPU = i386
CPUDIR = intel
PREFIX=_
!elseif "$(PROCESSOR_ARCHITECTURE)"=="ALPHA"
TARGET_CPU = ALPHA
CPUDIR = alpha
PREFIX=
!elseif "$(PROCESSOR_ARCHITECTURE)"=="MIPS"
TARGET_CPU = mips
CPUDIR = mips
PREFIX=
!elseif "$(PROCESSOR_ARCHITECTURE)"=="PPC"
TARGET_CPU = PPC
CPUDIR = ppc
PREFIX=
!elseif "$(PROCESSOR_ARCHITECTURE)"=="M68K"
TARGET_CPU = M68K
CPUDIR = m68k
PREFIX=_
OS=MAC
!elseif "$(PROCESSOR_ARCHITECTURE)"=="PMAC"
TARGET_CPU = PMAC
CPUDIR = mppc
PREFIX=_
OS=MAC
!else
!error makefile: unknown host CPU
!endif

# Build WINHEAP version of heap manager, except for MAC targets

!if "$(TARGET_CPU)" != "PMAC" && "$(TARGET_CPU)" != "M68K"
WINHEAP = YES
!else
WINHEAP = NO
!endif

SOURCE_OBJS = $(SOURCE_OBJS_RAW:*=*_obj)
SOURCE_OBJS_DLL = $(SOURCE_OBJS_RAW_DLL:*=*_obj)

# Source directories:
#
# These are the directories in which to run NMAKE to update the source
# objects and libraries they provide.  Note that there are slight
# differences between the ST/MT models and the DLL/DLS models.
#
# The dependencies directory list DEP_DIRS is the union of the MAKE_DIRS
# and MAKE_DIRS_DLL lists.
#
# In order to allow for auto source library calculation, each directory
# name must be preceded by a tilde (~) and followed by an asterisk (*).

!if "$(BLD_LIB)"==""
BLD_LIB=0
!endif
!if "$(BLD_OBJ)"==""
BLD_OBJ=0
!endif

PRE_BLD=0

MAKE_DIRS = .

MAKE_DIRS_DLL = .

DEP_DIRS = .

TCMAPLIB_DIR = $(CPUDIR)

TCMAPDLLLIB_DIR = $(CPUDIR)

SDKNAMESLIB_DIR = $(CPUDIR)


# Source Objects: These are the objects and/or libraries which constitute
# the statically linked library flavors (LIBC.LIB and LIBCMT.LIB).

SOURCE_OBJS_RAW = \
 build\$(CPUDIR)\*\convert.lib \
!if "$(TARGET_CPU)"!="M68K" && "$(TARGET_CPU)"!="PMAC"
 build\$(CPUDIR)\*\direct.lib \
!endif
 build\$(CPUDIR)\*\dos.lib \
 build\$(CPUDIR)\*\eh.lib \
 build\$(CPUDIR)\*\exec.lib \
 build\$(CPUDIR)\*\heap.lib \
!if "$(TARGET_CPU)"!="ALPHA" && "$(TARGET_CPU)"!="M68K" && "$(TARGET_CPU)"!="PMAC"
 build\$(CPUDIR)\*\helper.lib \
!endif
 build\$(CPUDIR)\*\iostream.lib \
 build\$(CPUDIR)\*\lowio.lib \
 build\$(CPUDIR)\*\mbstring.lib \
 build\$(CPUDIR)\*\misc.lib \
 build\$(CPUDIR)\*\startup.lib \
 build\$(CPUDIR)\*\stdio.lib \
 build\$(CPUDIR)\*\string.lib \
 $(TCMAPLIB_DIR)\tcmap.lib \
 build\$(CPUDIR)\*\time.lib \
 build\$(CPUDIR)\*\conv.lib \
 build\$(CPUDIR)\*\tran.lib

# Source Objects: These are the objects and/or libraries which constitute
# the dynamically linked library flavor (MSVCRTx0.DLL).

SOURCE_OBJS_RAW_DLL = \
!if "$(TARGET_CPU)"!="M68K" && "$(TARGET_CPU)"!="PMAC"
 build\$(CPUDIR)\*\_setargv.obj \
 build\$(CPUDIR)\*\_wstargv.obj \
 build\$(CPUDIR)\*\chkstk.obj \
 build\$(CPUDIR)\*\crt0dat.obj \
 build\$(CPUDIR)\*\crt0fp.obj \
 build\$(CPUDIR)\*\crt0init.obj \
 build\$(CPUDIR)\*\crt0msg.obj \
 build\$(CPUDIR)\*\crtlib.obj \
 build\$(CPUDIR)\*\mlock.obj \
 build\$(CPUDIR)\*\stdargv.obj \
 build\$(CPUDIR)\*\stdenvp.obj \
 build\$(CPUDIR)\*\thread.obj \
 build\$(CPUDIR)\*\threadex.obj \
 build\$(CPUDIR)\*\tidtable.obj \
 build\$(CPUDIR)\*\wild.obj \
 build\$(CPUDIR)\*\wstdargv.obj \
 build\$(CPUDIR)\*\wstdenvp.obj \
 build\$(CPUDIR)\*\wwild.obj \
!endif
!if "$(TARGET_CPU)"=="i386"
 build\$(CPUDIR)\*\fp8.obj \
!endif
 build\$(CPUDIR)\*\convert.lib \
!if "$(TARGET_CPU)"!="M68K" && "$(TARGET_CPU)"!="PMAC"
 build\$(CPUDIR)\*\direct.lib \
!endif
 build\$(CPUDIR)\*\dos.lib \
 build\$(CPUDIR)\*\eh.lib \
 build\$(CPUDIR)\*\exec.lib \
 build\$(CPUDIR)\*\heap.lib \
!if "$(TARGET_CPU)"!="ALPHA" && "$(TARGET_CPU)"!="M68K" && "$(TARGET_CPU)"!="PMAC"
 build\$(CPUDIR)\*\helper.lib \
!endif
 build\$(CPUDIR)\*\iostream.lib \
 build\$(CPUDIR)\*\lowio.lib \
 build\$(CPUDIR)\*\mbstring.lib \
 build\$(CPUDIR)\*\misc.lib \
!if "$(TARGET_CPU)"=="PMAC"
 build\$(CPUDIR)\*\amsg.obj \
 build\$(CPUDIR)\*\chkstk.obj \
 build\$(CPUDIR)\*\crt0dat.obj \
 build\$(CPUDIR)\*\crt0fp.obj \
 build\$(CPUDIR)\*\crt0msg.obj \
 build\$(CPUDIR)\*\crtexit.obj \
 build\$(CPUDIR)\*\dllcrt0.obj \
 build\$(CPUDIR)\*\dllmain.obj \
 build\$(CPUDIR)\*\dllexit.obj \
 build\$(CPUDIR)\*\init.obj \
 build\$(CPUDIR)\*\libcinfo.obj \
 build\$(CPUDIR)\*\qd.obj \
 build\$(CPUDIR)\*\shellrtn.obj \
 build\$(CPUDIR)\*\sp.obj \
!endif
 build\$(CPUDIR)\*\stdio.lib \
 build\$(CPUDIR)\*\string.lib \
 build\$(CPUDIR)\*\time.lib \
 build\$(CPUDIR)\*\conv.lib \
 build\$(CPUDIR)\*\tran.lib


UPDATE_MSG = *** Updating Component Objects ***

#
# Define names for the primary targets of this makefile.
#
###############################################################################

!if "$(IFLAG)"==""
IFLAG=-i
!else
IFLAG=
!endif

!if "$(CRT_RELDIR)"==""
CRT_RELDIR = build
!endif
RELDIR_CPU=$(CRT_RELDIR)\$(CPUDIR)
DEFFILE_DIR=$(CPUDIR)

#
# Tools:
#

!if "$(VERBOSE)"!="1"
LINKER=link -nologo
LINKLIB=link -lib -nologo
!else
LINKER=link
LINKLIB=link -lib
!endif


!if "$(TARGET_CPU)"!="M68K" && "$(TARGET_CPU)"!="PMAC"
COMMON_DEFS=-D_MBCS -D_MB_MAP_DIRECT -D_CRTBLD
!if "$(WINHEAP)" == "YES"
COMMON_DEFS=$(COMMON_DEFS) -DWINHEAP
!endif
!endif

!if "$(TARGET_CPU)"=="mips"
#
# NT headers require _MIPS_ to be defined for mips
#
COMMON_DEFS=$(COMMON_DEFS) -D_MIPS_
!endif

!if "$(TARGET_CPU)"=="PPC"
#
# NT headers require _PPC_ to be defined for PowerPC
#
COMMON_DEFS=$(COMMON_DEFS) -D_PPC_
!endif

!if "$(TARGET_CPU)"!="M68K" && "$(TARGET_CPU)"!="PMAC"
WINDOWS_H_DEFS=-DWIN32_LEAN_AND_MEAN -DNOSERVICE

CC_OPTS_BASE=-c -nologo -Zelp8 -W3 -WX -GFy -DWIN32

!if "$(TARGET_CPU)"=="ALPHA"
CC_OPTS_BASE=$(CC_OPTS_BASE) -Gi-
AS_OPTS=-nologo -D_WIN32 -DWIN32
!elseif "$(TARGET_CPU)"=="i386"
CC_OPTS_BASE=$(CC_OPTS_BASE) -GB -Gi-
AS_OPTS=-c -nologo -coff -Cx -Zm -DQUIET -D?QUIET -Di386 -D_WIN32 -DWIN32
!elseif "$(TARGET_CPU)"=="PPC"
AS_OPTS=
!else
CC_OPTS_BASE=$(CC_OPTS_BASE) -Gi-
AS_OPTS=-c -nologo -D_WIN32 -DWIN32
!endif

CC_OPTS=$(CC_OPTS_BASE) $(WINDOWS_H_DEFS)
!endif

!if "$(TARGET_CPU)"=="M68K" || "$(TARGET_CPU)"=="PMAC"
COMMON_DEFS=-D_MBCS -D_MB_MAP_DIRECT -D_CRTBLD
CC_OPTS_BASE=-c -nologo -W3 -WX -Zl
!if "$(TARGET_CPU)"=="PMAC"
CC_OPTS_BASE=$(CC_OPTS_BASE) -Zp2
AS_OPTS=-c -nologo
!else
AS_OPTS=
!endif
CC_OPTS=$(CC_OPTS_BASE)

!endif

!if "$(TARGET_CPU)"!="M68K"

ST_DEFINES=$(COMMON_DEFS)
MT_DEFINES=$(ST_DEFINES) -D_MT
DLL_DEFINES=$(MT_DEFINES) -DCRTDLL
DLS_DEFINES=$(DLL_DEFINES) -DDLL_FOR_WIN32S


RC_OPTS=-l 409 -r
RC_DEFS=$(COMMON_DEFS) $(WINDOWS_H_DEFS)
RC_INCS=-I$(V4TOOLS)\include
PDBDIR_CPU              = $(RELDIR_CPU)

RELEASE_LIBCST          = $(RELDIR_CPU)\libc.lib
RELEASE_LIBCMT          = $(RELDIR_CPU)\libcmt.lib
RELEASE_DLL             = $(RELDIR_CPU)\$(RETAIL_DLL_NAME).dll
RELEASE_IMPLIB_DLL      = $(RELDIR_CPU)\$(RETAIL_LIB_NAME).lib
RELEASE_OLDNAMES        = $(RELDIR_CPU)\oldnames.lib
!if "$(TARGET_CPU)"=="i386"
RELEASE_DLS             = $(RELDIR_CPU)\$(RETAIL_DLL_NAME).dls
!else
RELEASE_DLS             =
!endif

RELEASE_LIBCST_PDB      = $(PDBDIR_CPU)\libc.pdb
RELEASE_LIBCMT_PDB      = $(PDBDIR_CPU)\libcmt.pdb
RELEASE_DLL_PDB         = $(PDBDIR_CPU)\$(RETAIL_LIB_NAME).pdb
RELEASE_DLS_PDB         = $(PDBDIR_CPU)\$(RETAIL_LIB_NAME).pds


RELEASE_LIBCST_DBG      = $(RELDIR_CPU)\libcd.lib
RELEASE_LIBCMT_DBG      = $(RELDIR_CPU)\libcmtd.lib
RELEASE_DLL_DBG         = $(RELDIR_CPU)\$(DEBUG_DLL_NAME).dll
RELEASE_IMPLIB_DLL_DBG  = $(RELDIR_CPU)\$(DEBUG_LIB_NAME).lib
!if "$(TARGET_CPU)"=="i386"
RELEASE_DLS_DBG         = $(RELDIR_CPU)\$(DEBUG_DLL_NAME).dls
!else
RELEASE_DLS_DBG         =
!endif

RELEASE_LIBCST_DBG_PDB  = $(PDBDIR_CPU)\libcd.pdb
RELEASE_LIBCMT_DBG_PDB  = $(PDBDIR_CPU)\libcmtd.pdb
RELEASE_DLL_DBG_PDB     = $(PDBDIR_CPU)\$(DEBUG_LIB_NAME).pdb
RELEASE_DLS_DBG_PDB     = $(PDBDIR_CPU)\$(DEBUG_LIB_NAME).pds

FD_REL_ST=-Fd$(RELEASE_LIBCST_PDB)
FD_REL_MT=-Fd$(RELEASE_LIBCMT_PDB)
FD_REL_DLL=-Fd$(RELEASE_DLL_PDB)
FD_REL_DLS=-Fd$(RELEASE_DLS_PDB)


FD_REL_ST_DBG=-Fd$(RELEASE_LIBCST_DBG_PDB)
FD_REL_MT_DBG=-Fd$(RELEASE_LIBCMT_DBG_PDB)
FD_REL_DLL_DBG=-Fd$(RELEASE_DLL_DBG_PDB)
FD_REL_DLS_DBG=-Fd$(RELEASE_DLS_DBG_PDB)

!else

!if "$(TARGET_CPU)"=="PMAC"

RELEASE_LIBCST          = $(RELDIR_CPU)\libc.lib
RELEASE_DLL             = $(RELDIR_CPU)\$(RETAIL_DLL_NAME).dll
RELEASE_IMPLIB_DLL      = $(RELDIR_CPU)\$(RETAIL_LIB_NAME).lib
RELEASE_OLDNAMES        = $(RELDIR_CPU)\oldnames.lib

RELEASE_LIBCST_PDB      = $(PDBDIR_CPU)\libc.pdb
RELEASE_DLL_PDB         = $(PDBDIR_CPU)\$(RETAIL_LIB_NAME).pdb


RELEASE_LIBCST_DBG      = $(RELDIR_CPU)\libcd.lib
RELEASE_DLL_DBG         = $(RELDIR_CPU)\$(DEBUG_DLL_NAME).dll
RELEASE_IMPLIB_DLL_DBG  = $(RELDIR_CPU)\$(DEBUG_LIB_NAME).lib

RELEASE_LIBCST_DBG_PDB  = $(PDBDIR_CPU)\libcd.pdb
RELEASE_DLL_DBG_PDB     = $(PDBDIR_CPU)\$(DEBUG_LIB_NAME).pdb

FD_REL_ST=-Fd$(RELEASE_LIBCST_PDB)
FD_REL_DLL=-Fd$(RELEASE_DLL_PDB)


FD_REL_ST_DBG=-Fd$(RELEASE_LIBCST_DBG_PDB)
FD_REL_DLL_DBG=-Fd$(RELEASE_DLL_DBG_PDB)

!else

RELEASE_LIBCST         = $(RELDIR_CPU)\noswap\libc.lib
RELEASE_LIBCS         = $(RELDIR_CPU)\swap\libcs.lib
RELEASE_LLIBC         = $(RELDIR_CPU)\noswapf\llibc.lib
RELEASE_LLIBCS         = $(RELDIR_CPU)\swapf\llibcs.lib
RELEASE_OLDNAMES       = $(RELDIR_CPU)\oldnames.lib

RELEASE_LIBC_PDB      = $(PDBDIR_CPU)\libc.pdb

RELEASE_LIBC_DBG      = $(RELDIR_CPU)\libcd.lib

RELEASE_LIBC_DBG_PDB  = $(PDBDIR_CPU)\libcd.pdb

FD_REL=-Fd$(RELEASE_LIBC_PDB)

FD_REL_DBG=-Fd$(RELEASE_LIBC_DBG_PDB)

!endif

!endif

#
# Locate the scratch location for object files of various flavors.
#
###############################################################################

OBJROOT = build
OBJDIR_PREFIX =  #
OBJCPUDIR = $(OBJROOT)\$(CPUDIR)

OBJDIR_ST  = $(OBJCPUDIR)\st_obj
!if "$(TARGET_CPU)"!="M68K" && "$(TARGET_CPU)"!="PMAC"
OBJDIR_MT  = $(OBJCPUDIR)\mt_obj
!endif
OBJDIR_DLL = $(OBJCPUDIR)\dll_obj
!if "$(TARGET_CPU)"=="i386"
OBJDIR_DLS = $(OBJCPUDIR)\dls_obj
!endif

OBJDIR_OLDNAMES = $(OBJDIR_ST)\oldnames
OBJDIR_TCMAP = $(OBJDIR_ST)\tcmap
OBJDIR_TCMAPDLL = $(OBJDIR_DLL)\tcmap
!if "$(TARGET_CPU)"!="M68K" && "$(TARGET_CPU)"!="PMAC"
OBJDIR_SDKNAMES = $(OBJDIR_DLL)\sdknames
!endif

OBJDIR_DLL_RAW = $(OBJCPUDIR)\*_obj


OBJDIR_ST_DBG  = $(OBJCPUDIR)\xst_obj
!if "$(TARGET_CPU)"!="M68K" && "$(TARGET_CPU)"!="PMAC"
OBJDIR_MT_DBG  = $(OBJCPUDIR)\xmt_obj
!endif
OBJDIR_DLL_DBG = $(OBJCPUDIR)\xdll_obj
!if "$(TARGET_CPU)"=="i386"
OBJDIR_DLS_DBG = $(OBJCPUDIR)\xdls_obj
!endif



all : release debug

!if "$(TARGET_CPU)"=="i386"

release : st mt dll dls oldnames relobjs

!elseif "$(TARGET_CPU)"=="PMAC"

release: st dll oldnames relobjs

!elseif "$(TARGET_CPU)"=="M68K"

release: sst ssts lst lsts oldnames

!else

release : st mt dll oldnames relobjs

!endif

!if "$(TARGET_CPU)"=="i386"

debug : xst xmt xdll xdls


!elseif "$(TARGET_CPU)"=="PMAC"

debug: xst xdll


!elseif "$(TARGET_CPU)"=="M68K"

debug: xsst xssts xlst xlsts

!else

debug : xst xmt xdll


!endif


####
#
# Directory Targets
#
####

$(OBJDIR_ST) $(OBJDIR_MT) $(OBJDIR_DLL) $(OBJDIR_DLS) \
$(OBJDIR_OLDNAMES) $(OBJDIR_TCMAP) $(OBJDIR_TCMAPDLL) $(OBJDIR_SDKNAMES) \
$(OBJDIR_ST_DBG) $(OBJDIR_MT_DBG) $(OBJDIR_DLL_DBG) $(OBJDIR_DLS_DBG) \
$(CRT_RELDIR) $(RELDIR_CPU) :
        if not exist $@\* mkdir $@

####
#
# Define the path to return to the main directory where nmake is revoked
#
####

CD_ROOT=.
 

####
#
# Pseudo-target user interface:
#
####

!if "$(TARGET_CPU)"!="M68K" && "$(TARGET_CPU)"!="PMAC"

st_env :
!if "$(BLD_LIB)"!="1"
    !@-echo. \
    & echo # CL = $(CC_OPTS_BASE) \ \
    & echo # $(WINDOWS_H_DEFS) $(FD_REL_ST) \ \
    & echo # $(ST_DEFINES) \
    & echo. \
    & echo # ML = $(AS_OPTS) \ \
    & echo # $(ST_DEFINES) \
    & echo.
!endif

st : st_env $(OBJROOT) $(OBJCPUDIR) $(OBJDIR_ST) $(RELDIR_CPU) st_

!if "$(BLD_LIB)"!="1"
st_ :: $(MAKE_DIRS)
    !@-cd $** \
    & set CL=$(CC_OPTS) $(ST_DEFINES) $(FD_REL_ST) \
    & set ML=$(AS_OPTS) $(ST_DEFINES) \
    & $(MAKE) -nologo $(IFLAG) -f makefile.sub CPUDIR=$(CPUDIR) WINHEAP=$(WINHEAP) \
        BLD_MODEL=st OBJDIR=$(OBJDIR_PREFIX)$(OBJDIR_ST) \
        TARGET_CPU=$(TARGET_CPU) PRE_BLD=$(PRE_BLD) POST_BLD=$(POST_BLD) \
    & cd $(CD_ROOT)
!endif # BLD_LIB != 1

!if "$(PRE_BLD)"!="1" && "$(BLD_OBJ)"!="1"
st_ :: $(RELEASE_LIBCST)
!else
st_ ::
!endif

mt_env :
!if "$(BLD_LIB)"!="1"
    !@-echo. \
    & echo # CL = $(CC_OPTS_BASE) \ \
    & echo # $(WINDOWS_H_DEFS) $(FD_REL_MT) \ \
    & echo # $(MT_DEFINES) \
    & echo. \
    & echo # ML = $(AS_OPTS) \ \
    & echo # $(MT_DEFINES) \
    & echo.
!endif

mt : mt_env $(OBJROOT) $(OBJCPUDIR) $(OBJDIR_MT) $(RELDIR_CPU) mt_

!if "$(BLD_LIB)"!="1"
mt_ :: $(MAKE_DIRS)
    !@-cd $** \
    & set CL=$(CC_OPTS) $(MT_DEFINES) $(FD_REL_MT) \
    & set ML=$(AS_OPTS) $(MT_DEFINES) \
    & $(MAKE) -nologo $(IFLAG) -f makefile.sub CPUDIR=$(CPUDIR) WINHEAP=$(WINHEAP) \
        BLD_MODEL=mt OBJDIR=$(OBJDIR_PREFIX)$(OBJDIR_MT) \
        TARGET_CPU=$(TARGET_CPU) PRE_BLD=$(PRE_BLD) POST_BLD=$(POST_BLD) \
    & cd $(CD_ROOT)
!endif # BLD_LIB != 1

!if "$(PRE_BLD)"!="1" && "$(BLD_OBJ)"!="1"
mt_ :: $(RELEASE_LIBCMT)
!else
mt_ ::
!endif

dll_env :
!if "$(BLD_LIB)"!="1"
    !@-echo. \
    & echo # CL = $(CC_OPTS_BASE) \ \
    & echo # $(WINDOWS_H_DEFS) $(FD_REL_DLL) \ \
    & echo # $(DLL_DEFINES) \
    & echo. \
    & echo # ML = $(AS_OPTS) \ \
    & echo # $(DLL_DEFINES) \
    & echo.
!endif

dll : dll_env $(OBJROOT) $(OBJCPUDIR) $(OBJDIR_DLL) $(RELDIR_CPU) others dll_

!if "$(BLD_LIB)"!="1"
dll_ :: $(MAKE_DIRS_DLL)
    !@-cd $** \
    & set CL=$(CC_OPTS) $(DLL_DEFINES) $(FD_REL_DLL) \
    & set ML=$(AS_OPTS) $(DLL_DEFINES) \
    & $(MAKE) -nologo $(IFLAG) -f makefile.sub CPUDIR=$(CPUDIR) WINHEAP=$(WINHEAP) \
        BLD_MODEL=dll BLD_DLL=1 OBJDIR=$(OBJDIR_PREFIX)$(OBJDIR_DLL) \
        TARGET_CPU=$(TARGET_CPU) PRE_BLD=$(PRE_BLD) POST_BLD=$(POST_BLD) \
    & cd $(CD_ROOT)
!endif # BLD_LIB != 1

!if "$(PRE_BLD)"!="1" && "$(BLD_OBJ)"!="1"
dll_ :: $(RELEASE_DLL)
!else
dll_ ::
!endif

!if "$(TARGET_CPU)"=="i386"

dls_env :
!if "$(BLD_LIB)"!="1"
    !@-echo. \
    & echo # CL = $(CC_OPTS_BASE) \ \
    & echo # $(WINDOWS_H_DEFS) $(FD_REL_DLS) \ \
    & echo # $(DLS_DEFINES) \
    & echo. \
    & echo # ML = $(AS_OPTS) \ \
    & echo # $(DLS_DEFINES) \
    & echo.
!endif

dls : dls_env $(OBJROOT) $(OBJCPUDIR) $(OBJDIR_DLS) $(RELDIR_CPU) others dls_

!if "$(BLD_LIB)"!="1"
dls_ :: $(MAKE_DIRS_DLL)
    !@-cd $** \
    & set CL=$(CC_OPTS) $(DLS_DEFINES) $(FD_REL_DLS) \
    & set ML=$(AS_OPTS) $(DLS_DEFINES) \
    & $(MAKE) -nologo $(IFLAG) -f makefile.sub CPUDIR=$(CPUDIR) WINHEAP=$(WINHEAP) \
        BLD_MODEL=dls BLD_DLL=1 OBJDIR=$(OBJDIR_PREFIX)$(OBJDIR_DLS) \
        TARGET_CPU=$(TARGET_CPU) PRE_BLD=$(PRE_BLD) POST_BLD=$(POST_BLD) \
    & cd $(CD_ROOT)
!endif # BLD_LIB != 1

!if "$(PRE_BLD)"!="1" && "$(BLD_OBJ)"!="1"
dls_ :: $(RELEASE_DLS)
!else
dls_ ::
!endif

!endif


xst_env :
!if "$(BLD_LIB)"!="1"
    !@-echo. \
    & echo # CL = $(CC_OPTS_BASE) \ \
    & echo # $(WINDOWS_H_DEFS) $(FD_REL_ST_DBG) \ \
    & echo # $(ST_DEFINES) \
    & echo. \
    & echo # ML = $(AS_OPTS) \ \
    & echo # $(ST_DEFINES) \
    & echo.
!endif

xst : xst_env $(OBJROOT) $(OBJCPUDIR) $(OBJDIR_ST_DBG) $(RELDIR_CPU) xst_

!if "$(BLD_LIB)"!="1"
xst_ :: $(MAKE_DIRS)
    !@-cd $** \
    & set CL=$(CC_OPTS) $(ST_DEFINES) $(FD_REL_ST_DBG) \
    & set ML=$(AS_OPTS) $(ST_DEFINES) \
    & $(MAKE) -nologo $(IFLAG) -f makefile.sub CPUDIR=$(CPUDIR) WINHEAP=$(WINHEAP) \
        BLD_MODEL=xst BLD_DBG=1 OBJDIR=$(OBJDIR_PREFIX)$(OBJDIR_ST_DBG) \
        TARGET_CPU=$(TARGET_CPU) PRE_BLD=$(PRE_BLD) POST_BLD=$(POST_BLD) \
    & cd $(CD_ROOT)
!endif # BLD_LIB != 1

!if "$(PRE_BLD)"!="1" && "$(BLD_OBJ)"!="1"
xst_ :: $(RELEASE_LIBCST_DBG)
!else
xst_ ::
!endif

xmt_env :
!if "$(BLD_LIB)"!="1"
    !@-echo. \
    & echo # CL = $(CC_OPTS_BASE) \ \
    & echo # $(WINDOWS_H_DEFS) $(FD_REL_MT_DBG) \ \
    & echo # $(MT_DEFINES) \
    & echo. \
    & echo # ML = $(AS_OPTS) \ \
    & echo # $(MT_DEFINES) \
    & echo.
!endif

xmt : xmt_env $(OBJROOT) $(OBJCPUDIR) $(OBJDIR_MT_DBG) $(RELDIR_CPU) xmt_

!if "$(BLD_LIB)"!="1"
xmt_ :: $(MAKE_DIRS)
    !@-cd $** \
    & set CL=$(CC_OPTS) $(MT_DEFINES) $(FD_REL_MT_DBG) \
    & set ML=$(AS_OPTS) $(MT_DEFINES) \
    & $(MAKE) -nologo $(IFLAG) -f makefile.sub CPUDIR=$(CPUDIR) WINHEAP=$(WINHEAP) \
        BLD_MODEL=xmt BLD_DBG=1 OBJDIR=$(OBJDIR_PREFIX)$(OBJDIR_MT_DBG) \
        TARGET_CPU=$(TARGET_CPU) PRE_BLD=$(PRE_BLD) POST_BLD=$(POST_BLD) \
    & cd $(CD_ROOT)
!endif # BLD_LIB != 1

!if "$(PRE_BLD)"!="1" && "$(BLD_OBJ)"!="1"
xmt_ :: $(RELEASE_LIBCMT_DBG)
!else
xmt_ ::
!endif

xdll_env :
!if "$(BLD_LIB)"!="1"
    !@-echo. \
    & echo # CL = $(CC_OPTS_BASE) \ \
    & echo # $(WINDOWS_H_DEFS) $(FD_REL_DLL_DBG) \ \
    & echo # $(DLL_DEFINES) \
    & echo. \
    & echo # ML = $(AS_OPTS) \ \
    & echo # $(DLL_DEFINES) \
    & echo.
!endif

xdll : xdll_env $(OBJROOT) $(OBJCPUDIR) $(OBJDIR_DLL_DBG) $(RELDIR_CPU) xothers xdll_

!if "$(BLD_LIB)"!="1"
xdll_ :: $(MAKE_DIRS_DLL)
    !@-cd $** \
    & set CL=$(CC_OPTS) $(DLL_DEFINES) $(FD_REL_DLL_DBG) \
    & set ML=$(AS_OPTS) $(DLL_DEFINES) \
    & $(MAKE) -nologo $(IFLAG) -f makefile.sub CPUDIR=$(CPUDIR) WINHEAP=$(WINHEAP) \
        BLD_MODEL=xdll BLD_DLL=1 BLD_DBG=1 OBJDIR=$(OBJDIR_PREFIX)$(OBJDIR_DLL_DBG) \
        TARGET_CPU=$(TARGET_CPU) PRE_BLD=$(PRE_BLD) POST_BLD=$(POST_BLD) \
    & cd $(CD_ROOT)
!endif # BLD_LIB != 1

!if "$(PRE_BLD)"!="1" && "$(BLD_OBJ)"!="1"
xdll_ :: $(RELEASE_DLL_DBG)
!else
xdll_ ::
!endif

!if "$(TARGET_CPU)"=="i386"

xdls_env :
!if "$(BLD_LIB)"!="1"
    !@-echo. \
    & echo # CL = $(CC_OPTS_BASE) \ \
    & echo # $(WINDOWS_H_DEFS) $(FD_REL_DLS_DBG) \ \
    & echo # $(DLS_DEFINES) \
    & echo. \
    & echo # ML = $(AS_OPTS) \ \
    & echo # $(DLS_DEFINES) \
    & echo.
!endif

xdls : xdls_env $(OBJROOT) $(OBJCPUDIR) $(OBJDIR_DLS_DBG) $(RELDIR_CPU) xothers xdls_

!if "$(BLD_LIB)"!="1"
xdls_ :: $(MAKE_DIRS_DLL)
    !@-cd $** \
    & set CL=$(CC_OPTS) $(DLS_DEFINES) $(FD_REL_DLS_DBG) \
    & set ML=$(AS_OPTS) $(DLS_DEFINES) \
    & $(MAKE) -nologo $(IFLAG) -f makefile.sub CPUDIR=$(CPUDIR) WINHEAP=$(WINHEAP) \
        BLD_MODEL=xdls BLD_DLL=1 BLD_DBG=1 OBJDIR=$(OBJDIR_PREFIX)$(OBJDIR_DLS_DBG) \
        TARGET_CPU=$(TARGET_CPU) PRE_BLD=$(PRE_BLD) POST_BLD=$(POST_BLD) \
    & cd $(CD_ROOT)
!endif # BLD_LIB != 1

!if "$(PRE_BLD)"!="1" && "$(BLD_OBJ)"!="1"
xdls_ :: $(RELEASE_DLS_DBG)
!else
xdls_ ::
!endif

!endif


!if "$(TARGET_CPU)"=="i386"

all_link: st_link mt_link dll_link dls_link

!else

all_link: st_link mt_link dll_link

!endif

st_link: $(RELEASE_LIBCST)

mt_link: $(RELEASE_LIBCMT)

dll_link: $(RELEASE_DLL)

dls_link: $(RELEASE_DLS)



oldnames :

others :

xothers :


!elseif "$(TARGET_CPU)"=="PMAC"

ST_DEFINES=$(COMMON_DEFS)
DLL_DEFINES=$(ST_DEFINES) -DCRTDLL


st_env :
!if "$(BLD_LIB)"!="1"
    !@-echo. \
    & echo # CL = $(CC_OPTS) $(FD_REL_ST) \ \
    & echo # $(ST_DEFINES) \
    & echo. \
    & echo # ML = $(AS_OPTS) $(ST_DEFINES) \
    & echo.
!endif

st : st_env $(OBJROOT) $(OBJCPUDIR) $(OBJDIR_ST) $(RELDIR_CPU) st_

!if "$(BLD_LIB)"!="1"
st_ :: $(MAKE_DIRS)
    !@-cd $** \
    & set CL=$(CC_OPTS) $(ST_DEFINES) $(FD_REL_ST) \
    & set ML=$(AS_OPTS) $(ST_DEFINES) \
    & $(MAKE) -nologo $(IFLAG) -f makefile.sub CPUDIR=$(CPUDIR) WINHEAP=$(WINHEAP) \
        BLD_MODEL=st OBJDIR=$(OBJDIR_PREFIX)$(OBJDIR_ST) \
        TARGET_CPU=$(TARGET_CPU) PRE_BLD=$(PRE_BLD) POST_BLD=$(POST_BLD) \
    & cd $(CD_ROOT)
!endif # BLD_LIB != 1

!if "$(PRE_BLD)"!="1" && "$(BLD_OBJ)"!="1"
st_ :: $(RELEASE_LIBCST)
!else
st_ ::
!endif

dll_env :
!if "$(BLD_LIB)"!="1"
    !@-echo. \
    & echo # CL = $(CC_OPTS) $(FD_REL_DLL) \ \
    & echo # $(DLL_DEFINES) \
    & echo. \
    & echo # ML = $(AS_OPTS) $(DLL_DEFINES) \
    & echo.
!endif

dll : dll_env $(OBJROOT) $(OBJCPUDIR) $(OBJDIR_DLL) $(RELDIR_CPU) others dll_

!if "$(BLD_LIB)"!="1"
dll_ :: $(MAKE_DIRS_DLL)
    !@-cd $** \
    & set CL=$(CC_OPTS) $(DLL_DEFINES) $(FD_REL_DLL) \
    & set ML=$(AS_OPTS) $(DLL_DEFINES) \
    & $(MAKE) -nologo $(IFLAG) -f makefile.sub CPUDIR=$(CPUDIR) WINHEAP=$(WINHEAP) \
        BLD_MODEL=dll BLD_DLL=1 OBJDIR=$(OBJDIR_PREFIX)$(OBJDIR_DLL) \
        TARGET_CPU=$(TARGET_CPU) PRE_BLD=$(PRE_BLD) POST_BLD=$(POST_BLD) \
    & cd $(CD_ROOT)
!endif # BLD_LIB != 1

!if "$(PRE_BLD)"!="1" && "$(BLD_OBJ)"!="1"
dll_ :: $(RELEASE_DLL)
!else
dll_ ::
!endif


xst_env :
!if "$(BLD_LIB)"!="1"
    !@-echo. \
    & echo # CL = $(CC_OPTS) $(FD_REL_ST_DBG) \ \
    & echo # $(ST_DEFINES) \
    & echo. \
    & echo # ML = $(AS_OPTS) $(ST_DEFINES) \
    & echo.
!endif

xst : xst_env $(OBJROOT) $(OBJCPUDIR) $(OBJDIR_ST_DBG) $(RELDIR_CPU) xst_

!if "$(BLD_LIB)"!="1"
xst_ :: $(MAKE_DIRS)
    !@-cd $** \
    & set CL=$(CC_OPTS) $(ST_DEFINES) $(FD_REL_ST_DBG) \
    & set ML=$(AS_OPTS) \
    & $(MAKE) -nologo $(IFLAG) -f makefile.sub CPUDIR=$(CPUDIR) WINHEAP=$(WINHEAP) \
        BLD_MODEL=xst BLD_DBG=1 OBJDIR=$(OBJDIR_PREFIX)$(OBJDIR_ST_DBG) \
        TARGET_CPU=$(TARGET_CPU) PRE_BLD=$(PRE_BLD) POST_BLD=$(POST_BLD) \
    & cd $(CD_ROOT)
!endif # BLD_LIB != 1

!if "$(PRE_BLD)"!="1" && "$(BLD_OBJ)"!="1"
xst_ :: $(RELEASE_LIBCST_DBG)
!else
xst_ ::
!endif

xdll_env :
!if "$(BLD_LIB)"!="1"
    !@-echo. \
    & echo # CL = $(CC_OPTS) $(FD_REL_DLL_DBG) \ \
    & echo # $(DLL_DEFINES) \
    & echo. \
    & echo # ML = $(AS_OPTS) $(DLL_DEFINES) \
    & echo.
!endif

xdll : xdll_env $(OBJROOT) $(OBJCPUDIR) $(OBJDIR_DLL_DBG) $(RELDIR_CPU) xothers xdll_

!if "$(BLD_LIB)"!="1"
xdll_ :: $(MAKE_DIRS_DLL)
    !@-cd $** \
    & set CL=$(CC_OPTS) $(DLL_DEFINES) $(FD_REL_DLL_DBG) \
    & set ML=$(AS_OPTS) $(DLL_DEFINES) \
    & $(MAKE) -nologo $(IFLAG) -f makefile.sub CPUDIR=$(CPUDIR) WINHEAP=$(WINHEAP) \
        BLD_MODEL=xdll BLD_DLL=1 BLD_DBG=1 OBJDIR=$(OBJDIR_PREFIX)$(OBJDIR_DLL_DBG) \
        TARGET_CPU=$(TARGET_CPU) PRE_BLD=$(PRE_BLD) POST_BLD=$(POST_BLD) \
    & cd $(CD_ROOT)
!endif # BLD_LIB != 1

!if "$(PRE_BLD)"!="1" && "$(BLD_OBJ)"!="1"
xdll_ :: $(RELEASE_DLL_DBG)
!else
xdll_ ::
!endif


all_link: st_link dll_link

st_link: $(RELEASE_LIBCST)

dll_link: $(RELEASE_DLL)


!if "$(POST_BLD)"=="1"

oldnames :

others :

xothers :

!else

oldnames : $(RELEASE_OLDNAMES)

!if "$(PRE_BLD)"=="1"

others xothers: \
	$(TCMAPLIB_DIR)\tcmap.lib \
	$(TCMAPDLLLIB_DIR)\tcmapdll.lib

others : $(DEFFILE_DIR)\$(RETAIL_DLL_NAME).def

xothers : $(DEFFILE_DIR)\$(DEBUG_DLL_NAME).def

!else

others :

xothers :

!endif

!endif

!elseif "$(TARGET_CPU)"=="M68K"

!endif

#
# Make Process for Static Libraries
#
###############################################################################

$(RELEASE_LIBCST): $(RELDIR_CPU) $(SOURCE_OBJS:*=st) \
 $(OBJDIR_ST)\link.rsp
	$(LINKLIB) -out:$@ @$(OBJDIR_ST)\link.rsp

!if "$(BLD_OBJ)"!="1"
$(OBJDIR_ST)\link.rsp: makefile
	@echo *** Creating linker response file <<$@
$(SOURCE_OBJS:*=st)
<<keep
!endif


$(RELEASE_LIBCST_DBG): $(RELDIR_CPU) $(SOURCE_OBJS:*=xst) \
 $(OBJDIR_ST_DBG)\link.rsp
	$(LINKLIB) -out:$@ @$(OBJDIR_ST_DBG)\link.rsp

!if "$(BLD_OBJ)"!="1"
$(OBJDIR_ST_DBG)\link.rsp: makefile
	@echo *** Creating linker response file <<$@
$(SOURCE_OBJS:*=xst)
<<keep
!endif

!if "$(TARGET_CPU)"!="M68K" && "$(TARGET_CPU)"!="PMAC"

$(RELEASE_LIBCMT): $(RELDIR_CPU) $(SOURCE_OBJS:*=mt) \
 $(OBJDIR_MT)\link.rsp
	$(LINKLIB) -out:$@ @$(OBJDIR_MT)\link.rsp

!if "$(BLD_OBJ)"!="1"
$(OBJDIR_MT)\link.rsp: makefile
	@echo *** Creating linker response file <<$@
$(SOURCE_OBJS:*=mt)
<<keep
!endif


$(RELEASE_LIBCMT_DBG): $(RELDIR_CPU) $(SOURCE_OBJS:*=xmt) \
 $(OBJDIR_MT_DBG)\link.rsp
	$(LINKLIB) -out:$@ @$(OBJDIR_MT_DBG)\link.rsp

!if "$(BLD_OBJ)"!="1"
$(OBJDIR_MT_DBG)\link.rsp: makefile
	@echo *** Creating linker response file <<$@
$(SOURCE_OBJS:*=xmt)
<<keep
!endif

!endif

#
# Make Process for C Run-Time DLL
#
###############################################################################

# todo ... preprocess a single source .def file into machine-specific version

!if "$(TARGET_CPU)"!="M68K"

# {{ Beginning of block TARGET_CPU != M68K }}

OBJS_WITH_EXPORTS_DLL_RAW= \
        $(OBJDIR_DLL_RAW)\handler.obj \
        $(OBJDIR_DLL_RAW)\setnewh.obj \
        $(OBJDIR_DLL_RAW)\new_mode.obj \
        $(OBJDIR_DLL_RAW)\undname.obj \
!IF "$(TARGET_CPU)"=="i386"
        $(OBJDIR_DLL_RAW)\frame.obj \
        $(OBJDIR_DLL_RAW)\hooks.obj \
        $(OBJDIR_DLL_RAW)\throw.obj \
        $(OBJDIR_DLL_RAW)\trnsctrl.obj \
        $(OBJDIR_DLL_RAW)\typinfo.obj \
        $(OBJDIR_DLL_RAW)\typname.obj \
        $(OBJDIR_DLL_RAW)\unhandld.obj \
        $(OBJDIR_DLL_RAW)\user.obj \
        $(OBJDIR_DLL_RAW)\validate.obj \
!ELSEIF "$(TARGET_CPU)"=="mips"
        $(OBJDIR_DLL_RAW)\ehstate.obj \
        $(OBJDIR_DLL_RAW)\frame.obj \
        $(OBJDIR_DLL_RAW)\hooks.obj \
        $(OBJDIR_DLL_RAW)\throw.obj \
        $(OBJDIR_DLL_RAW)\trnsctrl.obj \
        $(OBJDIR_DLL_RAW)\typinfo.obj \
        $(OBJDIR_DLL_RAW)\typname.obj \
        $(OBJDIR_DLL_RAW)\unhandld.obj \
        $(OBJDIR_DLL_RAW)\user.obj \
        $(OBJDIR_DLL_RAW)\validate.obj \
!ELSEIF "$(TARGET_CPU)"=="ALPHA"
        $(OBJDIR_DLL_RAW)\hooks.obj \
        $(OBJDIR_DLL_RAW)\trnsctrl.obj \
        $(OBJDIR_DLL_RAW)\user.obj \
!ELSEIF "$(TARGET_CPU)"=="PMAC"
        $(OBJDIR_DLL_RAW)\trnsctrl.obj \
        $(OBJDIR_DLL_RAW)\ehstate.obj \
        $(OBJDIR_DLL_RAW)\lowhelpr.obj \
        $(OBJDIR_DLL_RAW)\frame.obj \
        $(OBJDIR_DLL_RAW)\hooks.obj \
        $(OBJDIR_DLL_RAW)\throw.obj \
        $(OBJDIR_DLL_RAW)\user.obj \
        $(OBJDIR_DLL_RAW)\ehvecctr.obj \
        $(OBJDIR_DLL_RAW)\ehveccvb.obj \
        $(OBJDIR_DLL_RAW)\ehvecdtr.obj \
        $(OBJDIR_DLL_RAW)\rtti.obj \
        $(OBJDIR_DLL_RAW)\stdexcpt.obj \
        $(OBJDIR_DLL_RAW)\typinfo.obj \
        $(OBJDIR_DLL_RAW)\typname.obj \
!ELSEIF "$(TARGET_CPU)"=="PPC"
        $(OBJDIR_DLL_RAW)\ehstate.obj \
        $(OBJDIR_DLL_RAW)\frame.obj \
        $(OBJDIR_DLL_RAW)\handlers.obj \
        $(OBJDIR_DLL_RAW)\hooks.obj \
        $(OBJDIR_DLL_RAW)\throw.obj \
        $(OBJDIR_DLL_RAW)\trnsctrl.obj \
        $(OBJDIR_DLL_RAW)\typinfo.obj \
        $(OBJDIR_DLL_RAW)\typname.obj \
        $(OBJDIR_DLL_RAW)\unhandld.obj \
        $(OBJDIR_DLL_RAW)\unwind.obj \
        $(OBJDIR_DLL_RAW)\user.obj \
        $(OBJDIR_DLL_RAW)\validate.obj \
!ENDIF
        $(OBJDIR_DLL_RAW)\cerrinit.obj \
        $(OBJDIR_DLL_RAW)\cininit.obj \
        $(OBJDIR_DLL_RAW)\cloginit.obj \
!IF "$(TARGET_CPU)"!="PMAC"
        $(OBJDIR_DLL_RAW)\errmode.obj \
!ENDIF
        $(OBJDIR_DLL_RAW)\filebuf.obj \
        $(OBJDIR_DLL_RAW)\filebuf1.obj \
        $(OBJDIR_DLL_RAW)\fstream.obj \
        $(OBJDIR_DLL_RAW)\ifstream.obj \
        $(OBJDIR_DLL_RAW)\ios.obj \
        $(OBJDIR_DLL_RAW)\iostream.obj \
        $(OBJDIR_DLL_RAW)\iostrini.obj \
        $(OBJDIR_DLL_RAW)\istrchar.obj \
        $(OBJDIR_DLL_RAW)\istrdbl.obj \
        $(OBJDIR_DLL_RAW)\istream.obj \
        $(OBJDIR_DLL_RAW)\istream1.obj \
        $(OBJDIR_DLL_RAW)\istrflt.obj \
        $(OBJDIR_DLL_RAW)\istrgdbl.obj \
        $(OBJDIR_DLL_RAW)\istrget.obj \
        $(OBJDIR_DLL_RAW)\istrgetl.obj \
        $(OBJDIR_DLL_RAW)\istrgint.obj \
        $(OBJDIR_DLL_RAW)\istrint.obj \
        $(OBJDIR_DLL_RAW)\istrldbl.obj \
        $(OBJDIR_DLL_RAW)\istrlong.obj \
        $(OBJDIR_DLL_RAW)\istrshrt.obj \
        $(OBJDIR_DLL_RAW)\istruint.obj \
        $(OBJDIR_DLL_RAW)\istrulng.obj \
        $(OBJDIR_DLL_RAW)\istrusht.obj \
!IF "$(TARGET_CPU)"!="PMAC"
        $(OBJDIR_DLL_RAW)\matherr.obj \
        $(OBJDIR_DLL_RAW)\mtlock.obj \
!ENDIF
        $(OBJDIR_DLL_RAW)\ofstream.obj \
        $(OBJDIR_DLL_RAW)\ostrchar.obj \
        $(OBJDIR_DLL_RAW)\ostrdbl.obj \
        $(OBJDIR_DLL_RAW)\ostream.obj \
        $(OBJDIR_DLL_RAW)\ostream1.obj \
        $(OBJDIR_DLL_RAW)\ostrint.obj \
        $(OBJDIR_DLL_RAW)\ostrldbl.obj \
        $(OBJDIR_DLL_RAW)\ostrlong.obj \
        $(OBJDIR_DLL_RAW)\ostrptr.obj \
        $(OBJDIR_DLL_RAW)\ostrput.obj \
        $(OBJDIR_DLL_RAW)\ostrshrt.obj \
        $(OBJDIR_DLL_RAW)\ostruint.obj \
        $(OBJDIR_DLL_RAW)\ostrulng.obj \
        $(OBJDIR_DLL_RAW)\ostrusht.obj \
        $(OBJDIR_DLL_RAW)\stdiostr.obj \
        $(OBJDIR_DLL_RAW)\streamb.obj \
        $(OBJDIR_DLL_RAW)\streamb1.obj \
        $(OBJDIR_DLL_RAW)\strmbdbp.obj \
        $(OBJDIR_DLL_RAW)\strstrea.obj

OBJS_WITH_EXPORTS_DLL=$(OBJS_WITH_EXPORTS_DLL_RAW:*=dll)


OBJS_WITH_EXPORTS_DLL_DBG=$(OBJS_WITH_EXPORTS_DLL_RAW:*=xdll)

!if "$(TARGET_CPU)"!="M68K" && "$(TARGET_CPU)"!="PMAC"

DLL_MT_OBJS_RAW= \
        $(OBJDIR_DLL_RAW)\_newmode.obj \
!if "$(TARGET_CPU)"=="i386"
        $(OBJDIR_DLL_RAW)\atlssup.obj \
!endif
        $(OBJDIR_DLL_RAW)\charmax.obj \
        $(OBJDIR_DLL_RAW)\chkstk.obj \
        $(OBJDIR_DLL_RAW)\xncommod.obj \
        $(OBJDIR_DLL_RAW)\tlssup.obj \
        $(OBJDIR_DLL_RAW)\xtxtmode.obj


DLL_STATIC_OBJS_RAW= \
        $(OBJDIR_DLL_RAW)\atonexit.obj \
        $(OBJDIR_DLL_RAW)\cinitexe.obj \
        $(OBJDIR_DLL_RAW)\crtdll.obj \
        $(OBJDIR_DLL_RAW)\crtexe.obj \
        $(OBJDIR_DLL_RAW)\crtexew.obj \
        $(OBJDIR_DLL_RAW)\dll_argv.obj \
        $(OBJDIR_DLL_RAW)\dllargv.obj \
        $(OBJDIR_DLL_RAW)\dllmain.obj \
        $(OBJDIR_DLL_RAW)\ehvecctr.obj \
        $(OBJDIR_DLL_RAW)\ehveccvb.obj \
        $(OBJDIR_DLL_RAW)\ehvecdtr.obj \
        $(OBJDIR_DLL_RAW)\merr.obj \
        $(OBJDIR_DLL_RAW)\ti_inst.obj \
        $(OBJDIR_DLL_RAW)\wcrtexe.obj \
        $(OBJDIR_DLL_RAW)\wcrtexew.obj \
        $(OBJDIR_DLL_RAW)\wdllargv.obj \
        $(OBJDIR_DLL_RAW)\wildcard.obj \
!if "$(TARGET_CPU)"=="i386"
        $(OBJDIR_DLL_RAW)\dllsupp.obj \
        $(OBJDIR_DLL_RAW)\adjustfd.obj \
        $(OBJDIR_DLL_RAW)\fp8.obj \
        $(OBJDIR_DLL_RAW)\lldiv.obj \
        $(OBJDIR_DLL_RAW)\llmul.obj \
        $(OBJDIR_DLL_RAW)\llrem.obj \
        $(OBJDIR_DLL_RAW)\llshl.obj \
        $(OBJDIR_DLL_RAW)\llshr.obj \
        $(OBJDIR_DLL_RAW)\ulldiv.obj \
        $(OBJDIR_DLL_RAW)\ullrem.obj \
        $(OBJDIR_DLL_RAW)\ullshr.obj \
!elseif "$(TARGET_CPU)"=="mips"
        $(OBJDIR_DLL_RAW)\llabsdiv.obj \
        $(OBJDIR_DLL_RAW)\llbit.obj \
        $(OBJDIR_DLL_RAW)\llcvt.obj \
        $(OBJDIR_DLL_RAW)\lldiv.obj \
        $(OBJDIR_DLL_RAW)\lldivrem.obj \
        $(OBJDIR_DLL_RAW)\llmul.obj \
        $(OBJDIR_DLL_RAW)\llshift.obj \
!elseif "$(TARGET_CPU)"=="PPC"
        $(OBJDIR_DLL_RAW)\dtoi.obj    \
        $(OBJDIR_DLL_RAW)\dtoi64.obj  \
        $(OBJDIR_DLL_RAW)\dtou.obj    \
        $(OBJDIR_DLL_RAW)\dtou64.obj  \
        $(OBJDIR_DLL_RAW)\i64div.obj  \
        $(OBJDIR_DLL_RAW)\i64rem.obj  \
        $(OBJDIR_DLL_RAW)\i64tod.obj  \
        $(OBJDIR_DLL_RAW)\itod.obj    \
        $(OBJDIR_DLL_RAW)\itof.obj    \
        $(OBJDIR_DLL_RAW)\restfpr.obj \
        $(OBJDIR_DLL_RAW)\restgpr.obj \
        $(OBJDIR_DLL_RAW)\savefpr.obj \
        $(OBJDIR_DLL_RAW)\savegpr.obj \
        $(OBJDIR_DLL_RAW)\u64div.obj  \
        $(OBJDIR_DLL_RAW)\u64rem.obj  \
        $(OBJDIR_DLL_RAW)\u64tod.obj  \
        $(OBJDIR_DLL_RAW)\utod.obj    \
        $(OBJDIR_DLL_RAW)\utof.obj
!endif

DLL_STATIC_OBJS=$(DLL_MT_OBJS_RAW:*=dll) $(DLL_STATIC_OBJS_RAW:*=dll)


DLL_STATIC_OBJS_DBG=$(DLL_MT_OBJS_RAW:*=xdll) $(DLL_STATIC_OBJS_RAW:*=xdll)


!if "$(POST_BLD)"!="1"

$(DEFFILE_DIR)\$(RETAIL_DLL_NAME).def : $(RETAIL_LIB_NAME).src
        $(CC) -nologo -DLIBRARYNAME=$(RETAIL_DLL_NAME_UC) -EP -Tc$(RETAIL_LIB_NAME).src | sed "/^[ 	]*$$/d" > $@

$(DEFFILE_DIR)\$(DEBUG_DLL_NAME).def : $(RETAIL_LIB_NAME).src
        $(CC) -nologo -DLIBRARYNAME=$(DEBUG_DLL_NAME_UC) -D_DEBUG -EP -Tc$(RETAIL_LIB_NAME).src | sed "/^[ 	]*$$/d" > $@

$(DEFFILE_DIR)\win32s\$(RETAIL_DLL_NAME).def : $(RETAIL_LIB_NAME).src
        $(CC) -nologo -DLIBRARYNAME=$(RETAIL_DLL_NAME_UC) -DWIN32S -EP -Tc$(RETAIL_LIB_NAME).src | sed "/^[ 	]*$$/d" > $@

$(DEFFILE_DIR)\win32s\$(DEBUG_DLL_NAME).def : $(RETAIL_LIB_NAME).src
        $(CC) -nologo -DLIBRARYNAME=$(DEBUG_DLL_NAME_UC) -D_DEBUG -DWIN32S -EP -Tcmsvcrt.src | sed "/^[ 	]*$$/d" > $@

!endif


$(RELEASE_DLL) : $(RELDIR_CPU) $(RETAIL_DLL_NAME).rc \
 $(DEFFILE_DIR)\$(RETAIL_DLL_NAME).def $(SOURCE_OBJS_DLL:*=dll) \
 $(DLL_STATIC_OBJS) $(SDKNAMESLIB_DIR)\sdknames.lib \
 $(TCMAPLIB_DIR)\tcmap.lib $(TCMAPDLLLIB_DIR)\tcmapdll.lib \
 $(V4TOOLS)\include\winver.h \
 $(OBJDIR_DLL)\link.rsp $(OBJDIR_DLL)\implib.rsp
	rc $(RC_OPTS) -Fo $(@R).res $(RC_DEFS) $(RC_INCS) $(RETAIL_DLL_NAME).rc
	$(LINKER) @$(OBJDIR_DLL)\link.rsp
	$(LINKLIB) @$(OBJDIR_DLL)\implib.rsp

!if "$(BLD_OBJ)"!="1"
$(OBJDIR_DLL)\link.rsp: makefile
	@echo *** Creating linker response file <<$@
-base:0x10200000
-def:$(DEFFILE_DIR)\$(RETAIL_DLL_NAME).def
-dll
-entry:_CRTDLL_INIT
-force:multiple
-implib:$(OBJDIR_DLL)\tmp.lib
-incremental:no
-map
-out:$(RELEASE_DLL)
-release
$(OBJS_WITH_EXPORTS_DLL)
$(RELEASE_DLL:.dll=.res)
$(SOURCE_OBJS_DLL:*=dll)
kernel32.lib
<<keep

$(OBJDIR_DLL)\implib.rsp: makefile
	@echo *** Creating linker response file <<$@
-out:$(RELEASE_IMPLIB_DLL)
$(OBJDIR_DLL)\tmp.lib
$(DLL_STATIC_OBJS)
$(SDKNAMESLIB_DIR)\sdknames.lib
$(TCMAPLIB_DIR)\tcmap.lib
$(TCMAPDLLLIB_DIR)\tcmapdll.lib
<<keep
!endif


$(RELEASE_DLL_DBG) : $(RELDIR_CPU) $(RETAIL_DLL_NAME).rc \
 $(DEFFILE_DIR)\$(DEBUG_DLL_NAME).def $(SOURCE_OBJS_DLL:*=xdll) \
 $(DLL_STATIC_OBJS_DBG) $(SDKNAMESLIB_DIR)\sdknames.lib \
 $(TCMAPLIB_DIR)\tcmap.lib $(TCMAPDLLLIB_DIR)\tcmapdll.lib \
 $(V4TOOLS)\include\winver.h \
 $(OBJDIR_DLL_DBG)\link.rsp $(OBJDIR_DLL_DBG)\implib.rsp
	rc $(RC_OPTS) -Fo $(@R).res -D_DEBUG $(RC_DEFS) $(RC_INCS) $(RETAIL_DLL_NAME).rc
	$(LINKER) @$(OBJDIR_DLL_DBG)\link.rsp
	$(LINKLIB) @$(OBJDIR_DLL_DBG)\implib.rsp

!if "$(BLD_OBJ)"!="1"
$(OBJDIR_DLL_DBG)\link.rsp: makefile
	@echo *** Creating linker response file <<$@
-base:0x10200000
-dbgimplib
-debug
-def:$(DEFFILE_DIR)\$(DEBUG_DLL_NAME).def
-dll
-entry:_CRTDLL_INIT
-force:multiple
-implib:$(OBJDIR_DLL_DBG)\tmp.lib
-incremental:no
-map
-out:$(RELEASE_DLL_DBG)
-release
$(OBJS_WITH_EXPORTS_DLL_DBG)
$(RELEASE_DLL_DBG:.dll=.res)
$(SOURCE_OBJS_DLL:*=xdll)
kernel32.lib
<<keep

$(OBJDIR_DLL_DBG)\implib.rsp: makefile
	@echo *** Creating linker response file <<$@
-out:$(RELEASE_IMPLIB_DLL_DBG)
$(OBJDIR_DLL_DBG)\tmp.lib
$(DLL_STATIC_OBJS_DBG)
$(SDKNAMESLIB_DIR)\sdknames.lib
$(TCMAPLIB_DIR)\tcmap.lib
$(TCMAPDLLLIB_DIR)\tcmapdll.lib
<<keep
!endif


!if "$(TARGET_CPU)"=="i386"

# {{ Beginning of block TARGET_CPU == i386 }}

#
# Make Process for Win32s version of C Run-Time DLL
#
###############################################################################

#
# In the Win32s version of the DLL, _file.obj must be explicitly linked into
# the DLL. It doesn't resolve any external references in other modules which
# cause the linker to bring it in automatically.
#

OBJS_WITH_EXPORTS_DLS = $(OBJS_WITH_EXPORTS_DLL:dll_obj=dls_obj) $(OBJDIR_DLS)\_file.obj

DLS_STATIC_OBJS = $(DLL_STATIC_OBJS:dll_obj=dls_obj)

$(RELEASE_DLS) : $(RELDIR_CPU) $(RETAIL_DLL_NAME).rc \
 $(DEFFILE_DIR)\win32s\$(RETAIL_DLL_NAME).def $(SOURCE_OBJS_DLL:*=dls) \
 $(DLS_STATIC_OBJS) $(SDKNAMESLIB_DIR)\sdknames.lib \
 $(TCMAPLIB_DIR)\tcmap.lib $(TCMAPDLLLIB_DIR)\tcmapdll.lib \
 $(V4TOOLS)\include\winver.h \
 $(OBJDIR_DLS)\link.rsp
	rc $(RC_OPTS) -Fo $(@R).res $(RC_DEFS) $(RC_INCS) $(RETAIL_DLL_NAME).rc
	$(LINKER) @$(OBJDIR_DLS)\link.rsp

!if "$(BLD_OBJ)"!="1"
$(OBJDIR_DLS)\link.rsp: makefile
	@echo *** Creating linker response file <<$@
-base:0x10200000
!if "$(DEBUG)"=="1"
-dbgimplib
-debug
-pdb:none
!else
-pdb:$(RELEASE_DLS:.dls=.pds)
!endif
-def:$(DEFFILE_DIR)\win32s\$(RETAIL_DLL_NAME).def
-dll
-entry:_CRTDLL_INIT
-force:multiple
-implib:$(OBJDIR_DLS)\tmp.lib
-incremental:no
-map:$(RELEASE_DLS:.dls=.mas)
-out:$(RELEASE_DLS)
-release
$(OBJS_WITH_EXPORTS_DLS)
$(RELEASE_DLS:.dls=.res)
$(SOURCE_OBJS_DLL:*=dls)
kernel32.lib
<<keep
!endif

#
# In the Win32s version of the DLL, _file.obj must be explicitly linked into
# the DLL. It doesn't resolve any external references in other modules which
# cause the linker to bring it in automatically.
#

OBJS_WITH_EXPORTS_DLS_DBG = $(OBJS_WITH_EXPORTS_DLL_DBG:xdll_obj=xdls_obj) $(OBJDIR_DLS_DBG)\_file.obj

DLS_STATIC_OBJS_DBG = $(DLL_STATIC_OBJS_DBG:xdll_obj=xdls_obj)

$(RELEASE_DLS_DBG) : $(RELDIR_CPU) $(RETAIL_DLL_NAME).rc \
 $(DEFFILE_DIR)\win32s\$(DEBUG_DLL_NAME).def $(SOURCE_OBJS_DLL:*=xdls) \
 $(DLS_STATIC_OBJS_DBG) $(SDKNAMESLIB_DIR)\sdknames.lib \
 $(TCMAPLIB_DIR)\tcmap.lib $(TCMAPDLLLIB_DIR)\tcmapdll.lib \
 $(V4TOOLS)\include\winver.h \
 $(OBJDIR_DLS_DBG)\link.rsp
	rc $(RC_OPTS) -Fo $(@R).res -D_DEBUG $(RC_DEFS) $(RC_INCS) $(RETAIL_DLL_NAME).rc
	$(LINKER) @$(OBJDIR_DLS_DBG)\link.rsp

!if "$(BLD_OBJ)"!="1"
$(OBJDIR_DLS_DBG)\link.rsp: makefile
	@echo *** Creating linker response file <<$@
-base:0x10200000
-dbgimplib
-debug
-def:$(DEFFILE_DIR)\win32s\$(DEBUG_DLL_NAME).def
-dll
-entry:_CRTDLL_INIT
-force:multiple
-implib:$(OBJDIR_DLS_DBG)\tmp.lib
-incremental:no
-map:$(RELEASE_DLS_DBG:.dls=.mas)
-out:$(RELEASE_DLS_DBG)
-pdb:$(RELEASE_DLS_DBG:.dls=.pds)
-release
$(OBJS_WITH_EXPORTS_DLS_DBG)
$(RELEASE_DLS_DBG:.dls=.res)
$(SOURCE_OBJS_DLL:*=xdls)
kernel32.lib
<<keep
!endif


# {{ End of block TARGET_CPU == i386 }}

!endif

# {{ End of block TARGET_CPU != M68K && TARGET_CPU != PMAC }}

!endif

# {{ End of block TARGET_CPU != M68K }}

!endif


!if "$(TARGET_CPU)" == "PMAC"

# {{ Beginning of block TARGET_CPU == PMAC }}

# PMAC DLL build

DLL_DEF_DIR=mppc

DLL_STATIC_OBJS=\
        $(OBJDIR_DLL_RAW)\_newmode.obj \
        $(OBJDIR_DLL_RAW)\atonexit.obj \
        $(OBJDIR_DLL_RAW)\crtexe.obj \
        $(OBJDIR_DLL_RAW)\cinitexe.obj \
        $(OBJDIR_DLL_RAW)\crtdllex.obj \
        $(OBJDIR_DLL_RAW)\crtdll.obj \
        $(OBJDIR_DLL_RAW)\dllmain.obj \
        $(OBJDIR_DLL_RAW)\dllexit.obj \
        $(OBJDIR_DLL_RAW)\testexit.obj \
        $(OBJDIR_DLL_RAW)\ti_inst.obj \


$(RELEASE_DLL) : $(RELDIR_CPU) $(DLL_DEF_DIR)\$(RETAIL_DLL_NAME).r \
 $(DLL_DEF_DIR)\$(RETAIL_DLL_NAME).def $(SOURCE_OBJS_DLL:*=dll) \
 $(DLL_STATIC_OBJS:*=dll) \
 $(TCMAPLIB_DIR)\tcmap.lib $(TCMAPDLLLIB_DIR)\tcmapdll.lib \
 $(OBJDIR_DLL)\link.rsp $(OBJDIR_DLL)\implib.rsp
	$(CC) -nologo -EP -Tc$(DLL_DEF_DIR)\$(RETAIL_DLL_NAME).r > $(OBJDIR_DLL)\$(RETAIL_DLL_NAME).tmp
	mrc -o $(@R).rsc $(RC_INCS) $(OBJDIR_DLL)\$(RETAIL_DLL_NAME).tmp
	$(LINKER) @$(OBJDIR_DLL)\link.rsp
	makepef $(@R).dll $(@R).pef
#	forkize /d 	$(@R).pef /r $(@R).rsc	 /o $(@R).ppc /t shlb /c cfmg
	$(LINKLIB) @$(OBJDIR_DLL)\implib.rsp

!if "$(BLD_OBJ)"!="1"
$(OBJDIR_DLL)\link.rsp: makefile
	@echo *** Creating linker response file <<$@
-def:$(DLL_DEF_DIR)\$(RETAIL_DLL_NAME).def
-dll
-machine:mppc
-implib:$(OBJDIR_DLL)\tmp.lib
-import:currentver=67141632,oldcodever=67141632,oldapiver=67141632
-incremental:no
-map
-mac:init=__cinit
-mac:term=_DllExit
-mac:creator=cfmg
-mac:type=shlb
-out:$(RELEASE_DLL)
-release
$(OBJS_WITH_EXPORTS_DLL)
$(RELEASE_DLL:.dll=.rsc)
$(SOURCE_OBJS_DLL:*=dll)
interfac.lib
<<keep

$(OBJDIR_DLL)\implib.rsp: makefile
	@echo *** Creating linker response file <<$@
-out:$(RELEASE_IMPLIB_DLL)
$(OBJDIR_DLL)\tmp.lib
$(DLL_STATIC_OBJS:*=dll)
$(TCMAPLIB_DIR)\tcmap.lib
$(TCMAPDLLLIB_DIR)\tcmapdll.lib
<<keep
!endif


$(RELEASE_DLL_DBG) : $(RELDIR_CPU) $(DLL_DEF_DIR)\$(RETAIL_DLL_NAME).r \
 $(DLL_DEF_DIR)\$(DEBUG_DLL_NAME).def $(SOURCE_OBJS_DLL:*=xdll) \
 $(DLL_STATIC_OBJS:*=dll) \
 $(TCMAPLIB_DIR)\tcmap.lib $(TCMAPDLLLIB_DIR)\tcmapdll.lib \
 $(OBJDIR_DLL_DBG)\link.rsp $(OBJDIR_DLL_DBG)\implib.rsp
	$(CC) -nologo -D_DEBUG -EP -Tc$(DLL_DEF_DIR)\$(RETAIL_DLL_NAME).r > $(OBJDIR_DLL_DBG)\$(DEBUG_DLL_NAME).tmp
	mrc -o $(@R).rsc $(RC_INCS) $(OBJDIR_DLL_DBG)\$(DEBUG_DLL_NAME).tmp
	$(LINKER) @$(OBJDIR_DLL_DBG)\link.rsp
	makepef $(@R).dll $(@R).pef
#	forkize /d 	$(@R).pef /r $(@R).rsc	 /o $(@R).ppc /t shlb /c cfmg
	$(LINKLIB) @$(OBJDIR_DLL_DBG)\implib.rsp

!if "$(BLD_OBJ)"!="1"
$(OBJDIR_DLL_DBG)\link.rsp: makefile
	@echo *** Creating linker response file <<$@
-dbgimplib
-debug
-def:$(DLL_DEF_DIR)\$(DEBUG_DLL_NAME).def
-dll
-machine:mppc
-implib:$(OBJDIR_DLL_DBG)\tmp.lib
-import:currentver=67141632,oldcodever=67141632,oldapiver=67141632
-incremental:no
-map
-mac:init=__cinit
-mac:term=_DllExit
-mac:creator=cfmg
-mac:type=shlb
-out:$(RELEASE_DLL_DBG)
-release
$(OBJS_WITH_EXPORTS_DLL_DBG)
$(RELEASE_DLL_DBG:.dll=.rsc)
$(SOURCE_OBJS_DLL:*=xdll)
interfac.lib
<<keep

$(OBJDIR_DLL_DBG)\implib.rsp: makefile
	@echo *** Creating linker response file <<$@
-out:$(RELEASE_IMPLIB_DLL_DBG)
$(OBJDIR_DLL_DBG)\tmp.lib
$(DLL_STATIC_OBJS:*=xdll)
$(TCMAPLIB_DIR)\tcmap.lib
$(TCMAPDLLLIB_DIR)\tcmapdll.lib
<<keep
!endif

# {{ End of block TARGET_CPU == PMAC }}

!endif


####
#
# Release objects
#
####

!if "$(POST_BLD)"=="1" && "$(BLD_OBJ)"=="1"

relobjs:


!else

relobjs: \
!if "$(TARGET_CPU)"=="i386"
	$(RELDIR_CPU)\fp10.obj \
!endif
!if "$(TARGET_CPU)"!="PMAC"
	$(RELDIR_CPU)\binmode.obj \
	$(RELDIR_CPU)\chkstk.obj \
	$(RELDIR_CPU)\newmode.obj \
	$(RELDIR_CPU)\setargv.obj \
	$(RELDIR_CPU)\wsetargv.obj \
!endif
	$(RELDIR_CPU)\commode.obj


!endif


$(RELDIR_CPU)\binmode.obj: $(OBJDIR_ST)\binmode.obj
	copy $** $@  >NUL

$(RELDIR_CPU)\chkstk.obj: $(OBJDIR_ST)\chkstk.obj
	copy $** $@ >NUL

$(RELDIR_CPU)\commode.obj: $(OBJDIR_ST)\commode.obj
	copy $** $@ >NUL

$(RELDIR_CPU)\newmode.obj: $(OBJDIR_ST)\newmode.obj
	copy $** $@ >NUL

$(RELDIR_CPU)\setargv.obj: $(OBJDIR_ST)\setargv.obj
	copy $** $@ >NUL

$(RELDIR_CPU)\wsetargv.obj: $(OBJDIR_ST)\wsetargv.obj
	copy $** $@ >NUL

!if "$(TARGET_CPU)"=="i386"
$(RELDIR_CPU)\fp10.obj: $(OBJDIR_ST)\fp10.obj
	copy $** $@ >NUL
!endif

#<eof>
