All:
!IFDEF NODEBUG
   nmake /f Data.mak CFG="Data - Win32 Release MinSize" -nologo /$(MAKEFLAGS) $(makeopts)
!ELSE
   nmake /f Data.mak CFG="Data - Win32 Debug" -nologo /$(MAKEFLAGS) $(makeopts)
!ENDIF
