#
# Microsoft Windows MEMSET.EXE Makefile
#

#
# You can create a debug version of MEMSET.EXE for use with CodeView.
# simply add the following flags to the command line of each Makefile
# build line:
#
# For .ASM files, the command line should read:
#
#       masm -Zi -z-t-Mx-b63 filename;
# 
# For .C files, the command line should read:
# 
#       cl -Zi -D DEBUG -c -Od;


#
#  First, compile the .C files using the C compiler supplied with this OEM kit.
#  Also, make sure to use the .H files supplied with the OEM kit.
#

memscr.obj: memscr.c setup.h
#        cl -Zi -D DEBUG -c -Od memscr.c
        cl -c -Os memscr.c

graphics.obj: graphics.c setup.h
#        cl -Zi -D DEBUG -c -Od graphics.c
        cl -c -Os graphics.c

memset.obj: memset.c setup.h
#        cl -Zi -D DEBUG -c -Od memset.c
        cl -c -Os memset.c

memout.obj: memout.c setup.h memdef.h
#        cl -Zi -D DEBUG -c -Od memout.c
        cl -c -Os memout.c

memdata.obj: memdata.c setup.h
#        cl -Zi -D DEBUG -c -Od memdata.c
        cl -c -Os memdata.c
                                        
#
# Now, compile the .ASM files under MASM v5.10 or above:
#

lmemcmp.obj: lmemcmp.asm    
#        masm -Zi -z-t-Mx-b63 lmemcmp;
        masm -z-t-Mx-b63 lmemcmp;

cmos.obj: cmos.asm
#        masm -Zi -z-t-Mx-b63 cmos;
        masm -z-t-Mx-b63 cmos;


subs.obj: subs.asm
#        masm -Zi -z-t-Mx-b63 subs;
        masm -z-t-Mx-b63 subs;
                                                                 
#
# Now link the .OBJ files into MEMSET.EXE.  Make sure to use the .LIB
# files supplied with the OEM kit.
#

memset.exe:     memscr.obj lmemcmp.obj cmos.obj subs.obj makefile \
                memset.obj memout.obj graphics.obj memdata.obj
        link4 @memset.lnk

