

; 3Com NETBIOS Protocol
[NBP]
  DRIVERNAME = NBP$
  BINDINGS =
  DEFAULTS = USER

BINDINGS specifies the mac driver you wish to bind to.

    ie. BINDINGS = ETHERLINKII

DEFAULTS can be either LIGHT-USER, USER, POWER-USER, SERVER, POWER-SERVER.


