#   Windows EGA color, EGA monochrome, and Hercules resource build file
#

color.obj:      color.asm
    masm -z-t-Ml-b63 color;

blkwhite.obj:   blkwhite.asm
    masm -z-t-Ml-b63 blkwhite;

config.obj:	config.asm
    masm -z-t-b63 config;

cconfig.bin:    config.obj color.obj
    link config color.obj,cconfig;
    exe2bin cconfig
    erase cconfig.exe

bconfig.bin:    config.obj blkwhite.obj
    link config blkwhite.obj,bconfig;
    exe2bin bconfig
    erase bconfig.exe

fonts.obj:	fonts.asm
    masm -z-t-b63 fonts;

fonts.bin:	fonts.obj
    link fonts;
    exe2bin fonts
    erase fonts.exe

# First build the color resource. This resource is intended for use 
# by the sample EGAHIRES color driver.  Then, build the monochrome
# resource.  The monochrome resource is copied to EGAHIBW.RES and
# HERCULES.RES and is appropriate for those sample drivers.

egahires.res:   egaherc.rc    cconfig.bin                         \
		normal.cur   ibeam.cur	  wait.cur    cross.cur   \
		up.cur	     size.cur	  icon.cur    sample.ico  \
		hand.ico     ques.ico	  bang.ico    note.ico	  \
		right.bmp    left.bmp	  up.bmp      down.bmp	  \
		check.bmp    btsize.bmp   size.bmp    close.bmp   \
		button.bmp   btncorn.bmp  fonts.bin   hizoom.bmp  \
		sizenwse.cur sizenesw.cur sizewe.cur  sizens.cur  \
		hired.bmp
    copy cconfig.bin config.bin
    rc -r egaherc.rc
    copy egaherc.res egahires.res
    erase config.bin
    erase egaherc.res

egaherc.res:    egaherc.rc   bconfig.bin                          \
		normal.cur   ibeam.cur	  wait.cur    cross.cur   \
		up.cur	     size.cur	  icon.cur    sample.ico  \
		hand.ico     ques.ico	  bang.ico    note.ico	  \
		right.bmp    left.bmp	  up.bmp      down.bmp	  \
		check.bmp    btsize.bmp   size.bmp    close.bmp   \
		button.bmp   btncorn.bmp  fonts.bin   hizoom.bmp  \
		sizenwse.cur sizenesw.cur sizewe.cur  sizens.cur  \
		hired.bmp
    copy bconfig.bin config.bin
    rc -r egaherc.rc
    copy egaherc.res egahibw.res
    copy egaherc.res hercules.res
    erase config.bin
    erase egaherc.res
