# Microsoft Windows SMARTDRV Makefile
#                         

smartdrv.obj:   smartdrv.asm mi.asm loadall.asm ab_macro.asm \
                syscall.asm emm.asm above.asm devsym.asm
        masm -z-t-b63 smartdrv.asm;

smartdrv.sys: smartdrv.obj
        link4 smartdrv,,smartdrv/M;
        exe2bin smartdrv smartdrv.sys
        erase smartdrv.exe
