#   Windows EGA & VGA driver makefile.
#
#       Since these two drivers are so similar (differing only in their
# screen height (EGA has 350 scanlines and VGA has 480 scanlines), they
# are made together.  If you have no use for one or the other driver, you
# can delete the device specific portions of this Makefile and get rid of
# the files that are unneeded.
#
#   Requirements:
#
#       MASM 5.10 or greater with the environment variable INCLUDE set to
#	the directories containing CMACROS.INC, GDIDEFS.INC, and WINDEFS.INC.
#

#   Define the dependencies

inquire.obj:    inquire.asm
        masm -z-t-Ml-b63 inquire;

setmode.obj:   setmode.asm
        masm -z-t-Ml-b63 setmode;

enable.obj:   enable.asm
        masm -z-t-Ml-b63 enable;

disable.obj:   disable.asm
        masm -z-t-Ml-b63 disable;

chkstk.obj:   chkstk.asm
        masm -z-t-Ml-b63 chkstk;

cursors.obj:   cursors.asm
        masm -z-t-Ml-b63 cursors;

control.obj:   control.asm
        masm -z-t-Ml-b63 control;

fb.obj:   fb.asm
        masm -z-t-Ml-b63 fb;

charwdth.obj:   charwdth.asm fontseg.inc
        masm -z-t-Ml-b63 charwdth;

dither.obj:     dither.asm
        masm -z-t-Ml-b63 dither;

sswitch.obj:   sswitch.asm
        masm -z-t-Ml-b63 sswitch;

robject.obj:    robject.asm
        masm -z-t-Ml-b63 robject;

enum.obj:       enum.asm         
        masm -z-t-Ml-b63 enum;

colorinf.obj:   colorinf.asm
        masm -z-t-Ml-b63 colorinf;

pixel.obj:   pixel.asm
        masm -DDEBUG -z-t-Ml-b63 pixel;

cblt.obj:                    cblt.asm           \
		             genlocal.blt	\
		             genconst.blt	\
		             gendata.blt	\
		             ropdefs.blt	\
		             roptable.blt	\
			     clrlocal.blt	\
			     clrconst.blt	\
			     clrdata.blt	\
			     devlocal.blt	\
			     devconst.blt	\
			     devdata.blt
        masm -DDEBUG -z-t-Ml-b63 cblt;

output.obj:   output.asm
        masm -DDEBUG -z-t-Ml-b63 output;

scanlr.obj:   scanlr.asm
        masm -DDEBUG -z-t-Ml-b63 scanlr;

egainit.obj: egainit.asm
        masm -DDEBUG -z-t-Ml-b63 egainit;

egastate.obj:   egastate.asm
        masm -DDEBUG -z-t-Ml-b63 egastate;

scanline.obj:   scanline.asm
        masm -DDEBUG -z-t-Ml-b63 scanline;

polyline.obj:   polyline.asm polyline.inc plylocal.inc
        masm -DDEBUG -z-t-Ml-b63 polyline;

plysolid.obj:   plysolid.asm polyline.inc plylocal.inc polyline.mac
        masm -DDEBUG -z-t-Ml-b63 plysolid;

polybitm.obj:   polybitm.asm polyline.inc plylocal.inc polyline.mac
        masm -DDEBUG -z-t-Ml-b63 polybitm;

polystyl.obj:   polystyl.asm polyline.inc plylocal.inc polyline.mac
        masm -DDEBUG -z-t-Ml-b63 polystyl;

strblt.obj:   strblt.asm   strblt.inc fontseg.inc
        masm -DDEBUG -z-t-Ml-b63 strblt;

buildstr.obj:   buildstr.asm strblt.inc fontseg.inc
        masm -DDEBUG -z-t-Ml-b63 buildstr;

smartfix.obj:   smartfix.asm strblt.inc fontseg.inc
        masm -DDEBUG -z-t-Ml-b63 smartfix;

smartpro.obj:   smartpro.asm strblt.inc fontseg.inc
        masm -DDEBUG -z-t-Ml-b63 smartpro;

ssb.obj:   ssb.asm
        masm -DDEBUG -z-t-Ml-b63 ssb;

3xswitch.obj:   3xswitch.asm
        masm -DDEBUG -z-t-Ml-b63 3xswitch;

bitblt.obj:	                bitblt.asm	\
		                genlocal.blt	\
		                genconst.blt	\
		                gendata.blt	\
		                ropdefs.blt	\
		                roptable.blt	\
			        clrlocal.blt	\
			        clrconst.blt	\
			        clrdata.blt	\
			        pdevice.blt	\
			        pattern.blt	\
			        copydev.blt	\
			        devlocal.blt	\
			        devconst.blt	\
			        computey.blt	\
			        special.blt	\
                                exit.blt        \
                                cursor.inc
        masm -z-t-Ml-b63 bitblt;            

# Since a few equates in CURSOR.INC are different between the EGA color 
# and VGA drivers, we build two versions of the .OBJ files which are linked
# into their respective drivers.

egacursr.obj:   cursor.asm egamemd.inc cursor.inc
        masm -DEGAHIRES -z-t-Ml-b63 cursor,egacursr;

vgacursr.obj:   cursor.asm egamemd.inc cursor.inc
        masm -DVGA -z-t-Ml-b63 cursor,vgacursr;

# The file EGAHIRES.ASM is used only for building the EGA color driver.

egahires.obj:	egahires.asm
        masm -DEGAHIRES -z-t-Ml-b63 egahires;
                               
# The file VGA.ASM is used only for building the VGA driver.

vga.obj:        vga.asm
        masm -DVGA -z-t-Ml-b63 vga;

egahires.drv: egahires.def egahires.lnk egahires.res            \
                         egahires.obj          egacursr.obj     \
		         bitblt.obj				\
		         egastate.obj	       cblt.obj 	\
		         pixel.obj	       polystyl.obj	\
		         output.obj	       polyline.obj	\
		         plysolid.obj	       polybitm.obj	\
		         strblt.obj	       buildstr.obj	\
		         smartfix.obj	       smartpro.obj	\
		         scanline.obj	       scanlr.obj	\
		         ssb.obj	       egainit.obj	\
		         3xswitch.obj				\
		         robject.obj	       colorinf.obj	\
		         enum.obj				\
		         control.obj           cursors.obj	\
		         inquire.obj           setmode.obj	\
                         dither.obj            disable.obj      \
		         enable.obj            chkstk.obj	\
		         charwdth.obj          fb.obj		\
		         sswitch.obj
    link4 @egahires.lnk
    rc egahires.res egahires.drv
    copy egahires.map display.map
    mapsym display      
    command /c del display.map
    copy display.sym egahires.sym
    command /c del display.sym


ibmps250.drv:            vga.def vga.lnk vga.res                \
                         vga.obj               vgacursr.obj     \
		         bitblt.obj				\
		         egastate.obj	       cblt.obj 	\
		         pixel.obj	       polystyl.obj	\
		         output.obj	       polyline.obj	\
		         plysolid.obj	       polybitm.obj	\
		         strblt.obj	       buildstr.obj	\
		         smartfix.obj	       smartpro.obj	\
		         scanline.obj	       scanlr.obj	\
		         ssb.obj	       egainit.obj	\
		         3xswitch.obj				\
		         robject.obj	       colorinf.obj	\
		         enum.obj				\
		         control.obj           cursors.obj	\
		         inquire.obj           setmode.obj	\
                         dither.obj            disable.obj      \
		         enable.obj            chkstk.obj	\
		         charwdth.obj          fb.obj		\
		         sswitch.obj
    link4 @vga.lnk
    rc vga.res ibmps250.drv
    copy ibmps250.map display.map
    mapsym display      
    command /c del display.map
    copy display.sym ibmps250.sym
    command /c del display.sym
