# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (C) 1992 Microsoft Corporation
# All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and Microsoft
# QuickHelp and/or WinHelp documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=PROPDLG
OBJS=colorpge.obj minifrm.obj preview.obj propdlg.obj propsht.obj \
	propsht2.obj shapedoc.obj shapeobj.obj shapesvw.obj stylepge.obj \
	mainfrm.obj

!if "$(PLATFORM)" == "MAC_68K" || "$(PLATFORM)" == "MAC_PPC"
MACPROJ=PropDlg
MACSIG=PROP
!endif

!include ..\sample_.mak
