OS=DOS
ENV=WIN16

# If this generates the error "Unable to open DOSWIN16.MAK" then you need
# to put a copy of that file (from the GENERIC sample code directory)
# into a directory on your INCLUDE environment variable

!include <$(OS)$(ENV).MAK>

proj = utsamp

all: $(proj)16.dll


# Update the object file if necessary
$(proj)16.obj: $*.c $(proj).h
    $(cc) $(cflags) $(cvars) $(cdebug) /Od /Zi $*.c


$(proj)16.dll: $*.obj $*.def
    $(link) $(guiflags) $*.obj libentry.obj, $*.dll,$*.map,libw mlibcew, $*.DEF /LI /CO /MAP
